import type { Deck } from '../../types'

// B2 — the top of the learning ladder. Six decks, all level 4.
//
// pos rules (load-bearing — isTypable excludes 'phrase' and 'grammar'):
// - 'phrase' for multi-word expressions (most of phrasal/connectors/opinions/idioms)
// - 'grammar' for every card in `tenses`, so a nine-word conditional is never typed
// - 'word' / 'noun' / 'verb' / 'adj' for genuine single tokens, which keeps them typable

const phrasal: Deck = {
  id: 'phrasal', name: 'Phrasal verbs', emoji: '🔗',
  desc: 'Two small words, one new meaning', level: 4,
  cards: [
    {
      id: 'phrasal_0', deckId: 'phrasal',
      en: 'pick up', pt: 'pegar / buscar',
      exampleHtml: "I'll <b>pick up</b> the kids at three.",
      examplePt: 'Eu vou buscar as crianças às três.',
      pos: 'phrase',
    },
    {
      id: 'phrasal_1', deckId: 'phrasal',
      en: 'give up', pt: 'desistir',
      exampleHtml: 'She almost <b>gave up</b> on the course.',
      examplePt: 'Ela quase desistiu do curso.',
      pos: 'phrase',
    },
    {
      id: 'phrasal_2', deckId: 'phrasal',
      en: 'look after', pt: 'cuidar de',
      exampleHtml: 'Can you <b>look after</b> the cat?',
      examplePt: 'Você pode cuidar do gato?',
      pos: 'phrase',
    },
    {
      id: 'phrasal_3', deckId: 'phrasal',
      en: 'sort out', pt: 'resolver / organizar',
      exampleHtml: 'We need to <b>sort out</b> the roster.',
      examplePt: 'Precisamos resolver a escala.',
      pos: 'phrase',
    },
    {
      id: 'phrasal_4', deckId: 'phrasal',
      en: 'run out of', pt: 'ficar sem',
      exampleHtml: 'We <b>ran out of</b> milk again.',
      examplePt: 'Ficamos sem leite de novo.',
      pos: 'phrase',
    },
    {
      id: 'phrasal_5', deckId: 'phrasal',
      en: 'deal with', pt: 'lidar com',
      exampleHtml: "I'll <b>deal with</b> it tomorrow.",
      examplePt: 'Eu vou lidar com isso amanhã.',
      pos: 'phrase',
    },
    {
      id: 'phrasal_6', deckId: 'phrasal',
      en: 'get on with', pt: 'se dar bem com',
      exampleHtml: 'She <b>gets on with</b> her new boss.',
      examplePt: 'Ela se dá bem com o novo chefe.',
      pos: 'phrase',
    },
    {
      id: 'phrasal_7', deckId: 'phrasal',
      en: 'put up with', pt: 'tolerar / suportar',
      exampleHtml: "I can't <b>put up with</b> the noise.",
      examplePt: 'Eu não aguento o barulho.',
      pos: 'phrase',
    },
    {
      id: 'phrasal_8', deckId: 'phrasal',
      en: 'figure out', pt: 'descobrir / entender',
      exampleHtml: "Let's <b>figure out</b> a plan.",
      examplePt: 'Vamos descobrir um plano.',
      pos: 'phrase',
    },
    {
      id: 'phrasal_9', deckId: 'phrasal',
      en: 'turn up', pt: 'aparecer / chegar',
      exampleHtml: 'He <b>turned up</b> an hour late.',
      examplePt: 'Ele apareceu uma hora atrasado.',
      pos: 'phrase',
    },
    {
      id: 'phrasal_10', deckId: 'phrasal',
      en: 'drop off', pt: 'deixar (alguém/algo)',
      exampleHtml: "I'll <b>drop off</b> the forms today.",
      examplePt: 'Vou deixar os formulários hoje.',
      pos: 'phrase',
    },
    {
      id: 'phrasal_11', deckId: 'phrasal',
      en: 'take off', pt: 'decolar / tirar (roupa)',
      exampleHtml: 'The flight <b>takes off</b> at six.',
      examplePt: 'O voo decola às seis.',
      pos: 'phrase',
    },
    {
      id: 'phrasal_12', deckId: 'phrasal',
      en: 'come across', pt: 'encontrar por acaso',
      exampleHtml: 'I <b>came across</b> an old photo.',
      examplePt: 'Eu encontrei uma foto antiga por acaso.',
      pos: 'phrase',
    },
    {
      id: 'phrasal_13', deckId: 'phrasal',
      en: 'get by', pt: 'se virar (com o que tem)',
      exampleHtml: 'We <b>get by</b> on one income.',
      examplePt: 'Nós nos viramos com uma renda só.',
      pos: 'phrase',
    },
    {
      id: 'phrasal_14', deckId: 'phrasal',
      en: 'look into', pt: 'investigar / analisar',
      exampleHtml: 'The manager will <b>look into</b> it.',
      examplePt: 'O gerente vai investigar isso.',
      pos: 'phrase',
    },
    {
      id: 'phrasal_15', deckId: 'phrasal',
      en: 'sign up', pt: 'se inscrever',
      exampleHtml: 'I <b>signed up</b> for a gym.',
      examplePt: 'Eu me inscrevi numa academia.',
      pos: 'phrase',
    },
    {
      id: 'phrasal_16', deckId: 'phrasal',
      en: 'work out', pt: 'dar certo / se resolver',
      exampleHtml: 'It all <b>worked out</b> fine.',
      examplePt: 'Tudo deu certo no final.',
      pos: 'phrase',
    },
    {
      id: 'phrasal_17', deckId: 'phrasal',
      en: 'bring up', pt: 'mencionar',
      exampleHtml: "Don't <b>bring up</b> the rent again.",
      examplePt: 'Não mencione o aluguel de novo.',
      pos: 'phrase',
    },
    {
      id: 'phrasal_18', deckId: 'phrasal',
      en: 'call off', pt: 'cancelar',
      exampleHtml: 'They <b>called off</b> the meeting.',
      examplePt: 'Eles cancelaram a reunião.',
      pos: 'phrase',
    },
    {
      id: 'phrasal_19', deckId: 'phrasal',
      en: 'carry on', pt: 'continuar',
      exampleHtml: '<b>Carry on</b> without me.',
      examplePt: 'Continue sem mim.',
      pos: 'phrase',
    },
    {
      id: 'phrasal_20', deckId: 'phrasal',
      en: 'end up', pt: 'acabar (fazendo algo)',
      exampleHtml: 'We <b>ended up</b> missing the bus.',
      examplePt: 'Acabamos perdendo o ônibus.',
      pos: 'phrase',
    },
    {
      id: 'phrasal_21', deckId: 'phrasal',
      en: 'fill in', pt: 'preencher',
      exampleHtml: 'Please <b>fill in</b> this form.',
      examplePt: 'Por favor, preencha este formulário.',
      pos: 'phrase',
    },
    {
      id: 'phrasal_22', deckId: 'phrasal',
      en: 'hand in', pt: 'entregar',
      exampleHtml: 'I need to <b>hand in</b> my timesheet.',
      examplePt: 'Eu preciso entregar minha planilha de horas.',
      pos: 'phrase',
    },
    {
      id: 'phrasal_23', deckId: 'phrasal',
      en: 'hold on', pt: 'esperar / aguardar',
      exampleHtml: "<b>Hold on</b>, I'm nearly ready.",
      examplePt: 'Espera, já estou quase pronta.',
      pos: 'phrase',
    },
    {
      id: 'phrasal_24', deckId: 'phrasal',
      en: 'look forward to', pt: 'estar ansioso por',
      exampleHtml: 'I <b>look forward to</b> the weekend.',
      examplePt: 'Estou ansioso pelo fim de semana.',
      pos: 'phrase',
    },
    {
      id: 'phrasal_25', deckId: 'phrasal',
      en: 'pull over', pt: 'encostar (o carro)',
      exampleHtml: 'The cop asked us to <b>pull over</b>.',
      examplePt: 'O policial pediu para encostarmos.',
      pos: 'phrase',
    },
    {
      id: 'phrasal_26', deckId: 'phrasal',
      en: 'put off', pt: 'postergar / adiar',
      exampleHtml: "Don't <b>put off</b> the dentist again.",
      examplePt: 'Não adie o dentista de novo.',
      pos: 'phrase',
    },
    {
      id: 'phrasal_27', deckId: 'phrasal',
      en: 'set up', pt: 'montar / configurar',
      exampleHtml: 'We <b>set up</b> the new printer.',
      examplePt: 'Nós configuramos a impressora nova.',
      pos: 'phrase',
    },
  ],
}

const connectors: Deck = {
  id: 'connectors', name: 'Connectors & linkers', emoji: '🧩',
  desc: 'Joining ideas like a fluent speaker', level: 4,
  cards: [
    {
      id: 'connectors_0', deckId: 'connectors',
      en: 'however', pt: 'porém / entretanto',
      exampleHtml: '<b>However</b>, the bus was late.',
      examplePt: 'Porém, o ônibus estava atrasado.',
      pos: 'word',
    },
    {
      id: 'connectors_1', deckId: 'connectors',
      en: 'although', pt: 'embora / apesar de',
      exampleHtml: '<b>Although</b> tired, she went for a run.',
      examplePt: 'Embora cansada, ela foi correr.',
      pos: 'word',
    },
    {
      id: 'connectors_2', deckId: 'connectors',
      en: 'therefore', pt: 'portanto',
      exampleHtml: '<b>Therefore</b>, we decided to stay home.',
      examplePt: 'Portanto, decidimos ficar em casa.',
      pos: 'word',
    },
    {
      id: 'connectors_3', deckId: 'connectors',
      en: 'on the other hand', pt: 'por outro lado',
      exampleHtml: '<b>On the other hand</b>, rent is cheaper here.',
      examplePt: 'Por outro lado, o aluguel é mais barato aqui.',
      pos: 'phrase',
    },
    {
      id: 'connectors_4', deckId: 'connectors',
      en: 'as soon as', pt: 'assim que',
      exampleHtml: 'Call me <b>as soon as</b> you land.',
      examplePt: 'Me ligue assim que você aterrissar.',
      pos: 'phrase',
    },
    {
      id: 'connectors_5', deckId: 'connectors',
      en: 'in order to', pt: 'para / a fim de',
      exampleHtml: 'She saved money <b>in order to</b> travel.',
      examplePt: 'Ela economizou dinheiro para viajar.',
      pos: 'phrase',
    },
    {
      id: 'connectors_6', deckId: 'connectors',
      en: 'even though', pt: 'mesmo que / ainda que',
      exampleHtml: '<b>Even though</b> it rained, we went out.',
      examplePt: 'Mesmo tendo chovido, nós saímos.',
      pos: 'phrase',
    },
    {
      id: 'connectors_7', deckId: 'connectors',
      en: 'meanwhile', pt: 'enquanto isso',
      exampleHtml: '<b>Meanwhile</b>, the kettle started to boil.',
      examplePt: 'Enquanto isso, a chaleira começou a ferver.',
      pos: 'word',
    },
    {
      id: 'connectors_8', deckId: 'connectors',
      en: 'whereas', pt: 'enquanto / ao passo que',
      exampleHtml: 'I like tea, <b>whereas</b> she prefers coffee.',
      examplePt: 'Eu gosto de chá, enquanto ela prefere café.',
      pos: 'word',
    },
    {
      id: 'connectors_9', deckId: 'connectors',
      en: 'nevertheless', pt: 'mesmo assim / apesar disso',
      exampleHtml: '<b>Nevertheless</b>, they carried on with the plan.',
      examplePt: 'Mesmo assim, eles seguiram com o plano.',
      pos: 'word',
    },
    {
      id: 'connectors_10', deckId: 'connectors',
      en: 'in addition', pt: 'além disso',
      exampleHtml: '<b>In addition</b>, the flat has off-street parking.',
      examplePt: 'Além disso, o flat tem estacionamento privado.',
      pos: 'phrase',
    },
    {
      id: 'connectors_11', deckId: 'connectors',
      en: 'as a result', pt: 'como resultado / por consequência',
      exampleHtml: '<b>As a result</b>, the meeting was postponed.',
      examplePt: 'Como resultado, a reunião foi adiada.',
      pos: 'phrase',
    },
    {
      id: 'connectors_12', deckId: 'connectors',
      en: 'for instance', pt: 'por exemplo',
      exampleHtml: 'Some Kiwis, <b>for instance</b>, love rugby.',
      examplePt: 'Alguns neozelandeses, por exemplo, amam rúgbi.',
      pos: 'phrase',
    },
    {
      id: 'connectors_13', deckId: 'connectors',
      en: 'in fact', pt: 'na verdade / de fato',
      exampleHtml: '<b>In fact</b>, the GP is running late.',
      examplePt: 'Na verdade, o médico está atrasado.',
      pos: 'phrase',
    },
    {
      id: 'connectors_14', deckId: 'connectors',
      en: 'otherwise', pt: 'senão / caso contrário',
      exampleHtml: 'Lock the door, <b>otherwise</b> the cat escapes.',
      examplePt: 'Trave a porta, senão o gato escapa.',
      pos: 'word',
    },
    {
      id: 'connectors_15', deckId: 'connectors',
      en: 'despite', pt: 'apesar de',
      exampleHtml: '<b>Despite</b> the rain, she caught the bus.',
      examplePt: 'Apesar da chuva, ela pegou o ônibus.',
      pos: 'word',
    },
    {
      id: 'connectors_16', deckId: 'connectors',
      en: 'unless', pt: 'a menos que',
      exampleHtml: "We'll be late <b>unless</b> we hurry.",
      examplePt: 'Vamos nos atrasar a menos que corramos.',
      pos: 'word',
    },
    {
      id: 'connectors_17', deckId: 'connectors',
      en: 'while', pt: 'enquanto',
      exampleHtml: 'She read <b>while</b> waiting for the bus.',
      examplePt: 'Ela leu enquanto esperava o ônibus.',
      pos: 'word',
    },
    {
      id: 'connectors_18', deckId: 'connectors',
      en: 'besides', pt: 'além disso / aliás',
      exampleHtml: '<b>Besides</b>, the flat is close to work.',
      examplePt: 'Além disso, o flat é perto do trabalho.',
      pos: 'word',
    },
    {
      id: 'connectors_19', deckId: 'connectors',
      en: 'so that', pt: 'para que',
      exampleHtml: "I left early <b>so that</b> I'd arrive on time.",
      examplePt: 'Eu saí mais cedo para chegar na hora.',
      pos: 'phrase',
    },
    {
      id: 'connectors_20', deckId: 'connectors',
      en: 'rather than', pt: 'em vez de',
      exampleHtml: 'She walked <b>rather than</b> took the bus.',
      examplePt: 'Ela foi a pé em vez de pegar o ônibus.',
      pos: 'phrase',
    },
    {
      id: 'connectors_21', deckId: 'connectors',
      en: 'at the same time', pt: 'ao mesmo tempo',
      exampleHtml: 'He studied and worked <b>at the same time</b>.',
      examplePt: 'Ele estudava e trabalhava ao mesmo tempo.',
      pos: 'phrase',
    },
  ],
}

const opinions: Deck = {
  id: 'opinions', name: 'Opinions & discussion', emoji: '💭',
  desc: 'Saying what you think without sounding blunt', level: 4,
  cards: [
    {
      id: 'opinions_0', deckId: 'opinions',
      en: 'I reckon…', pt: 'eu acho / eu diria',
      exampleHtml: "<b>I reckon</b> it'll rain later.",
      examplePt: 'Eu acho que vai chover mais tarde.',
      pos: 'phrase',
    },
    {
      id: 'opinions_1', deckId: 'opinions',
      en: "I'd say…", pt: 'eu diria que',
      exampleHtml: "<b>I'd say</b> it's worth the price.",
      examplePt: 'Eu diria que vale o preço.',
      pos: 'phrase',
    },
    {
      id: 'opinions_2', deckId: 'opinions',
      en: 'to be honest', pt: 'para ser sincero',
      exampleHtml: "<b>To be honest</b>, I didn't enjoy it.",
      examplePt: 'Para ser sincero, eu não gostei.',
      pos: 'phrase',
    },
    {
      id: 'opinions_3', deckId: 'opinions',
      en: 'it depends', pt: 'depende',
      exampleHtml: '<b>It depends</b> on the weather.',
      examplePt: 'Depende do tempo.',
      pos: 'phrase',
    },
    {
      id: 'opinions_4', deckId: 'opinions',
      en: 'the thing is…', pt: 'a questão é que',
      exampleHtml: "<b>The thing is</b>, I'm not free Friday.",
      examplePt: 'A questão é que não estou livre na sexta.',
      pos: 'phrase',
    },
    {
      id: 'opinions_5', deckId: 'opinions',
      en: "I'm not sure I agree", pt: 'não tenho certeza se concordo',
      exampleHtml: "<b>I'm not sure I agree</b> with that.",
      examplePt: 'Não tenho certeza se concordo com isso.',
      pos: 'phrase',
    },
    {
      id: 'opinions_6', deckId: 'opinions',
      en: 'fair enough', pt: 'tudo bem / justo',
      exampleHtml: '<b>Fair enough</b>, I see your point.',
      examplePt: 'Tudo bem, entendo seu ponto.',
      pos: 'phrase',
    },
    {
      id: 'opinions_7', deckId: 'opinions',
      en: 'I see your point', pt: 'entendo seu ponto',
      exampleHtml: '<b>I see your point</b>, but I disagree.',
      examplePt: 'Entendo seu ponto, mas discordo.',
      pos: 'phrase',
    },
    {
      id: 'opinions_8', deckId: 'opinions',
      en: 'from my point of view', pt: 'do meu ponto de vista',
      exampleHtml: "<b>From my point of view</b>, it's too pricey.",
      examplePt: 'Do meu ponto de vista, está muito caro.',
      pos: 'phrase',
    },
    {
      id: 'opinions_9', deckId: 'opinions',
      en: "I'd rather…", pt: 'eu preferiria',
      exampleHtml: "<b>I'd rather</b> walk than wait for a bus.",
      examplePt: 'Eu preferiria ir a pé do que esperar o ônibus.',
      pos: 'phrase',
    },
    {
      id: 'opinions_10', deckId: 'opinions',
      en: 'personally', pt: 'pessoalmente',
      exampleHtml: '<b>Personally</b>, I prefer flat whites.',
      examplePt: 'Pessoalmente, eu prefiro flat white.',
      pos: 'word',
    },
    {
      id: 'opinions_11', deckId: 'opinions',
      en: 'that makes sense', pt: 'isso faz sentido',
      exampleHtml: '<b>That makes sense</b>, thanks for explaining.',
      examplePt: 'Isso faz sentido, obrigado por explicar.',
      pos: 'phrase',
    },
    {
      id: 'opinions_12', deckId: 'opinions',
      en: "I'm not fussed", pt: 'tanto faz para mim',
      exampleHtml: "<b>I'm not fussed</b>, you choose.",
      examplePt: 'Tanto faz pra mim, você escolhe.',
      pos: 'phrase',
    },
    {
      id: 'opinions_13', deckId: 'opinions',
      en: 'up to you', pt: 'você que decide',
      exampleHtml: "It's <b>up to you</b>, really.",
      examplePt: 'É você que decide, na verdade.',
      pos: 'phrase',
    },
    {
      id: 'opinions_14', deckId: 'opinions',
      en: 'I doubt it', pt: 'eu duvido',
      exampleHtml: 'Will it rain? <b>I doubt it</b>.',
      examplePt: 'Vai chover? Eu duvido.',
      pos: 'phrase',
    },
    {
      id: 'opinions_15', deckId: 'opinions',
      en: 'as far as I know', pt: 'pelo que eu sei',
      exampleHtml: "<b>As far as I know</b>, the shop's open.",
      examplePt: 'Pelo que eu sei, a loja está aberta.',
      pos: 'phrase',
    },
    {
      id: 'opinions_16', deckId: 'opinions',
      en: 'if you ask me', pt: 'na minha opinião',
      exampleHtml: "<b>If you ask me</b>, it's overpriced.",
      examplePt: 'Na minha opinião, está caro demais.',
      pos: 'phrase',
    },
    {
      id: 'opinions_17', deckId: 'opinions',
      en: "it's worth…", pt: 'vale a pena',
      exampleHtml: "<b>It's worth</b> the extra ten dollars.",
      examplePt: 'Vale a pena os dez dólares extras.',
      pos: 'phrase',
    },
    {
      id: 'opinions_18', deckId: 'opinions',
      en: "I'd argue that…", pt: 'eu diria que / eu argumentaria que',
      exampleHtml: "<b>I'd argue that</b> renting is smarter now.",
      examplePt: 'Eu diria que alugar é mais inteligente agora.',
      pos: 'phrase',
    },
    {
      id: 'opinions_19', deckId: 'opinions',
      en: 'on balance', pt: 'no geral / considerando tudo',
      exampleHtml: '<b>On balance</b>, the course was worth it.',
      examplePt: 'No geral, o curso valeu a pena.',
      pos: 'phrase',
    },
    {
      id: 'opinions_20', deckId: 'opinions',
      en: 'to be fair', pt: 'para ser justo',
      exampleHtml: '<b>To be fair</b>, the bus was early today.',
      examplePt: 'Para ser justo, o ônibus chegou adiantado hoje.',
      pos: 'phrase',
    },
    {
      id: 'opinions_21', deckId: 'opinions',
      en: 'I take your point', pt: 'entendo seu argumento',
      exampleHtml: '<b>I take your point</b>, but I still disagree.',
      examplePt: 'Entendo seu argumento, mas ainda discordo.',
      pos: 'phrase',
    },
  ],
}

const workplace: Deck = {
  id: 'workplace', name: 'Work & professional', emoji: '🗂️',
  desc: 'Payslips, contracts and Kiwi office life', level: 4,
  cards: [
    {
      id: 'workplace_0', deckId: 'workplace',
      en: 'deadline', pt: 'prazo (final)',
      exampleHtml: 'The <b>deadline</b> is next Friday.',
      examplePt: 'O prazo é na próxima sexta.',
      pos: 'noun',
    },
    {
      id: 'workplace_1', deckId: 'workplace',
      en: 'roster', pt: 'escala de trabalho',
      exampleHtml: 'Check the <b>roster</b> for your shifts.',
      examplePt: 'Confira a escala para ver seus turnos.',
      pos: 'noun',
    },
    {
      id: 'workplace_2', deckId: 'workplace',
      en: 'sign off', pt: 'aprovar / dar aval',
      exampleHtml: 'My manager needs to <b>sign off</b> on it.',
      examplePt: 'Meu gerente precisa dar aval nisso.',
      pos: 'phrase',
    },
    {
      id: 'workplace_3', deckId: 'workplace',
      en: 'follow up', pt: 'dar retorno',
      exampleHtml: "I'll <b>follow up</b> with the client tomorrow.",
      examplePt: 'Vou dar retorno para o cliente amanhã.',
      pos: 'phrase',
    },
    {
      id: 'workplace_4', deckId: 'workplace',
      en: 'in charge of', pt: 'responsável por',
      exampleHtml: "She's <b>in charge of</b> the roster.",
      examplePt: 'Ela é responsável pela escala.',
      pos: 'phrase',
    },
    {
      id: 'workplace_5', deckId: 'workplace',
      en: 'take on', pt: 'assumir (uma tarefa)',
      exampleHtml: 'He <b>took on</b> extra shifts this month.',
      examplePt: 'Ele assumiu turnos extras esse mês.',
      pos: 'phrase',
    },
    {
      id: 'workplace_6', deckId: 'workplace',
      en: 'annual leave', pt: 'férias anuais',
      exampleHtml: "I've booked two weeks' <b>annual leave</b>.",
      examplePt: 'Reservei duas semanas de férias.',
      pos: 'phrase',
    },
    {
      id: 'workplace_7', deckId: 'workplace',
      en: 'KiwiSaver', pt: 'KiwiSaver (fundo de previdência da NZ)',
      exampleHtml: 'We both contribute to <b>KiwiSaver</b>.',
      examplePt: 'Nós dois contribuímos para o KiwiSaver.',
      pos: 'noun',
    },
    {
      id: 'workplace_8', deckId: 'workplace',
      en: 'notice period', pt: 'período de aviso prévio',
      exampleHtml: 'My <b>notice period</b> is four weeks.',
      examplePt: 'Meu aviso prévio é de quatro semanas.',
      pos: 'phrase',
    },
    {
      id: 'workplace_9', deckId: 'workplace',
      en: 'probation', pt: 'período de experiência',
      exampleHtml: "She's still on <b>probation</b> at work.",
      examplePt: 'Ela ainda está no período de experiência.',
      pos: 'noun',
    },
    {
      id: 'workplace_10', deckId: 'workplace',
      en: 'timesheet', pt: 'planilha de horas',
      exampleHtml: 'Fill in your <b>timesheet</b> by Friday.',
      examplePt: 'Preencha sua planilha de horas até sexta.',
      pos: 'noun',
    },
    {
      id: 'workplace_11', deckId: 'workplace',
      en: 'payslip', pt: 'holerite',
      exampleHtml: 'Check your <b>payslip</b> for the overtime.',
      examplePt: 'Confira seu holerite para ver a hora extra.',
      pos: 'noun',
    },
    {
      id: 'workplace_12', deckId: 'workplace',
      en: 'PAYE', pt: 'imposto retido na fonte (NZ)',
      exampleHtml: '<b>PAYE</b> is deducted from every payslip.',
      examplePt: 'O PAYE é descontado de cada holerite.',
      pos: 'noun',
    },
    {
      id: 'workplace_13', deckId: 'workplace',
      en: 'overtime', pt: 'hora extra',
      exampleHtml: 'He worked <b>overtime</b> again last night.',
      examplePt: 'Ele fez hora extra de novo ontem à noite.',
      pos: 'noun',
    },
    {
      id: 'workplace_14', deckId: 'workplace',
      en: 'shift', pt: 'turno',
      exampleHtml: "I've got a night <b>shift</b> tomorrow.",
      examplePt: 'Tenho um turno noturno amanhã.',
      pos: 'noun',
    },
    {
      id: 'workplace_15', deckId: 'workplace',
      en: 'handover', pt: 'passagem de serviço',
      exampleHtml: 'The <b>handover</b> took only ten minutes.',
      examplePt: 'A passagem de serviço durou só dez minutos.',
      pos: 'noun',
    },
    {
      id: 'workplace_16', deckId: 'workplace',
      en: 'performance review', pt: 'avaliação de desempenho',
      exampleHtml: 'My <b>performance review</b> is next Monday.',
      examplePt: 'Minha avaliação de desempenho é segunda que vem.',
      pos: 'phrase',
    },
    {
      id: 'workplace_17', deckId: 'workplace',
      en: 'contract', pt: 'contrato',
      exampleHtml: 'She finally signed her new <b>contract</b>.',
      examplePt: 'Ela finalmente assinou o novo contrato.',
      pos: 'noun',
    },
    {
      id: 'workplace_18', deckId: 'workplace',
      en: 'reference', pt: 'referência profissional',
      exampleHtml: 'Could you be a <b>reference</b> for me?',
      examplePt: 'Você poderia ser minha referência?',
      pos: 'noun',
    },
    {
      id: 'workplace_19', deckId: 'workplace',
      en: 'resign', pt: 'pedir demissão',
      exampleHtml: 'He plans to <b>resign</b> next month.',
      examplePt: 'Ele planeja pedir demissão no mês que vem.',
      pos: 'verb',
    },
    {
      id: 'workplace_20', deckId: 'workplace',
      en: 'apply for', pt: 'se candidatar a',
      exampleHtml: 'I <b>applied for</b> a supervisor role.',
      examplePt: 'Eu me candidatei a uma vaga de supervisor.',
      pos: 'phrase',
    },
    {
      id: 'workplace_21', deckId: 'workplace',
      en: 'shortlist', pt: 'selecionar (para a lista final)',
      exampleHtml: 'They <b>shortlisted</b> three candidates for the job.',
      examplePt: 'Eles selecionaram três candidatos para a vaga.',
      pos: 'verb',
    },
    {
      id: 'workplace_22', deckId: 'workplace',
      en: 'induction', pt: 'integração / treinamento inicial',
      exampleHtml: 'The <b>induction</b> covers health and safety.',
      examplePt: 'A integração cobre saúde e segurança.',
      pos: 'noun',
    },
    {
      id: 'workplace_23', deckId: 'workplace',
      en: 'health and safety', pt: 'saúde e segurança (do trabalho)',
      exampleHtml: '<b>Health and safety</b> comes first here.',
      examplePt: 'Saúde e segurança vêm primeiro aqui.',
      pos: 'phrase',
    },
    {
      id: 'workplace_24', deckId: 'workplace',
      en: 'casual work', pt: 'trabalho eventual',
      exampleHtml: "She's doing <b>casual work</b> at the café.",
      examplePt: 'Ela está fazendo trabalho casual no café.',
      pos: 'phrase',
    },
    {
      id: 'workplace_25', deckId: 'workplace',
      en: 'fixed-term', pt: 'por tempo determinado',
      exampleHtml: "It's a <b>fixed-term</b> contract for a year.",
      examplePt: 'É um contrato por tempo determinado de um ano.',
      pos: 'adj',
    },
  ],
}

const idioms: Deck = {
  id: 'idioms', name: 'Idioms & Kiwi collocations', emoji: '🎣',
  desc: 'The slang that makes you sound local', level: 4,
  cards: [
    {
      id: 'idioms_0', deckId: 'idioms',
      en: 'heaps of', pt: 'muito(s) / uma porção de',
      exampleHtml: "There's <b>heaps of</b> parking today.",
      examplePt: 'Tem muita vaga de estacionamento hoje.',
      pos: 'phrase',
    },
    {
      id: 'idioms_1', deckId: 'idioms',
      en: 'keen as', pt: 'super animado / muito a fim',
      exampleHtml: "I'm <b>keen as</b> for the weekend.",
      examplePt: 'Estou super animado para o fim de semana.',
      pos: 'phrase',
    },
    {
      id: 'idioms_2', deckId: 'idioms',
      en: 'chock-a-block', pt: 'cheio até não poder mais',
      exampleHtml: 'The car park was <b>chock-a-block</b>.',
      examplePt: 'O estacionamento estava cheio até não poder mais.',
      pos: 'adj',
    },
    {
      id: 'idioms_3', deckId: 'idioms',
      en: 'give it a go', pt: 'tentar / dar uma chance',
      exampleHtml: '<b>Give it a go</b>, mate.',
      examplePt: 'Só tenta, mano.',
      pos: 'phrase',
    },
    {
      id: 'idioms_4', deckId: 'idioms',
      en: 'no dramas', pt: 'sem problema / de boa',
      exampleHtml: "<b>No dramas</b>, I'll sort it out.",
      examplePt: 'Sem problema, eu resolvo isso.',
      pos: 'phrase',
    },
    {
      id: 'idioms_5', deckId: 'idioms',
      en: 'flat out', pt: 'numa correria / a toda',
      exampleHtml: "We've been <b>flat out</b> at work.",
      examplePt: 'Estamos numa correria no trabalho.',
      pos: 'phrase',
    },
    {
      id: 'idioms_6', deckId: 'idioms',
      en: 'hard yakka', pt: 'trabalho pesado / batalha',
      exampleHtml: 'Picking fruit is <b>hard yakka</b>.',
      examplePt: 'Colher frutas é um trabalho pesado.',
      pos: 'phrase',
    },
    {
      id: 'idioms_7', deckId: 'idioms',
      en: "she'll be right", pt: 'vai ficar tudo bem',
      exampleHtml: "Don't worry, <b>she'll be right</b>.",
      examplePt: 'Não se preocupa, vai ficar tudo bem.',
      pos: 'phrase',
    },
    {
      id: 'idioms_8', deckId: 'idioms',
      en: 'a piece of cake', pt: 'moleza / mamão com açúcar',
      exampleHtml: 'The test was <b>a piece of cake</b>.',
      examplePt: 'A prova foi moleza.',
      pos: 'phrase',
    },
    {
      id: 'idioms_9', deckId: 'idioms',
      en: 'out of the blue', pt: 'do nada / de repente',
      exampleHtml: 'He called me <b>out of the blue</b>.',
      examplePt: 'Ele me ligou do nada.',
      pos: 'phrase',
    },
    {
      id: 'idioms_10', deckId: 'idioms',
      en: 'over the moon', pt: 'nas nuvens / super feliz',
      exampleHtml: 'She was <b>over the moon</b> about it.',
      examplePt: 'Ela ficou nas nuvens com isso.',
      pos: 'phrase',
    },
    {
      id: 'idioms_11', deckId: 'idioms',
      en: 'under the weather', pt: 'meio doente / indisposto',
      exampleHtml: "I've been feeling <b>under the weather</b>.",
      examplePt: 'Estou meio indisposto esses dias.',
      pos: 'phrase',
    },
    {
      id: 'idioms_12', deckId: 'idioms',
      en: 'on the ball', pt: 'atento / afiado',
      exampleHtml: 'The new receptionist is <b>on the ball</b>.',
      examplePt: 'A nova recepcionista é bem atenta.',
      pos: 'phrase',
    },
    {
      id: 'idioms_13', deckId: 'idioms',
      en: 'touch base', pt: 'entrar em contato',
      exampleHtml: "Let's <b>touch base</b> next week.",
      examplePt: 'Vamos nos falar semana que vem.',
      pos: 'phrase',
    },
    {
      id: 'idioms_14', deckId: 'idioms',
      en: 'get the hang of', pt: 'pegar o jeito de',
      exampleHtml: "I'm finally <b>getting the hang of</b> it.",
      examplePt: 'Eu finalmente estou pegando o jeito.',
      pos: 'phrase',
    },
    {
      id: 'idioms_15', deckId: 'idioms',
      en: 'in the loop', pt: 'por dentro / informado',
      exampleHtml: 'Please keep me <b>in the loop</b>.',
      examplePt: 'Por favor, me mantenha informado.',
      pos: 'phrase',
    },
    {
      id: 'idioms_16', deckId: 'idioms',
      en: 'call it a day', pt: 'parar por aqui',
      exampleHtml: "Let's <b>call it a day</b>, team.",
      examplePt: 'Vamos parar por aqui, equipe.',
      pos: 'phrase',
    },
    {
      id: 'idioms_17', deckId: 'idioms',
      en: 'cut corners', pt: 'economizar de forma prejudicial',
      exampleHtml: "Don't <b>cut corners</b> on safety.",
      examplePt: 'Não corte custos na segurança.',
      pos: 'phrase',
    },
    {
      id: 'idioms_18', deckId: 'idioms',
      en: 'bite the bullet', pt: 'encarar o problema / criar coragem',
      exampleHtml: "I'll <b>bite the bullet</b> and call him.",
      examplePt: 'Vou encarar e ligar para ele.',
      pos: 'phrase',
    },
    {
      id: 'idioms_19', deckId: 'idioms',
      en: 'break the ice', pt: 'quebrar o gelo',
      exampleHtml: 'She told a joke to <b>break the ice</b>.',
      examplePt: 'Ela contou uma piada para quebrar o gelo.',
      pos: 'phrase',
    },
    {
      id: 'idioms_20', deckId: 'idioms',
      en: 'hit the road', pt: 'cair na estrada / partir',
      exampleHtml: 'We should <b>hit the road</b> soon.',
      examplePt: 'A gente devia cair na estrada em breve.',
      pos: 'phrase',
    },
    {
      id: 'idioms_21', deckId: 'idioms',
      en: 'spot on', pt: 'certinho / na mosca',
      exampleHtml: 'Your guess was <b>spot on</b>.',
      examplePt: 'Seu palpite foi certinho.',
      pos: 'phrase',
    },
  ],
}

const tenses: Deck = {
  id: 'tenses', name: 'Trickier tenses', emoji: '⏳',
  desc: 'The grammar that separates B1 from B2', level: 4,
  cards: [
    {
      id: 'tenses_0', deckId: 'tenses',
      en: 'present perfect + since', pt: 'presente perfeito + since (marca o início)',
      exampleHtml: 'I <b>have lived</b> here since March.',
      examplePt: 'Eu moro aqui desde março.',
      pos: 'grammar',
    },
    {
      id: 'tenses_1', deckId: 'tenses',
      en: 'present perfect + for', pt: 'presente perfeito + for (marca a duração)',
      exampleHtml: 'She <b>has worked</b> here for two years.',
      examplePt: 'Ela trabalha aqui há dois anos.',
      pos: 'grammar',
    },
    {
      id: 'tenses_2', deckId: 'tenses',
      en: 'present perfect continuous', pt: 'presente perfeito contínuo (ação em curso)',
      exampleHtml: 'We <b>have been waiting</b> for an hour.',
      examplePt: 'Estamos esperando há uma hora.',
      pos: 'grammar',
    },
    {
      id: 'tenses_3', deckId: 'tenses',
      en: 'past perfect', pt: 'passado perfeito (antes de outro passado)',
      exampleHtml: 'I <b>had finished</b> dinner before she called.',
      examplePt: 'Eu já tinha jantado quando ela ligou.',
      pos: 'grammar',
    },
    {
      id: 'tenses_4', deckId: 'tenses',
      en: 'first conditional — warning', pt: 'primeiro condicional (situação real e provável)',
      exampleHtml: "If you miss the bus, <b>you'll be late</b>.",
      examplePt: 'Se você perder o ônibus, vai se atrasar.',
      pos: 'grammar',
    },
    {
      id: 'tenses_5', deckId: 'tenses',
      en: 'first conditional — prediction', pt: 'primeiro condicional (if + presente, will)',
      exampleHtml: 'If it rains, we <b>will stay</b> home.',
      examplePt: 'Se chover, vamos ficar em casa.',
      pos: 'grammar',
    },
    {
      id: 'tenses_6', deckId: 'tenses',
      en: 'second conditional — hypothetical', pt: 'segundo condicional (hipótese improvável)',
      exampleHtml: 'If I had more money, <b>I would travel</b>.',
      examplePt: 'Se eu tivesse mais dinheiro, eu viajaria.',
      pos: 'grammar',
    },
    {
      id: 'tenses_7', deckId: 'tenses',
      en: 'second conditional — wish', pt: 'segundo condicional (hipótese no presente)',
      exampleHtml: 'If she won the lotto, <b>she would quit</b>.',
      examplePt: 'Se ela ganhasse na loteria, ela pediria demissão.',
      pos: 'grammar',
    },
    {
      id: 'tenses_8', deckId: 'tenses',
      en: 'third conditional — regret', pt: 'terceiro condicional (passado que não muda)',
      exampleHtml: 'If I had known, I <b>would have come</b>.',
      examplePt: 'Se eu tivesse sabido, eu teria vindo.',
      pos: 'grammar',
    },
    {
      id: 'tenses_9', deckId: 'tenses',
      en: 'third conditional — result', pt: 'terceiro condicional (resultado hipotético no passado)',
      exampleHtml: "We <b>wouldn't have missed</b> it if we'd left earlier.",
      examplePt: 'Não teríamos perdido se tivéssemos saído mais cedo.',
      pos: 'grammar',
    },
    {
      id: 'tenses_10', deckId: 'tenses',
      en: 'used to (affirmative)', pt: 'used to (hábito ou estado no passado que acabou)',
      exampleHtml: 'I <b>used to smoke</b>, but I quit.',
      examplePt: 'Eu costumava fumar, mas parei.',
      pos: 'grammar',
    },
    {
      id: 'tenses_11', deckId: 'tenses',
      en: 'used to (negative)', pt: 'used to na negativa (não costumava)',
      exampleHtml: "She <b>didn't use to</b> like coffee.",
      examplePt: 'Ela não costumava gostar de café.',
      pos: 'grammar',
    },
    {
      id: 'tenses_12', deckId: 'tenses',
      en: 'would (past habits)', pt: 'would para hábitos repetidos no passado',
      exampleHtml: 'We <b>would walk</b> to school every day.',
      examplePt: 'A gente ia a pé para a escola todo dia.',
      pos: 'grammar',
    },
    {
      id: 'tenses_13', deckId: 'tenses',
      en: 'going to (plan)', pt: 'going to (plano já decidido)',
      exampleHtml: "I'm <b>going to start</b> a new job.",
      examplePt: 'Eu vou começar um emprego novo.',
      pos: 'grammar',
    },
    {
      id: 'tenses_14', deckId: 'tenses',
      en: 'will (spontaneous decision)', pt: 'will (decisão tomada na hora)',
      exampleHtml: "I'll <b>call</b> the plumber right now.",
      examplePt: 'Eu vou ligar para o encanador agora mesmo.',
      pos: 'grammar',
    },
    {
      id: 'tenses_15', deckId: 'tenses',
      en: 'will (prediction)', pt: 'will (previsão, opinião sem prova concreta)',
      exampleHtml: 'It <b>will probably rain</b> tomorrow.',
      examplePt: 'Provavelmente vai chover amanhã.',
      pos: 'grammar',
    },
    {
      id: 'tenses_16', deckId: 'tenses',
      en: 'be about to', pt: 'be about to (prestes a)',
      exampleHtml: 'The bus <b>is about to leave</b>.',
      examplePt: 'O ônibus está prestes a partir.',
      pos: 'grammar',
    },
    {
      id: 'tenses_17', deckId: 'tenses',
      en: 'by the time', pt: 'by the time (até que, quando já)',
      exampleHtml: 'By the time we arrived, the shop <b>had closed</b>.',
      examplePt: 'Quando chegamos, a loja já tinha fechado.',
      pos: 'grammar',
    },
    {
      id: 'tenses_18', deckId: 'tenses',
      en: 'had better', pt: 'had better (é melhor, senão…)',
      exampleHtml: "<b>You'd better hurry</b> or you'll miss it.",
      examplePt: 'É melhor você se apressar, ou vai perder.',
      pos: 'grammar',
    },
    {
      id: 'tenses_19', deckId: 'tenses',
      en: 'might have', pt: 'might have (talvez tenha, especulação sobre o passado)',
      exampleHtml: 'She <b>might have missed</b> the bus.',
      examplePt: 'Talvez ela tenha perdido o ônibus.',
      pos: 'grammar',
    },
    {
      id: 'tenses_20', deckId: 'tenses',
      en: 'should have', pt: 'should have (deveria ter, mas não fez)',
      exampleHtml: 'You <b>should have called</b> me first.',
      examplePt: 'Você deveria ter me ligado antes.',
      pos: 'grammar',
    },
    {
      id: 'tenses_21', deckId: 'tenses',
      en: "shouldn't have", pt: "shouldn't have (crítica a uma ação passada)",
      exampleHtml: 'I <b>shouldn\'t have eaten</b> that pie.',
      examplePt: 'Eu não deveria ter comido aquela torta.',
      pos: 'grammar',
    },
  ],
}

export const B2_DECKS: Deck[] = [phrasal, connectors, opinions, workplace, idioms, tenses]
