/**
 * Pronúncia escrita "à brasileira" — ver PHONETICS-CONVENTION.md (mesma pasta).
 *
 * Chave = `Card.id`. Uma chave errada não dá erro: apenas não aparece pronúncia.
 * A junção com os baralhos acontece em `src/content/index.ts`.
 *
 * Cobertura desta tabela: níveis 1 e 2 (todos os baralhos gerados) + `irregular`.
 * Níveis 3 e 4 continuam noutra passagem, seguindo a mesma convenção.
 *
 * Lembretes rápidos da convenção:
 *   é/ê  →  bad = `béd`, bed = `bêd`  (rotação das vogais curtas da NZ)
 *   r    →  só antes de vogal; nunca no fim de sílaba (NZ é não-rótico)
 *   th   →  `f` (think = `fínk`) e `d` (the = `da`)
 *   schwa→  `a` átono (water = `uóta`)
 */
export const PHONETICS: Record<string, string> = {
  // ── survival · First words & courtesy (nível 1) ──────────────────────────
  survival_0: 'halôu',
  survival_1: 'hái',
  survival_2: 'gúd móning',
  survival_3: 'gúd aaftanún',
  survival_4: 'gúd íivning',
  survival_5: 'gudbái',
  survival_6: 'plíiz',
  survival_7: 'fénk iú',
  survival_8: 'ió uêlcam',
  survival_9: 'sóri',
  survival_10: 'ikskiúz mi',
  survival_11: 'iês',
  survival_12: 'nôu',
  survival_13: 'mêibi',
  survival_14: 'mái nêim iz…',
  survival_15: 'náis ta míitchu',
  survival_16: 'háu a iú',
  survival_17: 'áim gúd, fénks',
  survival_18: 'ái dôunt andasténd',
  survival_19: 'ken iu ripíit, plíiz',
  survival_20: 'ken iu spíik slôuli',
  survival_21: 'áim fram brazíl',

  // ── numbers · Numbers, time & days (nível 1) ─────────────────────────────
  numbers_0: 'uán',
  numbers_1: 'tú',
  numbers_2: 'fríi',
  numbers_3: 'fó',
  numbers_4: 'fáiv',
  numbers_5: 'tên',
  numbers_6: 'tuênti',
  numbers_7: 'hándrad',
  numbers_8: 'fêst',
  numbers_9: 'tadêi',
  numbers_10: 'tamórou',
  numbers_11: 'iêstadei',
  numbers_12: 'náu',
  numbers_13: 'uót táim iz it',
  numbers_14: 'íts háaf páast tú',
  numbers_15: 'móning',
  numbers_16: 'aaftanún',
  numbers_17: 'náit',
  numbers_18: 'mándei',
  numbers_19: 'fráidei',
  numbers_20: 'uíikend',
  numbers_21: 'uíik',

  // ── verbs · Everyday verbs (nível 1) ─────────────────────────────────────
  verbs_0: 'ta bíi',
  verbs_1: 'ta hév',
  verbs_2: 'ta uónt',
  verbs_3: 'ta níid',
  verbs_4: 'ta gôu',
  verbs_5: 'ta cám',
  verbs_6: 'ta íit',
  verbs_7: 'ta drínk',
  verbs_8: 'ta bái',
  verbs_9: 'ta pêi',
  verbs_10: 'ta uêk',
  verbs_11: 'ta lív',
  verbs_12: 'ta spíik',
  verbs_13: 'ta nôu',
  verbs_14: 'ta láik',
  verbs_15: 'ta hêlp',
  verbs_16: 'ta ôupan',
  verbs_17: 'ta clôuz',
  verbs_18: 'ta uêit',
  verbs_19: 'ta fáind',
  verbs_20: 'ta lúk fó',
  verbs_21: 'ta andasténd',

  // ── people · People & family (nível 1) ───────────────────────────────────
  people_0: 'házband',
  people_1: 'uáif',
  people_2: 'tcháild',
  people_3: 'tchíldran',
  people_4: 'máda',
  people_5: 'fáada',
  people_6: 'frênd',
  people_7: 'nêiba',
  people_8: 'mén',
  people_9: 'úman',
  people_10: 'bói',
  people_11: 'guêl',
  people_12: 'êvriuan',
  people_13: 'taguêda',
  people_14: 'híi / chíi',
  people_15: 'uíi',

  // ── food · Café & restaurant (nível 2) ───────────────────────────────────
  food_0: 'uóta',
  food_1: 'cófi',
  food_2: 'flét uáit',
  food_3: 'tíi',
  food_4: 'brêd',
  food_5: 'brêkfast',
  food_6: 'lántch',
  food_7: 'dína',
  food_8: 'mêniu',
  food_9: 'áid láik…',
  food_10: 'ken ái hév…',
  food_11: 'da bíl, plíiz',
  food_12: 'têikauei',
  food_13: 'dilíchas',
  food_14: 'áim alêdjik tu…',
  food_15: 'nôu chúga, fénks',
  food_16: 'tchíaz',

  // ── shopping · Shopping & supermarket (nível 2) ──────────────────────────
  shopping_0: 'háu mátch iz it',
  shopping_1: 'tú ikspênsiv',
  shopping_2: 'tchíip',
  shopping_3: 'ón spêchal',
  shopping_4: 'du iu hév…',
  shopping_5: 'sáiz',
  shopping_6: 'rissíit',
  shopping_7: 'tróli',
  shopping_8: 'tchêkaut',
  shopping_9: 'êftpos',
  shopping_10: 'kéch',
  shopping_11: 'cáad',
  shopping_12: 'bég',
  shopping_13: 'da uéahaus',
  shopping_14: 'káuntdaun / niú uêld',
  shopping_15: 'déari',

  // ── emergency · Emergencies & help (nível 1) ─────────────────────────────
  emergency_0: 'hêlp',
  emergency_1: 'kól uán uán uán',
  emergency_2: 'imêdjansi',
  emergency_3: 'émbiulans',
  emergency_4: 'palíis',
  emergency_5: 'fáia',
  emergency_6: 'ái níid hêlp',
  emergency_7: 'áim lóst',
  emergency_8: 'a iu oukêi',
  emergency_9: 'kéaful',
  emergency_10: 'stóp',
  emergency_11: 'dêindja',
  emergency_12: 'ái dôunt fíil sêif',
  emergency_13: 'uéa iz di êksit',

  // ── feelings · Feelings & states (nível 1) ───────────────────────────────
  feelings_0: 'hépi',
  feelings_1: 'séd',
  feelings_2: 'táiad',
  feelings_3: 'hángri',
  feelings_4: 'fêsti',
  feelings_5: 'côuld',
  feelings_6: 'hót',
  feelings_7: 'skéad',
  feelings_8: 'éngri',
  feelings_9: 'uárid',
  feelings_10: 'iksáitad',
  feelings_11: 'nêvas',
  feelings_12: 'bód',
  feelings_13: 'fáin',
  feelings_14: 'hôumsik',
  feelings_15: 'práud',
  feelings_16: 'cámftabal',
  feelings_17: 'canfiúzd',

  // ── house · Around the house (nível 2) ───────────────────────────────────
  house_0: 'dó',
  house_1: 'uíndou',
  house_2: 'têibal',
  house_3: 'tchéa',
  house_4: 'bêd',
  house_5: 'kítchan',
  house_6: 'báafrum',
  house_7: 'bêdrum',
  house_8: 'líving rum',
  house_9: 'frídj',
  house_10: 'ávan',
  house_11: 'sínk',
  house_12: 'cháua',
  house_13: 'táual',
  house_14: 'blénkat',
  house_15: 'láit',
  house_16: 'híita',
  house_17: 'clíin',

  // ── clothes · Clothes & weather (nível 2) ────────────────────────────────
  clothes_0: 'clôudz',
  clothes_1: 'chêt',
  clothes_2: 'djékat',
  clothes_3: 'côut',
  clothes_4: 'chúz',
  clothes_5: 'sóks',
  clothes_6: 'pénts',
  clothes_7: 'drês',
  clothes_8: 'hét',
  clothes_9: 'ambréla',
  clothes_10: 'rêincout',
  clothes_11: 'uêda',
  clothes_12: 'rêin',
  clothes_13: 'uínd',
  clothes_14: 'sáni',
  clothes_15: 'cláudi',
  clothes_16: 'uêt',
  clothes_17: 'uóm',

  // ── body · The body (nível 2) ────────────────────────────────────────────
  body_0: 'hêd',
  body_1: 'hénd',
  body_2: 'áam',
  body_3: 'lêg',
  body_4: 'fút',
  body_5: 'ái',
  body_6: 'ía',
  body_7: 'máuf',
  body_8: 'nôuz',
  body_9: 'túf',
  body_10: 'stámak',
  body_11: 'bék',
  body_12: 'frôut',
  body_13: 'héa',

  // ── questions · Question & linking words (nível 1) ───────────────────────
  questions_0: 'uót',
  questions_1: 'uéa',
  questions_2: 'uên',
  questions_3: 'hú',
  questions_4: 'uái',
  questions_5: 'háu',
  questions_6: 'uítch',
  questions_7: 'háu mátch',
  questions_8: 'háu mêni',
  questions_9: 'énd',
  questions_10: 'bát',
  questions_11: 'bicóz',
  questions_12: 'ólsou',
  questions_13: 'ó',
  questions_14: 'íf',
  questions_15: 'sôu',

  // ── town · Around town (nível 2) ─────────────────────────────────────────
  town_0: 'stríit',
  town_1: 'rôud',
  town_2: 'cóna',
  town_3: 'chóp',
  town_4: 'bénk',
  town_5: 'pôust ófis',
  town_6: 'láibri',
  town_7: 'páak',
  town_8: 'skúl',
  town_9: 'pêtral stêichan',
  town_10: 'tóilat',
  town_11: 'kéfei',
  town_12: 'bíitch',
  town_13: 'síti sênta',
  town_14: 'hía',
  town_15: 'déa',

  // ── basics · Colours & describing (nível 1) ──────────────────────────────
  basics_0: 'cála',
  basics_1: 'rêd',
  basics_2: 'blú',
  basics_3: 'gríin',
  basics_4: 'iêlou',
  basics_5: 'blék',
  basics_6: 'uáit',
  basics_7: 'bíg',
  basics_8: 'smól',
  basics_9: 'niú',
  basics_10: 'ôuld',
  basics_11: 'gúd',
  basics_12: 'béd',
  basics_13: 'biútiful',
  basics_14: 'íizi',
  basics_15: 'dífikalt',

  // ── verbs2 · More everyday verbs (nível 2) ───────────────────────────────
  verbs2_0: 'ta guív',
  verbs2_1: 'ta têik',
  verbs2_2: 'ta mêik',
  verbs2_3: 'ta dú',
  verbs2_4: 'ta sêi',
  verbs2_5: 'ta têl',
  verbs2_6: 'ta áask',
  verbs2_7: 'ta kól',
  verbs2_8: 'ta bríng',
  verbs2_9: 'ta pút',
  verbs2_10: 'ta guêt',
  verbs2_11: 'ta lên',
  verbs2_12: 'ta rimêmba',
  verbs2_13: 'ta faguêt',
  verbs2_14: 'ta trái',
  verbs2_15: 'ta chôu',
  verbs2_16: 'ta stáat',
  verbs2_17: 'ta fínich',

  // ── power · Power phrases (nível 2) ──────────────────────────────────────
  power_0: 'háu du iu sêi… in ínglich',
  power_1: 'uóts dís kóld',
  power_2: 'ken iu ráit it dáun',
  power_3: 'áim nót chó',
  power_4: 'ái fínk sôu',
  power_5: 'djást a môumant',
  power_6: 'áil bi ráit bék',
  power_7: 'nêva máind',
  power_8: 'av kós',
  power_9: 'déts fáin',
  power_10: 'lêt mi tchék',
  power_11: 'ken ái áask iu sámfing',
  power_12: 'ái agríi',
  power_13: 'gúd aidía',
  power_14: 'dôunt uári',
  power_15: 'uót chud ái dú',
  power_16: 'áil hév dís uán',
  power_17: 'slôu dáun, plíiz',

  // ── grammar · Essential grammar (nível 2) ────────────────────────────────
  grammar_0: 'ái ém / iu áa / hi íz',
  grammar_1: 'áim nót / ízant / áant',
  grammar_2: 'a iú…? / iz hí…?',
  grammar_3: 'a / an',
  grammar_4: 'da / di',
  grammar_5: 'plúralz: éd -s',
  grammar_6: 'dís / dét / díiz / dôuz',
  grammar_7: 'mái / ió / híz / hê',
  grammar_8: 'prêzant: ái uêk / chi uêks',
  grammar_9: 'ái dôunt / chi dázant',
  grammar_10: 'du iú…? / dáz hi…?',
  grammar_11: 'prêzant cantíniuas: áim uêking',
  grammar_12: 'páast: uêkt / uént',
  grammar_13: 'irêguiula páast: uóz / héd / uént',
  grammar_14: 'fiútcha: uíl',
  grammar_15: 'fiútcha: gôuing tu',
  grammar_16: 'kén / cáant',
  grammar_17: 'déa íz / déa áa',
  grammar_18: 'hév tu / níid tu',
  grammar_19: 'campérativz: bíga / mó…',
  grammar_20: 'úd láik',
  grammar_21: 'óbdjekt uêdz: mi / iu / him / hê',

  // ── irregular · Irregular verbs (nível 2, autorado) ──────────────────────
  irregular_0: 'gôu → uént',
  irregular_1: 'hév → héd',
  irregular_2: 'bíi → uóz / uê',
  irregular_3: 'dú → díd',
  irregular_4: 'sêi → sêd',
  irregular_5: 'mêik → mêid',
  irregular_6: 'têik → túk',
  irregular_7: 'cám → kêim',
  irregular_8: 'síi → só',
  irregular_9: 'guêt → gót',
  irregular_10: 'guív → guêiv',
  irregular_11: 'nôu → niú',
  irregular_12: 'fínk → fót',
  irregular_13: 'fáind → fáund',
}
