/**
 * Pronúncia do polonês escrita "à brasileira" — ver a seção 2 de
 * PHONETICS-CONVENTION.md (mesma pasta). Chave = `Card.id`. Uma chave
 * errada não dá erro: apenas não aparece pronúncia. A junção com os
 * baralhos acontece em `src/content/pl/index.ts`.
 */
export const PHONETICS_PL: Record<string, string> = {
  // ── pl_hello · Primeiras palavras ────────────────────────────────────────
  pl_hello_0: 'tchéść',
  pl_hello_1: 'dźéń dóbry',
  pl_hello_2: 'viétchur',
  pl_hello_3: 'dóbranots',
  pl_hello_4: 'dó vidzéńa',
  pl_hello_5: 'pa',
  pl_hello_6: 'próxen',
  pl_hello_7: 'dźenkuién',
  pl_hello_8: 'pjépraxam',
  pl_hello_9: 'tak',
  pl_hello_10: 'ńé',
  pl_hello_11: 'iak śen max',
  pl_hello_12: 'miuó mi',
  pl_hello_13: 'nazyvam śen',
  // ── pl_numbers · Números e tempo ─────────────────────────────────────────
  pl_numbers_0: 'zéró',
  pl_numbers_1: 'iédén',
  pl_numbers_2: 'dva',
  pl_numbers_3: 'tchy',
  pl_numbers_4: 'tchtéry',
  pl_numbers_5: 'pjenć',
  pl_numbers_6: 'xéść',
  pl_numbers_7: 'śédém',
  pl_numbers_8: 'óśém',
  pl_numbers_9: 'dźévjeńć',
  pl_numbers_10: 'dźéśeńć',
  pl_numbers_11: 'dźiśai',
  pl_numbers_12: 'iutró',
  pl_numbers_13: 'vtchórai',
  pl_numbers_14: 'téraz',
  pl_numbers_15: 'gódzina',
  // ── pl_verbs · Verbos do dia a dia ───────────────────────────────────────
  pl_verbs_0: 'być',
  pl_verbs_1: 'iéstém',
  pl_verbs_2: 'iéstéś',
  pl_verbs_3: 'miéć',
  pl_verbs_4: 'mam',
  pl_verbs_5: 'max',
  pl_verbs_6: 'rrćéć',
  pl_verbs_7: 'rrtsén',
  pl_verbs_8: 'iść',
  pl_verbs_9: 'idén',
  pl_verbs_10: 'róbić',
  pl_verbs_11: 'róbjen',
  pl_verbs_12: 'muvić',
  pl_verbs_13: 'muvjen',
  pl_verbs_14: 'rózumiéć',
  pl_verbs_15: 'viém',
  // ── pl_people · Família e pessoas ────────────────────────────────────────
  pl_people_0: 'ródzina',
  pl_people_1: 'mama',
  pl_people_2: 'tata',
  pl_people_3: 'brat',
  pl_people_4: 'śóstra',
  pl_people_5: 'syn',
  pl_people_6: 'tsurka',
  pl_people_7: 'monj',
  pl_people_8: 'jóna',
  pl_people_9: 'dźétsko',
  pl_people_10: 'pjyiaćél',
  pl_people_11: 'dźévtchyna',
  pl_people_12: 'rruópak',
  pl_people_13: 'tchuóviék',
  // ── pl_emergency · Emergências e ajuda ───────────────────────────────────
  pl_emergency_0: 'pómótsy',
  pl_emergency_1: 'pómóts',
  pl_emergency_2: 'pólitsia',
  pl_emergency_3: 'xpital',
  pl_emergency_4: 'lékaj',
  pl_emergency_5: 'karétka',
  pl_emergency_6: 'pójar',
  pl_emergency_7: 'ńébézpiétchéństvó',
  pl_emergency_8: 'zgubiuém śen',
  pl_emergency_9: 'pótjébujén pómótsy',
  pl_emergency_10: 'zadzvóń pó pómóts',
  pl_emergency_11: 'iéstém rróry',
}
