/**
 * Pronúncia do polonês escrita "à brasileira" — ver a seção 9 de
 * PHONETICS-CONVENTION.md (mesma pasta). Chave = `Card.id`. Uma chave
 * errada não dá erro: apenas não aparece pronúncia. A junção com os
 * baralhos acontece em `src/content/pl/index.ts`.
 */
export const PHONETICS_PL: Record<string, string> = {
  // ── pl_hello · Primeiras palavras ────────────────────────────────────────
  pl_hello_0: 'tchéść',
  pl_hello_1: 'dźéń dóbry',
  pl_hello_2: 'dóbry viétchur',
  pl_hello_3: 'dóbranóts',
  pl_hello_4: 'dó vidzéńa',
  pl_hello_5: 'pa',
  pl_hello_6: 'próxen',
  pl_hello_7: 'dźenkuién',
  pl_hello_8: 'pjépraxam',
  pl_hello_9: 'tak',
  pl_hello_10: 'ńé',
  pl_hello_11: 'iak śen max',
  pl_hello_12: 'miuó mi',
  pl_hello_13: 'nazyvam śen',
  // ── pl_numbers · Números e tempo ─────────────────────────────────────────
  pl_numbers_0: 'zéró',
  pl_numbers_1: 'iédén',
  pl_numbers_2: 'dva',
  pl_numbers_3: 'tchy',
  pl_numbers_4: 'tchtéry',
  pl_numbers_5: 'pjeńć',
  pl_numbers_6: 'xéść',
  pl_numbers_7: 'śédém',
  pl_numbers_8: 'óśém',
  pl_numbers_9: 'dźévjeńć',
  pl_numbers_10: 'dźéśeńć',
  pl_numbers_11: 'dźiśai',
  pl_numbers_12: 'iutró',
  pl_numbers_13: 'vtchórai',
  pl_numbers_14: 'téraz',
  pl_numbers_15: 'gódzina',
  // ── pl_verbs · Verbos do dia a dia ───────────────────────────────────────
  pl_verbs_0: 'być',
  pl_verbs_1: 'iéstém',
  pl_verbs_2: 'iéstéś',
  pl_verbs_3: 'miéć',
  pl_verbs_4: 'mam',
  pl_verbs_5: 'max',
  pl_verbs_6: 'rrćéć',
  pl_verbs_7: 'rrtsen',
  pl_verbs_8: 'iść',
  pl_verbs_9: 'iden',
  pl_verbs_10: 'róbić',
  pl_verbs_11: 'róbjen',
  pl_verbs_12: 'muvić',
  pl_verbs_13: 'muvjen',
  pl_verbs_14: 'rózumiéć',
  pl_verbs_15: 'viém',
  // ── pl_people · Família e pessoas ────────────────────────────────────────
  pl_people_0: 'ródzina',
  pl_people_1: 'mama',
  pl_people_2: 'tata',
  pl_people_3: 'brat',
  pl_people_4: 'śóstra',
  pl_people_5: 'syn',
  pl_people_6: 'tsurka',
  pl_people_7: 'monj',
  pl_people_8: 'jóna',
  pl_people_9: 'dźétskó',
  pl_people_10: 'pjyiaćél',
  pl_people_11: 'dźévtchyna',
  pl_people_12: 'rruópak',
  pl_people_13: 'tchuóviék',
  // ── pl_emergency · Emergências e ajuda ───────────────────────────────────
  pl_emergency_0: 'pómótsy',
  pl_emergency_1: 'pómóts',
  pl_emergency_2: 'pólitsia',
  pl_emergency_3: 'xpital',
  pl_emergency_4: 'lékaj',
  pl_emergency_5: 'karétka',
  pl_emergency_6: 'pójar',
  pl_emergency_7: 'ńébézpiétchéństvó',
  pl_emergency_8: 'zgubiuém śen',
  pl_emergency_9: 'pótchébuién pómótsy',
  pl_emergency_10: 'zadzvóń pó pómóts',
  pl_emergency_11: 'iéstém rróry',
  // ── pl_feelings · Sentimentos e estados ──────────────────────────────────
  pl_feelings_0: 'xtchéńślivy',
  pl_feelings_1: 'smutny',
  pl_feelings_2: 'zméntchóny',
  pl_feelings_3: 'guódny',
  pl_feelings_4: 'spragnióny',
  pl_feelings_5: 'zuy',
  pl_feelings_6: 'pjéstraxóny',
  pl_feelings_7: 'zaskótchóny',
  pl_feelings_8: 'rróry',
  pl_feelings_9: 'zdróvy',
  pl_feelings_10: 'zaiénty',
  pl_feelings_11: 'vólny',
  pl_feelings_12: 'dóbjé',
  pl_feelings_13: 'źlé',
  // ── pl_questions · Perguntas e conectivos ────────────────────────────────
  pl_questions_0: 'tsó',
  pl_questions_1: 'któ',
  pl_questions_2: 'gdźé',
  pl_questions_3: 'kiédy',
  pl_questions_4: 'dlatchégó',
  pl_questions_5: 'iak',
  pl_questions_6: 'ilé',
  pl_questions_7: 'ktury',
  pl_questions_8: 'i',
  pl_questions_9: 'alé',
  pl_questions_10: 'albó',
  pl_questions_11: 'bó',
  // ── pl_basics · Cores e descrições ───────────────────────────────────────
  pl_basics_0: 'tchérvóny',
  pl_basics_1: 'ńébiéski',
  pl_basics_2: 'źélóny',
  pl_basics_3: 'juuty',
  pl_basics_4: 'tcharny',
  pl_basics_5: 'biauy',
  pl_basics_6: 'dujy',
  pl_basics_7: 'mauy',
  pl_basics_8: 'nóvy',
  pl_basics_9: 'stary',
  pl_basics_10: 'dóbry',
  pl_basics_11: 'zuy',
  pl_basics_12: 'uadny',
  pl_basics_13: 'bjydki',
  // ── pl_food · Comida e restaurante ───────────────────────────────────────
  pl_food_0: 'rrléb',
  pl_food_1: 'vóda',
  pl_food_2: 'kava',
  pl_food_3: 'rrérbata',
  pl_food_4: 'mlékó',
  pl_food_5: 'iaikó',
  pl_food_6: 'sér',
  pl_food_7: 'mjensó',
  pl_food_8: 'ryba',
  pl_food_9: 'vajyva',
  pl_food_10: 'óvótsé',
  pl_food_11: 'tsukiér',
  pl_food_12: 'sul',
  pl_food_13: 'śńadańé',
  pl_food_14: 'óbiad',
  pl_food_15: 'kólatsia',
  // ── pl_shopping · Compras e mercado ──────────────────────────────────────
  pl_shopping_0: 'sklép',
  pl_shopping_1: 'supérmarkét',
  pl_shopping_2: 'piéńondzé',
  pl_shopping_3: 'tséna',
  pl_shopping_4: 'tańi',
  pl_shopping_5: 'drógi',
  pl_shopping_6: 'kupóvać',
  pl_shopping_7: 'kupuién',
  pl_shopping_8: 'spjédavać',
  pl_shopping_9: 'rarrunék',
  pl_shopping_10: 'gótuvka',
  pl_shopping_11: 'karta',
  pl_shopping_12: 'tórba',
  pl_shopping_13: 'paragón',
  // ── pl_house · Casa ───────────────────────────────────────────────────────
  pl_house_0: 'dóm',
  pl_house_1: 'miéxkańé',
  pl_house_2: 'pókui',
  pl_house_3: 'kurrńa',
  pl_house_4: 'uaźénka',
  pl_house_5: 'sypialńa',
  pl_house_6: 'salón',
  pl_house_7: 'djvi',
  pl_house_8: 'óknó',
  pl_house_9: 'stuu',
  pl_house_10: 'kjésuó',
  pl_house_11: 'uujkó',
  pl_house_12: 'klutch',
  pl_house_13: 'śviatuó',
  pl_house_14: 'tchysty',
  pl_house_15: 'brudny',
  // ── pl_clothes · Roupas e clima ──────────────────────────────────────────
  pl_clothes_0: 'ubrańé',
  pl_clothes_1: 'kóxula',
  pl_clothes_2: 'spódńé',
  pl_clothes_3: 'sukiénka',
  pl_clothes_4: 'buty',
  pl_clothes_5: 'kurtka',
  pl_clothes_6: 'tchapka',
  pl_clothes_7: 'pógóda',
  pl_clothes_8: 'suóńtsé',
  pl_clothes_9: 'déxtch',
  pl_clothes_10: 'śńég',
  pl_clothes_11: 'viatr',
  pl_clothes_12: 'zimnó',
  pl_clothes_13: 'ćépuó',
  pl_clothes_14: 'górontsó',
  pl_clothes_15: 'rrmura',
  // ── pl_body · Corpo ───────────────────────────────────────────────────────
  pl_body_0: 'guóva',
  pl_body_1: 'renka',
  pl_body_2: 'nóga',
  pl_body_3: 'ókó',
  pl_body_4: 'urró',
  pl_body_5: 'usta',
  pl_body_6: 'nós',
  pl_body_7: 'sértsé',
  pl_body_8: 'jóuondék',
  pl_body_9: 'plétsy',
  pl_body_10: 'paléts',
  pl_body_11: 'vuósy',
  pl_body_12: 'tvaj',
  pl_body_13: 'zomb',
  // ── pl_town · Cidade ──────────────────────────────────────────────────────
  pl_town_0: 'miastó',
  pl_town_1: 'ulitsa',
  pl_town_2: 'plats',
  pl_town_3: 'kóśćuu',
  pl_town_4: 'xkóua',
  pl_town_5: 'bank',
  pl_town_6: 'pótchta',
  pl_town_7: 'park',
  pl_town_8: 'móst',
  pl_town_9: 'jéka',
  pl_town_10: 'autóbus',
  pl_town_11: 'póćong',
  pl_town_12: 'lótńiskó',
  pl_town_13: 'dvójéts',
  // ── pl_verbs2 · Mais verbos do dia a dia ─────────────────────────────────
  pl_verbs2_0: 'vidźéć',
  pl_verbs2_1: 'vidzen',
  pl_verbs2_2: 'suyxéć',
  pl_verbs2_3: 'tchytać',
  pl_verbs2_4: 'tchytam',
  pl_verbs2_5: 'pisać',
  pl_verbs2_6: 'pixen',
  pl_verbs2_7: 'iéść',
  pl_verbs2_8: 'iém',
  pl_verbs2_9: 'pić',
  pl_verbs2_10: 'piién',
  pl_verbs2_11: 'spać',
  pl_verbs2_12: 'śpjen',
  pl_verbs2_13: 'pratsóvać',
  pl_verbs2_14: 'pratsuién',
  pl_verbs2_15: 'kórrać',
  // ── pl_power · Frases de uso frequente ───────────────────────────────────
  pl_power_0: 'próxen ó rarrunék',
  pl_power_1: 'ilé tó kóxtuié?',
  pl_power_2: 'ńé rózumiém',
  pl_power_3: 'tchy muvix pó angiélsku?',
  pl_power_4: 'gdźé iést tóaléta?',
  pl_power_5: 'iéstém guódny',
  pl_power_6: 'mógen próśić ó pómóts?',
  pl_power_7: 'tsó tó znatchy?',
  pl_power_8: 'vxystkó v pójondku',
  pl_power_9: 'ńé ma spravy',
  pl_power_10: 'dó zóbatchéńa',
  pl_power_11: 'na zdróvié',
  pl_power_12: 'smatchnégó',
  pl_power_13: 'póvódzéńa',
  pl_power_14: 'iak tó śen muvi pó pólsku?',
  pl_power_15: 'muxen iść',
}
