/**
 * Pronúncia escrita "à brasileira" — ver PHONETICS-CONVENTION.md (mesma pasta).
 *
 * Chave = `Card.id`. Uma chave errada não dá erro: apenas não aparece pronúncia.
 * A junção com os baralhos acontece em `src/content/index.ts`.
 *
 * Cobertura desta tabela: o corpo inteiro — níveis 1 e 2 (baralhos gerados +
 * `irregular`) e níveis 3 e 4 (B1 gerado + os seis baralhos B2 autorados).
 *
 * O alvo é o inglês **americano** (decisão do dono, 2026-08-03).
 *
 * Lembretes rápidos da convenção:
 *   r    →  o r do fim de sílaba é escrito: water = `uóter`, car = `cár`
 *   êr   →  work = `uêrk`, first = `fêrst`, girl = `guêrl`  (vogal de NURSE)
 *   é    →  ask = `ésk`, half = `héf`, can't = `ként`  (o a curto americano)
 *   é/ê  →  bad = `béd`, bed = `bêd`
 *   th   →  `f` (think = `fínk`) e `d` (the = `da`)
 *   schwa→  `a` átono quando não há r (`abáut`), `er` quando há (`uóter`)
 */
export const PHONETICS: Record<string, string> = {
  // ── survival · First words & courtesy (nível 1) ──────────────────────────
  survival_0: 'halôu',
  survival_1: 'hái',
  survival_2: 'gúd mórning',
  survival_3: 'gúd efternún',
  survival_4: 'gúd íivning',
  survival_5: 'gudbái',
  survival_6: 'plíiz',
  survival_7: 'fénk iú',
  survival_8: 'iór uêlcam',
  survival_9: 'sóri',
  survival_10: 'ikskiúz mi',
  survival_11: 'iês',
  survival_12: 'nôu',
  survival_13: 'mêibi',
  survival_14: 'mái nêim iz…',
  survival_15: 'náis ta míitchu',
  survival_16: 'háu ar iú',
  survival_17: 'áim gúd, fénks',
  survival_18: 'ái dôunt andersténd',
  survival_19: 'ken iu ripíit, plíiz',
  survival_20: 'ken iu spíik slôuli',
  survival_21: 'áim fram brazíl',

  // ── numbers · Numbers, time & days (nível 1) ─────────────────────────────
  numbers_0: 'uán',
  numbers_1: 'tú',
  numbers_2: 'fríi',
  numbers_3: 'fór',
  numbers_4: 'fáiv',
  numbers_5: 'tên',
  numbers_6: 'tuênti',
  numbers_7: 'hándrad',
  numbers_8: 'fêrst',
  numbers_9: 'tadêi',
  numbers_10: 'tamórou',
  numbers_11: 'iêsterdei',
  numbers_12: 'náu',
  numbers_13: 'uót táim iz it',
  numbers_14: 'íts héf pést tú',
  numbers_15: 'mórning',
  numbers_16: 'efternún',
  numbers_17: 'náit',
  numbers_18: 'mándei',
  numbers_19: 'fráidei',
  numbers_20: 'uíikend',
  numbers_21: 'uíik',

  // ── verbs · Everyday verbs (nível 1) ─────────────────────────────────────
  verbs_0: 'ta bíi',
  verbs_1: 'ta hév',
  verbs_2: 'ta uónt',
  verbs_3: 'ta níid',
  verbs_4: 'ta gôu',
  verbs_5: 'ta cám',
  verbs_6: 'ta íit',
  verbs_7: 'ta drínk',
  verbs_8: 'ta bái',
  verbs_9: 'ta pêi',
  verbs_10: 'ta uêrk',
  verbs_11: 'ta lív',
  verbs_12: 'ta spíik',
  verbs_13: 'ta nôu',
  verbs_14: 'ta láik',
  verbs_15: 'ta hêlp',
  verbs_16: 'ta ôupan',
  verbs_17: 'ta clôuz',
  verbs_18: 'ta uêit',
  verbs_19: 'ta fáind',
  verbs_20: 'ta lúk fór',
  verbs_21: 'ta andersténd',

  // ── people · People & family (nível 1) ───────────────────────────────────
  people_0: 'házband',
  people_1: 'uáif',
  people_2: 'tcháild',
  people_3: 'tchíldran',
  people_4: 'máder',
  people_5: 'fáader',
  people_6: 'frênd',
  people_7: 'nêiber',
  people_8: 'mén',
  people_9: 'úman',
  people_10: 'bói',
  people_11: 'guêrl',
  people_12: 'êvriuan',
  people_13: 'taguêder',
  people_14: 'híi / chíi',
  people_15: 'uíi',

  // ── food · Café & restaurant (nível 2) ───────────────────────────────────
  food_0: 'uóter',
  food_1: 'cófi',
  food_2: 'flét uáit',
  food_3: 'tíi',
  food_4: 'brêd',
  food_5: 'brêkfast',
  food_6: 'lántch',
  food_7: 'díner',
  food_8: 'mêniu',
  food_9: 'áid láik…',
  food_10: 'ken ái hév…',
  food_11: 'da bíl, plíiz',
  food_12: 'têikauei',
  food_13: 'dilíchas',
  food_14: 'áim alêrdjik tu…',
  food_15: 'nôu chúger, fénks',
  food_16: 'tchírz',

  // ── shopping · Shopping & supermarket (nível 2) ──────────────────────────
  shopping_0: 'háu mátch iz it',
  shopping_1: 'tú ikspênsiv',
  shopping_2: 'tchíip',
  shopping_3: 'ón spêchal',
  shopping_4: 'du iu hév…',
  shopping_5: 'sáiz',
  shopping_6: 'rissíit',
  shopping_7: 'tróli',
  shopping_8: 'tchêkaut',
  shopping_9: 'êftpos',
  shopping_10: 'kéch',
  shopping_11: 'cárd',
  shopping_12: 'bég',
  shopping_13: 'da uérhaus',
  shopping_14: 'káuntdaun / nú uêrld',
  shopping_15: 'déri',

  // ── emergency · Emergencies & help (nível 1) ─────────────────────────────
  emergency_0: 'hêlp',
  emergency_1: 'kól uán uán uán',
  emergency_2: 'imêrdjensi',
  emergency_3: 'émbiulans',
  emergency_4: 'palíis',
  emergency_5: 'fáier',
  emergency_6: 'ái níid hêlp',
  emergency_7: 'áim lóst',
  emergency_8: 'ar iu oukêi',
  emergency_9: 'kérful',
  emergency_10: 'stóp',
  emergency_11: 'dêindjer',
  emergency_12: 'ái dôunt fíil sêif',
  emergency_13: 'uér iz di êksit',

  // ── feelings · Feelings & states (nível 1) ───────────────────────────────
  feelings_0: 'hépi',
  feelings_1: 'séd',
  feelings_2: 'táierd',
  feelings_3: 'hángri',
  feelings_4: 'fêrsti',
  feelings_5: 'côuld',
  feelings_6: 'hót',
  feelings_7: 'skérd',
  feelings_8: 'éngri',
  feelings_9: 'uêrid',
  feelings_10: 'iksáitad',
  feelings_11: 'nêrvas',
  feelings_12: 'bórd',
  feelings_13: 'fáin',
  feelings_14: 'hôumsik',
  feelings_15: 'práud',
  feelings_16: 'cámfterbal',
  feelings_17: 'canfiúzd',

  // ── house · Around the house (nível 2) ───────────────────────────────────
  house_0: 'dór',
  house_1: 'uíndou',
  house_2: 'têibal',
  house_3: 'tchér',
  house_4: 'bêd',
  house_5: 'kítchan',
  house_6: 'béfrum',
  house_7: 'bêdrum',
  house_8: 'líving rum',
  house_9: 'frídj',
  house_10: 'ávan',
  house_11: 'sínk',
  house_12: 'cháuer',
  house_13: 'táual',
  house_14: 'blénkat',
  house_15: 'láit',
  house_16: 'híiter',
  house_17: 'clíin',

  // ── clothes · Clothes & weather (nível 2) ────────────────────────────────
  clothes_0: 'clôudz',
  clothes_1: 'chêrt',
  clothes_2: 'djékat',
  clothes_3: 'côut',
  clothes_4: 'chúz',
  clothes_5: 'sóks',
  clothes_6: 'pénts',
  clothes_7: 'drês',
  clothes_8: 'hét',
  clothes_9: 'ambréla',
  clothes_10: 'rêincout',
  clothes_11: 'uêder',
  clothes_12: 'rêin',
  clothes_13: 'uínd',
  clothes_14: 'sáni',
  clothes_15: 'cláudi',
  clothes_16: 'uêt',
  clothes_17: 'uórm',

  // ── body · The body (nível 2) ────────────────────────────────────────────
  body_0: 'hêd',
  body_1: 'hénd',
  body_2: 'árm',
  body_3: 'lêg',
  body_4: 'fút',
  body_5: 'ái',
  body_6: 'ír',
  body_7: 'máuf',
  body_8: 'nôuz',
  body_9: 'túf',
  body_10: 'stámak',
  body_11: 'bék',
  body_12: 'frôut',
  body_13: 'hér',

  // ── questions · Question & linking words (nível 1) ───────────────────────
  questions_0: 'uót',
  questions_1: 'uér',
  questions_2: 'uên',
  questions_3: 'hú',
  questions_4: 'uái',
  questions_5: 'háu',
  questions_6: 'uítch',
  questions_7: 'háu mátch',
  questions_8: 'háu mêni',
  questions_9: 'énd',
  questions_10: 'bát',
  questions_11: 'bicóz',
  questions_12: 'ólsou',
  questions_13: 'ór',
  questions_14: 'íf',
  questions_15: 'sôu',

  // ── town · Around town (nível 2) ─────────────────────────────────────────
  town_0: 'stríit',
  town_1: 'rôud',
  town_2: 'córner',
  town_3: 'chóp',
  town_4: 'bénk',
  town_5: 'pôust ófis',
  town_6: 'láibreri',
  town_7: 'párk',
  town_8: 'skúl',
  town_9: 'pêtral stêichan',
  town_10: 'tóilat',
  town_11: 'keféi',
  town_12: 'bíitch',
  town_13: 'síti sênter',
  town_14: 'hír',
  town_15: 'dér',

  // ── basics · Colours & describing (nível 1) ──────────────────────────────
  basics_0: 'cáler',
  basics_1: 'rêd',
  basics_2: 'blú',
  basics_3: 'gríin',
  basics_4: 'iêlou',
  basics_5: 'blék',
  basics_6: 'uáit',
  basics_7: 'bíg',
  basics_8: 'smól',
  basics_9: 'nú',
  basics_10: 'ôuld',
  basics_11: 'gúd',
  basics_12: 'béd',
  basics_13: 'biútiful',
  basics_14: 'íizi',
  basics_15: 'dífikalt',

  // ── verbs2 · More everyday verbs (nível 2) ───────────────────────────────
  verbs2_0: 'ta guív',
  verbs2_1: 'ta têik',
  verbs2_2: 'ta mêik',
  verbs2_3: 'ta dú',
  verbs2_4: 'ta sêi',
  verbs2_5: 'ta têl',
  verbs2_6: 'ta ésk',
  verbs2_7: 'ta kól',
  verbs2_8: 'ta bríng',
  verbs2_9: 'ta pút',
  verbs2_10: 'ta guêt',
  verbs2_11: 'ta lêrn',
  verbs2_12: 'ta rimêmber',
  verbs2_13: 'ta ferguêt',
  verbs2_14: 'ta trái',
  verbs2_15: 'ta chôu',
  verbs2_16: 'ta stárt',
  verbs2_17: 'ta fínich',

  // ── power · Power phrases (nível 2) ──────────────────────────────────────
  power_0: 'háu du iu sêi… in ínglich',
  power_1: 'uóts dís kóld',
  power_2: 'ken iu ráit it dáun',
  power_3: 'áim nót chúr',
  power_4: 'ái fínk sôu',
  power_5: 'djást a môumant',
  power_6: 'áil bi ráit bék',
  power_7: 'nêver máind',
  power_8: 'av córs',
  power_9: 'déts fáin',
  power_10: 'lêt mi tchék',
  power_11: 'ken ái ésk iu sámfing',
  power_12: 'ái agríi',
  power_13: 'gúd aidía',
  power_14: 'dôunt uêri',
  power_15: 'uót chud ái dú',
  power_16: 'áil hév dís uán',
  power_17: 'slôu dáun, plíiz',

  // ── grammar · Essential grammar (nível 2) ────────────────────────────────
  grammar_0: 'ái ém / iu ár / hi íz',
  grammar_1: 'áim nót / ízant / árnt',
  grammar_2: 'ar iú…? / iz hí…?',
  grammar_3: 'a / an',
  grammar_4: 'da / di',
  grammar_5: 'plúralz: éd -s',
  grammar_6: 'dís / dét / díiz / dôuz',
  grammar_7: 'mái / iór / híz / hêr',
  grammar_8: 'prêzant: ái uêrk / chi uêrks',
  grammar_9: 'ái dôunt / chi dázant',
  grammar_10: 'du iú…? / dáz hi…?',
  grammar_11: 'prêzant cantíniuas: áim uêrking',
  grammar_12: 'pést: uêrkt / uént',
  grammar_13: 'irêguiuler pést: uóz / héd / uént',
  grammar_14: 'fiútcher: uíl',
  grammar_15: 'fiútcher: gôuing tu',
  grammar_16: 'kén / ként',
  grammar_17: 'dér íz / dér ár',
  grammar_18: 'hév tu / níid tu',
  grammar_19: 'campérativz: bíguer / mór…',
  grammar_20: 'úd láik',
  grammar_21: 'óbdjekt uêrdz: mi / iu / him / hêr',

  // ── irregular · Irregular verbs (nível 2, autorado) ──────────────────────
  irregular_0: 'gôu → uént',
  irregular_1: 'hév → héd',
  irregular_2: 'bíi → uóz / uêr',
  irregular_3: 'dú → díd',
  irregular_4: 'sêi → sêd',
  irregular_5: 'mêik → mêid',
  irregular_6: 'têik → túk',
  irregular_7: 'cám → kêim',
  irregular_8: 'síi → só',
  irregular_9: 'guêt → gót',
  irregular_10: 'guív → guêiv',
  irregular_11: 'nôu → nú',
  irregular_12: 'fínk → fót',
  irregular_13: 'fáind → fáund',

  // ── money · Money & banking (nível 3) ────────────────────────────────────
  money_0: 'bénk akáunt',
  money_1: 'ái ár díi námber',
  money_2: 'bíl',
  money_3: 'rênt',
  money_4: 'uêidjaz / pêi',
  money_5: 'fórtnait',
  money_6: 'sêivingz',
  money_7: 'ikspênsiv',
  money_8: 'dóler',
  money_9: 'sênts',
  money_10: 'trénsfer',
  money_11: 'êi tíi êm',
  money_12: 'dipózit',
  money_13: 'bádjat',

  // ── housing · Housing & renting (nível 3) ────────────────────────────────
  housing_0: 'flét',
  housing_1: 'flétmeit',
  housing_2: 'léndlord',
  housing_3: 'lêting êidjant',
  housing_4: 'bónd',
  housing_5: 'líis / tênansi',
  housing_6: 'viúing',
  housing_7: 'fêrnicht',
  housing_8: 'páuer / ilektríssiti',
  housing_9: 'híit pámp',
  housing_10: 'rábich / bín',
  housing_11: 'rissáicling',
  housing_12: 'sáberb',
  housing_13: 'démp',
  housing_14: 'kíi',
  housing_15: 'adrês',

  // ── health · Health, GP & pharmacy (nível 3) ─────────────────────────────
  health_0: 'djíi píi',
  health_1: 'apóintmant',
  health_2: 'kêmist / fármassi',
  health_3: 'priscrípchan',
  health_4: 'mêdsan',
  health_5: 'ái fíil sík',
  health_6: 'it hêrts hír',
  health_7: 'hêdeik',
  health_8: 'fíiver',
  health_9: 'cóf',
  health_10: 'côuld / flú',
  health_11: 'nêrs',
  health_12: 'hóspital',
  health_13: 'dêntist',
  health_14: 'hêlflain',
  health_15: 'áim prêgnant',

  // ── transport · Getting around (nível 3) ─────────────────────────────────
  transport_0: 'bás',
  transport_1: 'bás stóp',
  transport_2: 'êi tíi hóp / bíi cárd',
  transport_3: 'trêin',
  transport_4: 'féri',
  transport_5: 'cár',
  transport_6: 'pêtral',
  transport_7: 'dráiverz láissans',
  transport_8: 'lêft sáid',
  transport_9: 'háu du ai guêt tu…',
  transport_10: 'têrn lêft',
  transport_11: 'têrn ráit',
  transport_12: 'strêit ahêd',
  transport_13: 'nír / fár',
  transport_14: 'tréfik láits',
  transport_15: 'fútpéf',

  // ── work · Work & job (nível 3) ──────────────────────────────────────────
  work_0: 'djób',
  work_1: 'síi víi / rézumei',
  work_2: 'ínterviu',
  work_3: 'bós / ménadjer',
  work_4: 'cóliig / uêrkmeit',
  work_5: 'chíft',
  work_6: 'fúl táim',
  work_7: 'párt táim',
  work_8: 'ikspíriens',
  work_9: 'avêilabal',
  work_10: 'brêik',
  work_11: 'míiting',
  work_12: 'íimeil',
  work_13: 'fénk iu fer iór táim',

  // ── smalltalk · Small talk & social (nível 3) ────────────────────────────
  smalltalk_0: 'háuz it gôuing',
  smalltalk_1: 'nót béd, iú',
  smalltalk_2: 'uót du iu dú',
  smalltalk_3: 'uér ar iu fróm',
  smalltalk_4: 'lávli uêder',
  smalltalk_5: 'déts grêit',
  smalltalk_6: 'nôu uêriz',
  smalltalk_7: 'síi iu lêiter',
  smalltalk_8: 'têik kér',
  smalltalk_9: 'hév a gúd uán',
  smalltalk_10: 'áim stíl lêrning ínglich',
  smalltalk_11: 'kud iu hêlp mi',
  smalltalk_12: 'uót dáz dis míin',
  smalltalk_13: 'cangratchulêichanz',

  // ── kiwi · American slang & customs (nível 3) ────────────────────────────
  kiwi_0: 'uáts áp',
  kiwi_1: 'ósam',
  kiwi_2: 'mái béd',
  kiwi_3: 'fór chúr',
  kiwi_4: 'nôu bígui',
  kiwi_5: 'dáun',
  kiwi_6: 'bádi',
  kiwi_7: 'iól',
  kiwi_8: 'kúkaut',
  kiwi_9: 'pótlak',
  kiwi_10: 'rôud tríp',
  kiwi_11: 'têilgueit',
  kiwi_12: 'splít da bíl',
  kiwi_13: 'tchíl',
  kiwi_14: 'uêi ta gôu',
  kiwi_15: 'da stêits',

  // ── arrival · Airport & immigration (nível 3) ────────────────────────────
  arrival_0: 'pésport',
  arrival_1: 'víiza',
  arrival_2: 'fláit',
  arrival_3: 'bórding pés',
  arrival_4: 'lágadj',
  arrival_5: 'bégadj clêim',
  arrival_6: 'aráival',
  arrival_7: 'cástamz',
  arrival_8: 'imigrêichan',
  arrival_9: 'baiou sikiúriti',
  arrival_10: 'diklér',
  arrival_11: 'náfing ta diklér',
  arrival_12: 'nôu fúd ór plénts',
  arrival_13: 'pêrpas av vízit',
  arrival_14: 'áim múving hír',
  arrival_15: 'rêzidans',

  // ── phrasal · Phrasal verbs (nível 4) ────────────────────────────────────
  phrasal_0: 'pík áp',
  phrasal_1: 'guív áp',
  phrasal_2: 'lúk éfter',
  phrasal_3: 'sórt áut',
  phrasal_4: 'rán áut av',
  phrasal_5: 'díil uif',
  phrasal_6: 'guêt ón uif',
  phrasal_7: 'pút áp uif',
  phrasal_8: 'fíguer áut',
  phrasal_9: 'têrn áp',
  phrasal_10: 'dróp óf',
  phrasal_11: 'têik óf',
  phrasal_12: 'cám acrós',
  phrasal_13: 'guêt bái',
  phrasal_14: 'lúk íntu',
  phrasal_15: 'sáin áp',
  phrasal_16: 'uêrk áut',
  phrasal_17: 'bríng áp',
  phrasal_18: 'kól óf',
  phrasal_19: 'kéri ón',
  phrasal_20: 'ênd áp',
  phrasal_21: 'fíl ín',
  phrasal_22: 'hénd ín',
  phrasal_23: 'hôuld ón',
  phrasal_24: 'lúk fóruerd ta',
  phrasal_25: 'púl ôuver',
  phrasal_26: 'pút óf',
  phrasal_27: 'sêt áp',

  // ── connectors · Connectors & linkers (nível 4) ──────────────────────────
  connectors_0: 'hauêver',
  connectors_1: 'oldôu',
  connectors_2: 'dérfor',
  connectors_3: 'ón di áder hénd',
  connectors_4: 'az sún az',
  connectors_5: 'in órder ta',
  connectors_6: 'íivan dôu',
  connectors_7: 'míinuail',
  connectors_8: 'ueréz',
  connectors_9: 'neverdalês',
  connectors_10: 'in adíchan',
  connectors_11: 'az a rizált',
  connectors_12: 'fer ínstans',
  connectors_13: 'in fékt',
  connectors_14: 'áderuaiz',
  connectors_15: 'dispáit',
  connectors_16: 'anlês',
  connectors_17: 'uáil',
  connectors_18: 'bissáidz',
  connectors_19: 'sôu dét',
  connectors_20: 'réder dén',
  connectors_21: 'at da sêim táim',

  // ── opinions · Opinions & discussion (nível 4) ───────────────────────────
  opinions_0: 'ái rêkan…',
  opinions_1: 'áid sêi…',
  opinions_2: 'ta bi ónast',
  opinions_3: 'it dipêndz',
  opinions_4: 'da fíng iz…',
  opinions_5: 'áim nót chúr ai agríi',
  opinions_6: 'fér ináf',
  opinions_7: 'ái síi iór póint',
  opinions_8: 'fram mái póint av viú',
  opinions_9: 'áid réder…',
  opinions_10: 'pêrsanali',
  opinions_11: 'dét mêiks sêns',
  opinions_12: 'áim nót fást',
  opinions_13: 'áp ta iú',
  opinions_14: 'ái dáut it',
  opinions_15: 'az fár az ai nôu',
  opinions_16: 'if iu ésk mi',
  opinions_17: 'its uêrf…',
  opinions_18: 'áid árguiu dét…',
  opinions_19: 'ón bélans',
  opinions_20: 'ta bi fér',
  opinions_21: 'ái têik iór póint',

  // ── workplace · Work & professional (nível 4) ────────────────────────────
  workplace_0: 'dêdlain',
  workplace_1: 'róster',
  workplace_2: 'sáin óf',
  workplace_3: 'fólou áp',
  workplace_4: 'in tchárdj av',
  workplace_5: 'têik ón',
  workplace_6: 'éniual líiv',
  workplace_7: 'kíui sêiver',
  workplace_8: 'nôutis píried',
  workplace_9: 'prabêichan',
  workplace_10: 'táimchiit',
  workplace_11: 'pêislip',
  workplace_12: 'píi êi uái íi',
  workplace_13: 'ôuvertaim',
  workplace_14: 'chíft',
  workplace_15: 'héndouver',
  workplace_16: 'perfórmans riviú',
  workplace_17: 'cóntrekt',
  workplace_18: 'rêfrans',
  workplace_19: 'rizáin',
  workplace_20: 'aplái fer',
  workplace_21: 'chórtlist',
  workplace_22: 'indákchan',
  workplace_23: 'hêlf an sêifti',
  workplace_24: 'kéjual uêrk',
  workplace_25: 'fíkst têrm',

  // ── idioms · Idioms & Kiwi collocations (nível 4) ────────────────────────
  idioms_0: 'híips av',
  idioms_1: 'kíin éz',
  idioms_2: 'tchóka blók',
  idioms_3: 'guív it a gôu',
  idioms_4: 'nôu dráamaz',
  idioms_5: 'flét áut',
  idioms_6: 'hárd iéka',
  idioms_7: 'chil bi ráit',
  idioms_8: 'a píis av kêik',
  idioms_9: 'áut av da blú',
  idioms_10: 'ôuver da mún',
  idioms_11: 'ánder da uêder',
  idioms_12: 'ón da ból',
  idioms_13: 'tátch bêis',
  idioms_14: 'guêt da héng av',
  idioms_15: 'in da lúp',
  idioms_16: 'kól it a dêi',
  idioms_17: 'cát córnerz',
  idioms_18: 'báit da búlat',
  idioms_19: 'brêik di áis',
  idioms_20: 'hít da rôud',
  idioms_21: 'spót ón',

  // ── tenses · Trickier tenses (nível 4) ───────────────────────────────────
  // Aqui transcrevemos o exemplo do cartão na forma contraída da fala — é o
  // que ela precisa dizer. O rótulo ("present perfect + since") é metalinguagem.
  tenses_0: 'aiv lívd hír sins mártch',
  tenses_1: 'chiz uêrkt hír fer tú iírz',
  tenses_2: 'uív bin uêiting fer an áuer',
  tenses_3: 'aid fínicht díner bifór chi kóld',
  tenses_4: 'if iu mís da bás, iul bi lêit',
  tenses_5: 'if it rêinz, uil stêi hôum',
  tenses_6: 'if ai héd mór máni, aid trével',
  tenses_7: 'if chi uán da lótou, chid kuít',
  tenses_8: 'if ai had nôun, aidav cám',
  tenses_9: 'uí údantav míst it if uíd lêft êrlier',
  tenses_10: 'ái iúst ta smôuk, bat ai kuít',
  tenses_11: 'chi dídant iús ta láik cófi',
  tenses_12: 'uí ud uók ta skúl êvri dêi',
  tenses_13: 'áim gána stárt a nú djób',
  tenses_14: 'áil kól da plámer ráit náu',
  tenses_15: 'itl próbabli rêin tamórou',
  tenses_16: 'da bás iz abáut ta líiv',
  tenses_17: 'bái da táim ui aráivd, it had clôuzd',
  tenses_18: 'iúd bêter hári ór iul mís it',
  tenses_19: 'chi máitav míst da bás',
  tenses_20: 'iu chúdav kóld mi fêrst',
  tenses_21: 'ai chúdantav íitan dét pái',
}
