// GENERATED by scripts/fetch-photos.mjs — DO NOT EDIT BY HAND.
//
// Pexels does not require attribution but asks for it, and the
// photographers gave these away for free. One entry per photo.
import type { PhotoCredit } from '../../types'

export const PHOTO_CREDITS: Record<string, PhotoCredit> = {
  "arrival_0": {
    "photographer": "Marta Branco",
    "url": "https://www.pexels.com/photo/european-passports-and-id-cards-close-up-32081456/"
  },
  "arrival_2": {
    "photographer": "Lucas Pezeta",
    "url": "https://www.pexels.com/photo/silhouette-of-an-airplane-in-mid-air-5703069/"
  },
  "arrival_3": {
    "photographer": "Torsten Dettlaff",
    "url": "https://www.pexels.com/photo/orange-and-green-label-airplane-ticket-69866/"
  },
  "arrival_4": {
    "photographer": "Jahra Tasfia Reza",
    "url": "https://www.pexels.com/photo/colorful-suitcases-stacked-in-a-travel-setting-34629931/"
  },
  "arrival_5": {
    "photographer": "Markus Winkler",
    "url": "https://www.pexels.com/photo/a-luggage-conveyor-inside-airport-3693017/"
  },
  "arrival_6": {
    "photographer": "Harm Jakob Tolsma",
    "url": "https://www.pexels.com/photo/arrivals-aankomst-terminal-1-signage-1719490/"
  },
  "basics_0": {
    "photographer": "AI25.Studio  Studio",
    "url": "https://www.pexels.com/photo/person-holding-color-palettes-5292188/"
  },
  "basics_1": {
    "photographer": "Steve A Johnson",
    "url": "https://www.pexels.com/photo/red-and-white-painting-1962555/"
  },
  "basics_2": {
    "photographer": "Mark Henry Rood",
    "url": "https://www.pexels.com/photo/blue-boat-board-16556292/"
  },
  "basics_3": {
    "photographer": "Engin Akyurt",
    "url": "https://www.pexels.com/photo/blurry-green-background-in-different-shades-16689906/"
  },
  "basics_4": {
    "photographer": "Turgay Koca",
    "url": "https://www.pexels.com/photo/close-up-of-yellow-paint-14918674/"
  },
  "basics_5": {
    "photographer": "Tomás Asurmendi",
    "url": "https://www.pexels.com/photo/close-up-of-black-textured-surface-36101854/"
  },
  "basics_6": {
    "photographer": "𝗛&𝗖𝗢 　",
    "url": "https://www.pexels.com/photo/shadow-on-white-wall-in-close-up-photography-11800919/"
  },
  "body_0": {
    "photographer": "Kindel Media",
    "url": "https://www.pexels.com/photo/side-profile-of-a-serious-woman-7298898/"
  },
  "body_1": {
    "photographer": "Luis Quintero",
    "url": "https://www.pexels.com/photo/photo-of-person-s-open-hands-2258248/"
  },
  "body_10": {
    "photographer": "Towfiqu barbhuiya",
    "url": "https://www.pexels.com/photo/close-up-photo-of-person-holding-his-belly-11773868/"
  },
  "body_11": {
    "photographer": "Nathan Bernardoni",
    "url": "https://www.pexels.com/photo/mans-back-in-black-and-white-17770535/"
  },
  "body_13": {
    "photographer": "freestocks.org",
    "url": "https://www.pexels.com/photo/woman-in-naked-figure-113042/"
  },
  "body_2": {
    "photographer": "Samer Daboul",
    "url": "https://www.pexels.com/photo/man-raising-his-right-arm-2080544/"
  },
  "body_3": {
    "photographer": "ROCKETMANN TEAM",
    "url": "https://www.pexels.com/photo/women-standing-barefooted-9486805/"
  },
  "body_4": {
    "photographer": "Noelle Otto",
    "url": "https://www.pexels.com/photo/splash-of-water-906023/"
  },
  "body_5": {
    "photographer": "Wojtek Pacześ",
    "url": "https://www.pexels.com/photo/close-up-photo-of-an-eye-green-and-white-eye-3695875/"
  },
  "body_6": {
    "photographer": "https://kaboompics.com/",
    "url": "https://www.pexels.com/photo/a-woman-s-ear-8092983/"
  },
  "body_7": {
    "photographer": "Manuel Campagnoli",
    "url": "https://www.pexels.com/photo/close-up-of-woman-s-lips-with-natural-skin-texture-31328995/"
  },
  "body_9": {
    "photographer": "Towfiqu barbhuiya",
    "url": "https://www.pexels.com/photo/a-close-up-shot-of-a-person-s-teeth-12474261/"
  },
  "clothes_0": {
    "photographer": "Arnie Chou",
    "url": "https://www.pexels.com/photo/hanged-assorted-shirts-965632/"
  },
  "clothes_1": {
    "photographer": "onkar  salvi",
    "url": "https://www.pexels.com/photo/close-up-of-colorful-shirts-11176397/"
  },
  "clothes_10": {
    "photographer": "Thirdman",
    "url": "https://www.pexels.com/photo/a-person-in-yellow-rain-boots-holding-stainless-steel-water-can-7656741/"
  },
  "clothes_12": {
    "photographer": "Uday Veeru",
    "url": "https://www.pexels.com/photo/abstract-rainfall-droplets-on-dark-surface-38340424/"
  },
  "clothes_13": {
    "photographer": "Alexey Demidov",
    "url": "https://www.pexels.com/photo/smiling-woman-with-flowing-hair-10982918/"
  },
  "clothes_14": {
    "photographer": "MarcTutorials",
    "url": "https://www.pexels.com/photo/palm-trees-1152359/"
  },
  "clothes_15": {
    "photographer": "Umar Andrabi",
    "url": "https://www.pexels.com/photo/majestic-storm-clouds-20531247/"
  },
  "clothes_2": {
    "photographer": "cottonbro studio",
    "url": "https://www.pexels.com/photo/three-people-in-denim-outfits-6770027/"
  },
  "clothes_3": {
    "photographer": "Eliezer Muller",
    "url": "https://www.pexels.com/photo/stylish-camel-coat-and-wool-scarf-indoors-36180262/"
  },
  "clothes_4": {
    "photographer": "Nathan J Hilton",
    "url": "https://www.pexels.com/photo/white-and-gray-trainers-11946030/"
  },
  "clothes_5": {
    "photographer": "https://kaboompics.com/",
    "url": "https://www.pexels.com/photo/multicolored-socks-drying-on-rope-with-clothespins-in-open-air-4495756/"
  },
  "clothes_6": {
    "photographer": "Castorly Stock",
    "url": "https://www.pexels.com/photo/blue-denim-pants-on-table-4109755/"
  },
  "clothes_7": {
    "photographer": "Chris F",
    "url": "https://www.pexels.com/photo/pink-dress-on-a-mannequin-8619007/"
  },
  "clothes_8": {
    "photographer": "Marcelo  Lemes",
    "url": "https://www.pexels.com/photo/stylish-baseball-caps-displayed-on-shelf-31162881/"
  },
  "clothes_9": {
    "photographer": "Mateus  Rodrigues",
    "url": "https://www.pexels.com/photo/women-with-umbrellas-standing-on-sidewalk-12348815/"
  },
  "emergency_10": {
    "photographer": "Tobias Scheuer",
    "url": "https://www.pexels.com/photo/bright-red-stop-sign-in-green-forest-setting-34075426/"
  },
  "emergency_11": {
    "photographer": "Griffin Wooldridge",
    "url": "https://www.pexels.com/photo/warning-sign-on-a-door-4978542/"
  },
  "emergency_3": {
    "photographer": "Antonio Batinić",
    "url": "https://www.pexels.com/photo/ambulances-on-a-parking-lot-5364345/"
  },
  "emergency_4": {
    "photographer": "112 Uttar Pradesh",
    "url": "https://www.pexels.com/photo/serious-policeman-standing-near-car-4496624/"
  },
  "emergency_5": {
    "photographer": "marco allasio",
    "url": "https://www.pexels.com/photo/photo-of-flames-during-night-time-4275989/"
  },
  "feelings_0": {
    "photographer": "Andrea Piacquadio",
    "url": "https://www.pexels.com/photo/woman-wearing-black-jacket-3768882/"
  },
  "feelings_1": {
    "photographer": "Liza Summer",
    "url": "https://www.pexels.com/photo/sad-woman-sitting-on-couch-6382660/"
  },
  "feelings_10": {
    "photographer": "Pavel Danilyuk",
    "url": "https://www.pexels.com/photo/surprised-happy-woman-in-red-long-sleeve-shirt-looking-in-excitement-8638014/"
  },
  "feelings_12": {
    "photographer": "https://kaboompics.com/",
    "url": "https://www.pexels.com/photo/photograph-of-a-bored-woman-wearing-a-headband-7320373/"
  },
  "feelings_2": {
    "photographer": "cottonbro studio",
    "url": "https://www.pexels.com/photo/a-woman-in-blue-blazer-yawning-5990143/"
  },
  "feelings_5": {
    "photographer": "Aleksey Bystrov",
    "url": "https://www.pexels.com/photo/woman-in-mittens-covering-her-face-on-a-winter-day-15212524/"
  },
  "feelings_7": {
    "photographer": "Andrea Piacquadio",
    "url": "https://www.pexels.com/photo/woman-in-gray-tank-top-looking-frightened-3812729/"
  },
  "feelings_8": {
    "photographer": "Andrea Piacquadio",
    "url": "https://www.pexels.com/photo/woman-in-gray-tank-top-3812746/"
  },
  "food_0": {
    "photographer": "Pixabay",
    "url": "https://www.pexels.com/photo/close-up-of-bottle-pouring-water-on-glass-327090/"
  },
  "food_1": {
    "photographer": "Josh Sorenson",
    "url": "https://www.pexels.com/photo/photo-of-paper-cup-on-top-of-the-table-976876/"
  },
  "food_12": {
    "photographer": "MART  PRODUCTION",
    "url": "https://www.pexels.com/photo/brown-paper-bag-on-concrete-stairs-8165417/"
  },
  "food_2": {
    "photographer": "Juan Pablo Serrano",
    "url": "https://www.pexels.com/photo/coffee-in-white-ceramic-teacup-on-white-ceramic-suacer-894696/"
  },
  "food_3": {
    "photographer": "Arturo Añez.",
    "url": "https://www.pexels.com/photo/a-white-ceramic-teapot-beside-white-and-blue-cup-13110529/"
  },
  "food_4": {
    "photographer": "Cats Coming",
    "url": "https://www.pexels.com/photo/close-up-of-fresh-homemade-bread-on-table-5657400/"
  },
  "food_5": {
    "photographer": "Manit Seekhao",
    "url": "https://www.pexels.com/photo/fork-and-spoon-beside-a-breakfast-meal-12824418/"
  },
  "food_6": {
    "photographer": "ΘSWΛLD",
    "url": "https://www.pexels.com/photo/two-ready-to-eat-wrapped-sandwiches-15974769/"
  },
  "food_7": {
    "photographer": "Kha Ruxury",
    "url": "https://www.pexels.com/photo/light-over-juice-on-table-in-darkness-17527769/"
  },
  "food_8": {
    "photographer": "Katya Wolf",
    "url": "https://www.pexels.com/photo/a-woman-holding-a-black-menu-book-8715595/"
  },
  "health_0": {
    "photographer": "cottonbro studio",
    "url": "https://www.pexels.com/photo/woman-in-white-suit-with-stethoscope-talking-to-a-person-7579823/"
  },
  "health_10": {
    "photographer": "Andrea Piacquadio",
    "url": "https://www.pexels.com/photo/woman-lying-on-bed-while-blowing-her-nose-3807629/"
  },
  "health_11": {
    "photographer": "https://kaboompics.com/",
    "url": "https://www.pexels.com/photo/a-doctor-holding-a-digital-tablet-5206922/"
  },
  "health_12": {
    "photographer": "Jonathan Meyer",
    "url": "https://www.pexels.com/photo/gray-steel-post-lamp-668300/"
  },
  "health_13": {
    "photographer": "SHVETS production",
    "url": "https://www.pexels.com/photo/female-dentist-doing-an-examination-on-her-elderly-patient-8413334/"
  },
  "health_2": {
    "photographer": "World Sikh Organization of Canada",
    "url": "https://www.pexels.com/photo/smiling-pharmacist-with-beard-14797857/"
  },
  "health_3": {
    "photographer": "https://kaboompics.com/",
    "url": "https://www.pexels.com/photo/woman-holding-a-pen-7195122/"
  },
  "health_4": {
    "photographer": "SHVETS production",
    "url": "https://www.pexels.com/photo/medicine-tablets-beside-a-plastic-container-9742882/"
  },
  "health_7": {
    "photographer": "Andrea Piacquadio",
    "url": "https://www.pexels.com/photo/woman-with-headache-3921418/"
  },
  "health_8": {
    "photographer": "Polina Tankilevitch",
    "url": "https://www.pexels.com/photo/thermometer-on-blanket-3873200/"
  },
  "health_9": {
    "photographer": "Towfiqu barbhuiya",
    "url": "https://www.pexels.com/photo/a-man-in-a-plaid-shirt-coughing-11501479/"
  },
  "house_0": {
    "photographer": "Luis Quintero",
    "url": "https://www.pexels.com/photo/blue-wooden-french-doors-2564866/"
  },
  "house_1": {
    "photographer": "Zişan  Özdemir",
    "url": "https://www.pexels.com/photo/light-art-architecture-luxury-28285060/"
  },
  "house_10": {
    "photographer": "ready made",
    "url": "https://www.pexels.com/photo/croissants-on-a-tray-3850398/"
  },
  "house_11": {
    "photographer": "Bilguun Gantumur",
    "url": "https://www.pexels.com/photo/modern-black-kitchen-sink-with-marble-backsplash-38310807/"
  },
  "house_12": {
    "photographer": "https://kaboompics.com/",
    "url": "https://www.pexels.com/photo/close-up-photo-of-a-shower-head-4194866/"
  },
  "house_13": {
    "photographer": "Dom J",
    "url": "https://www.pexels.com/photo/white-and-maroon-rugs-45980/"
  },
  "house_14": {
    "photographer": "Engin Akyurt",
    "url": "https://www.pexels.com/photo/close-up-photography-of-gray-textile-1487701/"
  },
  "house_15": {
    "photographer": "Jonathan Borba",
    "url": "https://www.pexels.com/photo/selective-focus-of-hanging-light-bulb-12876508/"
  },
  "house_16": {
    "photographer": "Patrycja Grobelny",
    "url": "https://www.pexels.com/photo/white-steel-rib-radiator-in-a-new-bright-renovated-room-in-apartment-or-home-12034871/"
  },
  "house_2": {
    "photographer": "Tirachard Kumtanom",
    "url": "https://www.pexels.com/photo/brown-wooden-panel-347139/"
  },
  "house_3": {
    "photographer": "Jan van der Wolf",
    "url": "https://www.pexels.com/photo/photograph-of-wooden-chairs-near-a-wall-10892990/"
  },
  "house_4": {
    "photographer": "Jaymantri",
    "url": "https://www.pexels.com/photo/white-bed-comforter-212269/"
  },
  "house_5": {
    "photographer": "Max Vakhtbovych",
    "url": "https://www.pexels.com/photo/an-interior-of-a-modern-kitchen-counter-7045356/"
  },
  "house_6": {
    "photographer": "Max Vakhtbovych",
    "url": "https://www.pexels.com/photo/white-bathtub-and-sink-in-spacious-bathtub-at-home-6957081/"
  },
  "house_7": {
    "photographer": "Michael D Beckwith",
    "url": "https://www.pexels.com/photo/historic-english-bedroom-with-vintage-decor-37884161/"
  },
  "house_8": {
    "photographer": "Max Vakhtbovych",
    "url": "https://www.pexels.com/photo/couch-with-cushions-in-living-room-6758245/"
  },
  "house_9": {
    "photographer": "Anna Shvets",
    "url": "https://www.pexels.com/photo/young-woman-standing-next-to-an-open-refrigerator-6593607/"
  },
  "housing_0": {
    "photographer": "Robin Osolinski",
    "url": "https://www.pexels.com/photo/modern-urban-building-architecture-against-blue-sky-37301680/"
  },
  "housing_10": {
    "photographer": "Yori H",
    "url": "https://www.pexels.com/photo/garbage-bins-on-city-street-19775307/"
  },
  "housing_11": {
    "photographer": "Xavier Messina",
    "url": "https://www.pexels.com/photo/plastic-crate-with-empty-glass-bottles-18799752/"
  },
  "housing_12": {
    "photographer": "Curtis Adams",
    "url": "https://www.pexels.com/photo/photo-of-houses-during-daytime-3571200/"
  },
  "housing_14": {
    "photographer": "Ingo Joseph",
    "url": "https://www.pexels.com/photo/gray-ikon-keys-on-brown-wooden-surface-14721/"
  },
  "housing_8": {
    "photographer": "Andy Lee",
    "url": "https://www.pexels.com/photo/electricity-pole-with-wires-18332045/"
  },
  "housing_9": {
    "photographer": "alpha innotec",
    "url": "https://www.pexels.com/photo/air-conditioner-on-outside-wall-20046692/"
  },
  "kiwi_10": {
    "photographer": "Alican Helik",
    "url": "https://www.pexels.com/photo/convertible-silver-car-is-driving-fast-18059861/"
  },
  "kiwi_11": {
    "photographer": "Wendy Wei",
    "url": "https://www.pexels.com/photo/gathering-on-car-park-9578109/"
  },
  "kiwi_15": {
    "photographer": "Linda Rusinko",
    "url": "https://www.pexels.com/photo/us-a-flag-on-pole-under-blue-sky-7483195/"
  },
  "kiwi_8": {
    "photographer": "Harvey Ashwin",
    "url": "https://www.pexels.com/photo/person-grilling-sausages-and-patties-at-a-backyard-4824157/"
  },
  "kiwi_9": {
    "photographer": "Cedric Fauntleroy",
    "url": "https://www.pexels.com/photo/a-group-of-friends-eating-together-7220804/"
  },
  "money_11": {
    "photographer": "Jan van der Wolf",
    "url": "https://www.pexels.com/photo/modern-yellow-atm-geldmaat-machine-on-dark-wall-33307521/"
  },
  "money_6": {
    "photographer": "Towfiqu barbhuiya",
    "url": "https://www.pexels.com/photo/clear-glass-jar-with-silver-coins-9821387/"
  },
  "money_8": {
    "photographer": "Engin Akyurt",
    "url": "https://www.pexels.com/photo/dollar-bills-on-a-wooden-surface-10149296/"
  },
  "money_9": {
    "photographer": "Mike Bird",
    "url": "https://www.pexels.com/photo/bronze-collection-of-coins-189405/"
  },
  "people_10": {
    "photographer": "khebab salaheddine",
    "url": "https://www.pexels.com/photo/portrait-of-boy-in-black-and-white-21053489/"
  },
  "people_11": {
    "photographer": "Mery Amiri",
    "url": "https://www.pexels.com/photo/young-girl-holding-vintage-camera-in-black-and-white-30002351/"
  },
  "people_2": {
    "photographer": "Werner Pfennig",
    "url": "https://www.pexels.com/photo/smiling-kid-in-white-long-sleeves-holding-a-pencil-6482281/"
  },
  "people_3": {
    "photographer": "Antonius Ferret",
    "url": "https://www.pexels.com/photo/happy-children-in-mantles-playing-outdoors-5275834/"
  },
  "people_4": {
    "photographer": "Jonathan Borba",
    "url": "https://www.pexels.com/photo/smiling-mother-sitting-with-baby-on-stairs-19773885/"
  },
  "people_5": {
    "photographer": "Ketut Subiyanto",
    "url": "https://www.pexels.com/photo/a-father-and-son-playing-building-blocks-4934159/"
  },
  "people_6": {
    "photographer": "Ketut Subiyanto",
    "url": "https://www.pexels.com/photo/women-holding-disposable-cups-laughing-5047002/"
  },
  "people_8": {
    "photographer": "Karol Zieliński",
    "url": "https://www.pexels.com/photo/grayscale-photo-of-mans-face-9181434/"
  },
  "people_9": {
    "photographer": "Peter Platou",
    "url": "https://www.pexels.com/photo/thoughtful-portrait-of-a-woman-indoors-37389134/"
  },
  "shopping_10": {
    "photographer": "Pixabay",
    "url": "https://www.pexels.com/photo/euro-pound-banknote-lot-259251/"
  },
  "shopping_11": {
    "photographer": "Aukid phumsirichat",
    "url": "https://www.pexels.com/photo/man-in-blue-button-up-shirt-holding-a-credit-card-4691471/"
  },
  "shopping_12": {
    "photographer": "RDNE Stock project",
    "url": "https://www.pexels.com/photo/a-bag-with-groceries-on-the-floor-7363085/"
  },
  "shopping_6": {
    "photographer": "https://kaboompics.com/",
    "url": "https://www.pexels.com/photo/a-person-holding-a-wallet-4968388/"
  },
  "shopping_7": {
    "photographer": "cedric george",
    "url": "https://www.pexels.com/photo/shopping-carts-lined-up-outside-24-hour-supermarket-35009698/"
  },
  "shopping_8": {
    "photographer": "Radik 2707",
    "url": "https://www.pexels.com/photo/cashier-at-supermarket-checkout-counter-36772947/"
  },
  "shopping_9": {
    "photographer": "https://kaboompics.com/",
    "url": "https://www.pexels.com/photo/making-a-payment-with-a-debit-card-4968635/"
  },
  "town_0": {
    "photographer": "Shamba Datta",
    "url": "https://www.pexels.com/photo/traffic-in-front-of-a-hotel-in-lucerne-switzerland-17091398/"
  },
  "town_1": {
    "photographer": "Михаил Крамор",
    "url": "https://www.pexels.com/photo/a-concrete-road-between-a-grassy-field-12939244/"
  },
  "town_10": {
    "photographer": "Jan van der Wolf",
    "url": "https://www.pexels.com/photo/inclusive-restroom-sign-with-wheelchair-icon-35597510/"
  },
  "town_11": {
    "photographer": "Aaryan Jain",
    "url": "https://www.pexels.com/photo/cozy-cafe-interior-with-espresso-machine-29833130/"
  },
  "town_12": {
    "photographer": "Jonathan Borba",
    "url": "https://www.pexels.com/photo/gentle-ocean-wave-on-sandy-beach-35786603/"
  },
  "town_13": {
    "photographer": "leyvaine davids",
    "url": "https://www.pexels.com/photo/dramatic-auckland-city-skyline-at-daytime-34083204/"
  },
  "town_2": {
    "photographer": "Miguel González",
    "url": "https://www.pexels.com/photo/aerial-view-of-urban-intersection-with-crosswalks-34997117/"
  },
  "town_3": {
    "photographer": "Hüseyin Göçek",
    "url": "https://www.pexels.com/photo/a-man-standing-outside-of-a-store-28153483/"
  },
  "town_4": {
    "photographer": "Zeynep",
    "url": "https://www.pexels.com/photo/writing-in-entrance-to-bank-in-turkey-18556288/"
  },
  "town_5": {
    "photographer": "Bingqian Li",
    "url": "https://www.pexels.com/photo/exterior-view-of-french-la-poste-building-33376731/"
  },
  "town_6": {
    "photographer": "Ahmet Polat",
    "url": "https://www.pexels.com/photo/brown-wooden-book-shelves-in-the-bookstore-5225982/"
  },
  "town_7": {
    "photographer": "Bob Jenkin",
    "url": "https://www.pexels.com/photo/serene-summer-day-at-london-park-pathway-32666094/"
  },
  "town_8": {
    "photographer": "Borys Zaitsev",
    "url": "https://www.pexels.com/photo/beige-concrete-buildings-under-blue-sky-12444974/"
  },
  "town_9": {
    "photographer": "Gonzalo Carlos Novillo Lapeyra",
    "url": "https://www.pexels.com/photo/a-gas-station-at-night-19286387/"
  },
  "transport_0": {
    "photographer": "Oliver Boese",
    "url": "https://www.pexels.com/photo/buss-and-cars-on-city-street-bus-display-word-sorry-4774659/"
  },
  "transport_1": {
    "photographer": "Joaquin Carfagna",
    "url": "https://www.pexels.com/photo/men-waiting-on-bus-stop-in-london-18111366/"
  },
  "transport_14": {
    "photographer": "Mathias Reding",
    "url": "https://www.pexels.com/photo/blue-and-red-light-fixture-10289021/"
  },
  "transport_3": {
    "photographer": "Сергей Велов",
    "url": "https://www.pexels.com/photo/train-in-the-station-servicing-commuters-12367459/"
  },
  "transport_4": {
    "photographer": "Brian Cook",
    "url": "https://www.pexels.com/photo/sydney-ferry_1-28387531/"
  },
  "transport_5": {
    "photographer": "Crab Lens",
    "url": "https://www.pexels.com/photo/a-car-on-a-road-12770250/"
  },
  "transport_6": {
    "photographer": "ClickerHappy",
    "url": "https://www.pexels.com/photo/car-refill-transportation-gas-9796/"
  },
  "transport_7": {
    "photographer": "Dom J",
    "url": "https://www.pexels.com/photo/uk-driving-license-45113/"
  },
  "work_1": {
    "photographer": "Lukas Blazek",
    "url": "https://www.pexels.com/photo/white-ceramic-cup-on-brown-wooden-surface-590044/"
  },
  "work_11": {
    "photographer": "Matheus Bertelli",
    "url": "https://www.pexels.com/photo/casual-team-meeting-in-modern-office-29267507/"
  },
  "work_2": {
    "photographer": "Tima Miroshnichenko",
    "url": "https://www.pexels.com/photo/female-candidate-doing-hand-shakes-5439153/"
  }
}
