// GENERATED by scripts/fetch-photos.mjs — DO NOT EDIT BY HAND.
//
// Card id -> public path of its photograph. Merged onto the Polish decks,
// the same way PHOTOS_ES is for Spanish. Empty until Task 13 runs the
// script; a card with no entry here simply renders without a picture.
export const PHOTOS_PL: Record<string, string> = {}
