// GENERATED by scripts/fetch-photos.mjs — DO NOT EDIT BY HAND.
//
// Pexels does not require attribution but asks for it, and the
// photographers gave these away for free. One entry per photo.
import type { PhotoCredit } from '../../types'

export const PHOTO_CREDITS_ES: Record<string, PhotoCredit> = {
  "es_false_0": {
    "photographer": "Ivan S",
    "url": "https://www.pexels.com/photo/a-pregnant-woman-in-brown-sweater-holding-a-bouquet-of-flowers-while-walking-on-the-street-7990621/"
  },
  "es_false_15": {
    "photographer": "Gwladys Nicimbikije",
    "url": "https://www.pexels.com/photo/tomato-sauce-with-mozzarella-and-tomatoes-35428719/"
  },
  "es_false_16": {
    "photographer": "Tiberiu",
    "url": "https://www.pexels.com/photo/a-parsley-plant-in-close-up-photography-5833170/"
  },
  "es_false_17": {
    "photographer": "Steve A Johnson",
    "url": "https://www.pexels.com/photo/red-and-white-painting-1962555/"
  },
  "es_false_18": {
    "photographer": "Steve A Johnson",
    "url": "https://www.pexels.com/photo/vibrant-purple-and-yellow-abstract-painting-30874918/"
  },
  "es_false_19": {
    "photographer": "Kha Ruxury",
    "url": "https://www.pexels.com/photo/light-over-juice-on-table-in-darkness-17527769/"
  },
  "es_false_23": {
    "photographer": "TUBARONES PHOTOGRAPHY",
    "url": "https://www.pexels.com/photo/ham-slices-with-chive-9670688/"
  },
  "es_false_24": {
    "photographer": "Anh Lee",
    "url": "https://www.pexels.com/photo/group-of-students-in-classroom-celebrating-33415745/"
  },
  "es_false_5": {
    "photographer": "https://kaboompics.com/",
    "url": "https://www.pexels.com/photo/man-in-white-and-black-striped-shirt-smiling-6333498/"
  },
  "es_false_7": {
    "photographer": "cottonbro studio",
    "url": "https://www.pexels.com/photo/desks-with-desk-lamps-in-an-office-8369211/"
  },
  "es_false_8": {
    "photographer": "Renee Razumov",
    "url": "https://www.pexels.com/photo/car-repair-and-maintenance-workshop-interior-33814734/"
  },
  "es_false_9": {
    "photographer": "Thới Nam Cao",
    "url": "https://www.pexels.com/photo/a-drinking-glasses-on-a-wooden-table-10115519/"
  },
  "es_home_0": {
    "photographer": "Max Vakhtbovych",
    "url": "https://www.pexels.com/photo/an-interior-of-a-modern-kitchen-counter-7045356/"
  },
  "es_home_1": {
    "photographer": "Michael D Beckwith",
    "url": "https://www.pexels.com/photo/historic-english-bedroom-with-vintage-decor-37884161/"
  },
  "es_home_11": {
    "photographer": "Bilguun Gantumur",
    "url": "https://www.pexels.com/photo/modern-black-kitchen-sink-with-marble-backsplash-38310807/"
  },
  "es_home_12": {
    "photographer": "Humphrey  Jones-Behan",
    "url": "https://www.pexels.com/photo/shallow-focus-photography-of-light-bulb-1025410/"
  },
  "es_home_2": {
    "photographer": "Max Vakhtbovych",
    "url": "https://www.pexels.com/photo/white-bathtub-and-sink-in-spacious-bathtub-at-home-6957081/"
  },
  "es_home_3": {
    "photographer": "Max Vakhtbovych",
    "url": "https://www.pexels.com/photo/couch-with-cushions-in-living-room-6758245/"
  },
  "es_home_4": {
    "photographer": "Phát Trương",
    "url": "https://www.pexels.com/photo/contrasting-urban-architecture-facades-38000582/"
  },
  "es_home_7": {
    "photographer": "Yori H",
    "url": "https://www.pexels.com/photo/garbage-bins-on-city-street-19775307/"
  },
  "es_things_0": {
    "photographer": "Alexey Demidov",
    "url": "https://www.pexels.com/photo/clear-shot-glass-with-liquid-10482146/"
  },
  "es_things_1": {
    "photographer": "Amar  Preciado",
    "url": "https://www.pexels.com/photo/appetizer-served-in-a-restaurant-23644633/"
  },
  "es_things_11": {
    "photographer": "Sergio Zhukov",
    "url": "https://www.pexels.com/photo/crowded-city-street-with-diverse-group-of-people-31846022/"
  },
  "es_things_12": {
    "photographer": "Ketut Subiyanto",
    "url": "https://www.pexels.com/photo/women-holding-disposable-cups-laughing-5047002/"
  },
  "es_things_13": {
    "photographer": "cottonbro studio",
    "url": "https://www.pexels.com/photo/a-family-sitting-at-the-table-5959750/"
  },
  "es_things_16": {
    "photographer": "Pedro H.  Novais",
    "url": "https://www.pexels.com/photo/portrait-of-woman-with-braided-hair-outdoors-38866875/"
  },
  "es_things_17": {
    "photographer": "Karol Zieliński",
    "url": "https://www.pexels.com/photo/grayscale-photo-of-mans-face-9181434/"
  },
  "es_things_2": {
    "photographer": "Aynur Latfullin",
    "url": "https://www.pexels.com/photo/close-up-of-homemade-sesame-seed-bread-loaf-38168543/"
  },
  "es_things_3": {
    "photographer": "Rachel Claire",
    "url": "https://www.pexels.com/photo/raw-meat-on-a-cutting-board-8112380/"
  },
  "es_things_4": {
    "photographer": "Tom Tran",
    "url": "https://www.pexels.com/photo/sliced-fruits-on-the-plate-11704884/"
  },
  "es_things_5": {
    "photographer": "Josh Sorenson",
    "url": "https://www.pexels.com/photo/photo-of-paper-cup-on-top-of-the-table-976876/"
  },
  "es_things_6": {
    "photographer": "Mahmoud Yahyaoui",
    "url": "https://www.pexels.com/photo/view-of-a-red-house-seen-from-the-bosporus-in-istanbul-turkey-14930288/"
  },
  "es_things_7": {
    "photographer": "Ozan Tabakoğlu",
    "url": "https://www.pexels.com/photo/street-in-city-20375051/"
  },
  "es_things_9": {
    "photographer": "Pixabay",
    "url": "https://www.pexels.com/photo/euro-pound-banknote-lot-259251/"
  },
  "es_topics_10": {
    "photographer": "Mindaugas U",
    "url": "https://www.pexels.com/photo/gray-city-building-1313534/"
  },
  "es_topics_14": {
    "photographer": "Tima Miroshnichenko",
    "url": "https://www.pexels.com/photo/a-variety-of-tools-at-a-workshop-5846253/"
  },
  "es_topics_15": {
    "photographer": "Alexander Pöllinger",
    "url": "https://www.pexels.com/photo/a-tablet-and-a-smartphone-on-a-wooden-table-10535365/"
  },
  "es_topics_22": {
    "photographer": "Xavier Messina",
    "url": "https://www.pexels.com/photo/plastic-crate-with-empty-glass-bottles-18799752/"
  },
  "es_travel_0": {
    "photographer": "https://kaboompics.com/",
    "url": "https://www.pexels.com/photo/money-paper-and-bills-on-white-surface-7680361/"
  },
  "es_travel_1": {
    "photographer": "MART  PRODUCTION",
    "url": "https://www.pexels.com/photo/dollar-bills-on-a-wooden-table-beside-an-ashtray-and-a-wine-glass-9566292/"
  },
  "es_travel_10": {
    "photographer": "Jeffry Surianto",
    "url": "https://www.pexels.com/photo/interior-of-railway-station-20705525/"
  },
  "es_travel_12": {
    "photographer": "https://kaboompics.com/",
    "url": "https://www.pexels.com/photo/female-hands-stamping-paper-7195195/"
  },
  "es_travel_13": {
    "photographer": "cottonbro studio",
    "url": "https://www.pexels.com/photo/an-elderly-woman-looking-at-the-product-she-is-holding-while-standing-beside-a-woman-in-white-uniform-8657366/"
  },
  "es_travel_17": {
    "photographer": "Gustavo Fring",
    "url": "https://www.pexels.com/photo/woman-in-brown-long-sleeve-shirt-and-blue-denim-jeans-3865936/"
  },
  "es_travel_18": {
    "photographer": "Ron Lach",
    "url": "https://www.pexels.com/photo/multicolored-label-tags-9594082/"
  },
  "es_travel_19": {
    "photographer": "Meruyert Gonullu",
    "url": "https://www.pexels.com/photo/an-illuminated-text-signage-7317353/"
  },
  "es_travel_21": {
    "photographer": "https://kaboompics.com/",
    "url": "https://www.pexels.com/photo/money-paper-and-bills-on-white-surface-7680361/"
  },
  "es_travel_22": {
    "photographer": "Pixabay",
    "url": "https://www.pexels.com/photo/euro-pound-banknote-lot-259251/"
  },
  "es_travel_23": {
    "photographer": "Anna Tarazevich",
    "url": "https://www.pexels.com/photo/a-person-handing-bank-card-to-another-person-5242822/"
  },
  "es_travel_24": {
    "photographer": "Jakub Zerdzicki",
    "url": "https://www.pexels.com/photo/miniature-houses-and-keys-symbolize-real-estate-choices-34134899/"
  },
  "es_travel_25": {
    "photographer": "Jahra Tasfia Reza",
    "url": "https://www.pexels.com/photo/collection-of-modern-suitcases-lined-up-34629933/"
  },
  "es_travel_26": {
    "photographer": "Kenneth Surillo",
    "url": "https://www.pexels.com/photo/bustling-airport-check-in-counter-scene-32223420/"
  },
  "es_travel_3": {
    "photographer": "Quang Nguyen Vinh",
    "url": "https://www.pexels.com/photo/modern-hotel-room-with-two-beds-and-natural-light-29000006/"
  },
  "es_travel_34": {
    "photographer": "Ransi Deshadi",
    "url": "https://www.pexels.com/photo/serene-beach-view-in-colombo-sri-lanka-30310146/"
  },
  "es_travel_4": {
    "photographer": "Alfred Franz",
    "url": "https://www.pexels.com/photo/elegant-hotel-reception-with-ornate-woodwork-31231176/"
  },
  "es_travel_5": {
    "photographer": "Erik Mclean",
    "url": "https://www.pexels.com/photo/photo-of-a-person-holding-tickets-8266773/"
  },
  "es_travel_6": {
    "photographer": "Felipe Valtl de Mello",
    "url": "https://www.pexels.com/photo/airplane-on-clear-sky-19563698/"
  },
  "es_travel_9": {
    "photographer": "Joaquin Carfagna",
    "url": "https://www.pexels.com/photo/men-waiting-on-bus-stop-in-london-18111366/"
  },
  "es_work_0": {
    "photographer": "Matheus Bertelli",
    "url": "https://www.pexels.com/photo/casual-team-meeting-in-modern-office-29267507/"
  },
  "es_work_23": {
    "photographer": "Pixabay",
    "url": "https://www.pexels.com/photo/two-red-paper-organizers-265024/"
  },
  "es_work_24": {
    "photographer": "Kindel Media",
    "url": "https://www.pexels.com/photo/close-up-shot-of-a-person-holding-a-clipboard-7651555/"
  },
  "es_work_25": {
    "photographer": "Polina Tankilevitch",
    "url": "https://www.pexels.com/photo/a-person-in-black-and-gray-jacket-handing-over-boxes-to-a-person-4440774/"
  },
  "es_work_3": {
    "photographer": "RDNE Stock project",
    "url": "https://www.pexels.com/photo/a-person-wearing-white-long-sleeves-holding-a-piece-of-paper-on-a-wooden-table-9034223/"
  }
}
