import type { Deck } from '../../types'

/** The rest of a life in Spanish: the house, the week, the body, and the
 * sentence shapes Portuguese does not have. */

export const ES_STRUCTURE_DECK: Deck = {
  id: 'es_structure',
  name: 'Estruturas que a gente erra',
  emoji: '🧩',
  desc: 'Gustar, doler, faltar — a frase que vira do avesso',
  level: 2,
  cards: [
    { id: 'es_structure_0', deckId: 'es_structure', en: 'me gusta', pt: 'eu gosto (de algo)', exampleHtml: '<b>Me gusta</b> mucho esa canción.', examplePt: 'Eu gosto muito dessa música.', pos: 'phrase' },
    { id: 'es_structure_1', deckId: 'es_structure', en: 'me gustan', pt: 'eu gosto (de vários)', exampleHtml: '<b>Me gustan</b> los días fríos.', examplePt: 'Eu gosto dos dias frios.', pos: 'phrase' },
    { id: 'es_structure_2', deckId: 'es_structure', en: 'me falta', pt: 'está me faltando', exampleHtml: '<b>Me falta</b> un poco de tiempo.', examplePt: 'Está me faltando um pouco de tempo.', pos: 'phrase' },
    { id: 'es_structure_3', deckId: 'es_structure', en: 'me sobra', pt: 'está me sobrando', exampleHtml: 'Hoy <b>me sobra</b> trabajo.', examplePt: 'Hoje está me sobrando trabalho.', pos: 'phrase' },
    { id: 'es_structure_4', deckId: 'es_structure', en: 'me encanta', pt: 'eu adoro', exampleHtml: '<b>Me encanta</b> ese restaurante.', examplePt: 'Eu adoro esse restaurante.', pos: 'phrase' },
    { id: 'es_structure_5', deckId: 'es_structure', en: 'me interesa', pt: 'me interessa', exampleHtml: '<b>Me interesa</b> mucho ese tema.', examplePt: 'Esse tema me interessa muito.', pos: 'phrase' },
    { id: 'es_structure_6', deckId: 'es_structure', en: 'me cuesta', pt: 'tenho dificuldade', exampleHtml: '<b>Me cuesta</b> hablar en público.', examplePt: 'Tenho dificuldade de falar em público.', pos: 'phrase' },
    { id: 'es_structure_7', deckId: 'es_structure', en: 'me da miedo', pt: 'tenho medo', exampleHtml: '<b>Me da miedo</b> volar de noche.', examplePt: 'Tenho medo de voar à noite.', pos: 'phrase' },
    { id: 'es_structure_8', deckId: 'es_structure', en: 'me da pena', pt: 'tenho vergonha', exampleHtml: '<b>Me da pena</b> pedir ayuda.', examplePt: 'Tenho vergonha de pedir ajuda.', pos: 'phrase' },
    { id: 'es_structure_9', deckId: 'es_structure', en: 'se me olvidó', pt: 'eu esqueci', exampleHtml: '<b>Se me olvidó</b> avisarte ayer.', examplePt: 'Esqueci de te avisar ontem.', pos: 'phrase' },
    { id: 'es_structure_10', deckId: 'es_structure', en: 'se me perdió', pt: 'eu perdi', exampleHtml: '<b>Se me perdió</b> la llave otra vez.', examplePt: 'Perdi a chave de novo.', pos: 'phrase' },
    { id: 'es_structure_11', deckId: 'es_structure', en: 'se me hizo tarde', pt: 'me atrasei', exampleHtml: 'Perdón, <b>se me hizo tarde</b>.', examplePt: 'Desculpa, me atrasei.', pos: 'phrase' },
    { id: 'es_structure_12', deckId: 'es_structure', en: 'hace falta', pt: 'é preciso', exampleHtml: '<b>Hace falta</b> más gente aquí.', examplePt: 'É preciso mais gente aqui.', pos: 'phrase' },
    { id: 'es_structure_13', deckId: 'es_structure', en: 'hay que', pt: 'tem que (impessoal)', exampleHtml: '<b>Hay que</b> salir más temprano.', examplePt: 'Tem que sair mais cedo.', pos: 'phrase' },
    { id: 'es_structure_14', deckId: 'es_structure', en: 'tengo que', pt: 'eu tenho que', exampleHtml: '<b>Tengo que</b> terminar esto hoy.', examplePt: 'Tenho que terminar isso hoje.', pos: 'phrase' },
    { id: 'es_structure_15', deckId: 'es_structure', en: 'acabo de', pt: 'acabei de', exampleHtml: '<b>Acabo de</b> hablar con ella.', examplePt: 'Acabei de falar com ela.', pos: 'phrase' },
    { id: 'es_structure_16', deckId: 'es_structure', en: 'estoy por', pt: 'estou prestes a', exampleHtml: '<b>Estoy por</b> salir de casa.', examplePt: 'Estou prestes a sair de casa.', pos: 'phrase' },
    { id: 'es_structure_17', deckId: 'es_structure', en: 'llevo dos años', pt: 'faz dois anos que', exampleHtml: '<b>Llevo dos años</b> en esta empresa.', examplePt: 'Faz dois anos que estou nesta empresa.', pos: 'phrase' },
    { id: 'es_structure_18', deckId: 'es_structure', en: 'hace un mes', pt: 'faz um mês', exampleHtml: 'Lo compré <b>hace un mes</b>.', examplePt: 'Comprei faz um mês.', pos: 'phrase' },
    { id: 'es_structure_19', deckId: 'es_structure', en: 'desde hace', pt: 'desde (há tempo)', exampleHtml: 'Vivo aquí <b>desde hace</b> años.', examplePt: 'Moro aqui há anos.', pos: 'phrase' },
    { id: 'es_structure_20', deckId: 'es_structure', en: 'volver a', pt: 'voltar a / de novo', exampleHtml: '<b>Volví a</b> leer ese libro.', examplePt: 'Voltei a ler aquele livro.', pos: 'verb' },
    { id: 'es_structure_21', deckId: 'es_structure', en: 'seguir siendo', pt: 'continuar sendo', exampleHtml: '<b>Sigue siendo</b> mi favorito.', examplePt: 'Continua sendo o meu favorito.', pos: 'phrase' },
    { id: 'es_structure_22', deckId: 'es_structure', en: 'lo mejor', pt: 'o melhor (coisa)', exampleHtml: '<b>Lo mejor</b> fue la comida.', examplePt: 'O melhor foi a comida.', pos: 'phrase' },
    { id: 'es_structure_23', deckId: 'es_structure', en: 'lo que', pt: 'o que', exampleHtml: 'No entendí <b>lo que</b> dijiste.', examplePt: 'Não entendi o que você disse.', pos: 'phrase' },
    { id: 'es_structure_24', deckId: 'es_structure', en: 'todo lo que', pt: 'tudo o que', exampleHtml: 'Anota <b>todo lo que</b> necesites.', examplePt: 'Anota tudo o que precisar.', pos: 'phrase' },
  ],
}

export const ES_HOME_DECK: Deck = {
  id: 'es_home',
  name: 'Casa e rotina',
  emoji: '🏠',
  desc: 'A vida entre quatro paredes e a semana inteira',
  level: 2,
  cards: [
    { id: 'es_home_0', deckId: 'es_home', en: 'la cocina', pt: 'a cozinha', exampleHtml: 'La <b>cocina</b> es bastante grande.', examplePt: 'A cozinha é bastante grande.', pos: 'noun' },
    { id: 'es_home_1', deckId: 'es_home', en: 'el cuarto', pt: 'o quarto', exampleHtml: 'Mi <b>cuarto</b> da a la calle.', examplePt: 'Meu quarto dá para a rua.', pos: 'noun' },
    { id: 'es_home_2', deckId: 'es_home', en: 'el baño', pt: 'o banheiro', exampleHtml: 'El <b>baño</b> está al fondo.', examplePt: 'O banheiro fica no fundo.', pos: 'noun' },
    { id: 'es_home_3', deckId: 'es_home', en: 'la sala', pt: 'a sala', exampleHtml: 'Nos sentamos en la <b>sala</b>.', examplePt: 'Nos sentamos na sala.', pos: 'noun' },
    { id: 'es_home_4', deckId: 'es_home', en: 'el departamento', pt: 'o apartamento', exampleHtml: 'Rentamos un <b>departamento</b> chico.', examplePt: 'Alugamos um apartamento pequeno.', pos: 'noun' },
    { id: 'es_home_5', deckId: 'es_home', en: 'la renta', pt: 'o aluguel', exampleHtml: 'La <b>renta</b> subió este año.', examplePt: 'O aluguel subiu este ano.', pos: 'noun' },
    { id: 'es_home_6', deckId: 'es_home', en: 'el vecino', pt: 'o vizinho', exampleHtml: 'Mi <b>vecino</b> es muy amable.', examplePt: 'Meu vizinho é muito gentil.', pos: 'noun' },
    { id: 'es_home_7', deckId: 'es_home', en: 'la basura', pt: 'o lixo', exampleHtml: 'Saca la <b>basura</b>, por favor.', examplePt: 'Põe o lixo para fora, por favor.', pos: 'noun' },
    { id: 'es_home_8', deckId: 'es_home', en: 'lavar', pt: 'lavar', exampleHtml: 'Tengo que <b>lavar</b> los platos.', examplePt: 'Tenho que lavar a louça.', pos: 'verb' },
    { id: 'es_home_9', deckId: 'es_home', en: 'barrer', pt: 'varrer', exampleHtml: 'Voy a <b>barrer</b> la cocina.', examplePt: 'Vou varrer a cozinha.', pos: 'verb' },
    { id: 'es_home_10', deckId: 'es_home', en: 'tender', pt: 'estender / arrumar', exampleHtml: 'Hay que <b>tender</b> la cama.', examplePt: 'Tem que arrumar a cama.', pos: 'verb' },
    { id: 'es_home_11', deckId: 'es_home', en: 'el grifo', pt: 'a torneira', exampleHtml: 'Cierra bien el <b>grifo</b>, por favor.', examplePt: 'Fecha bem a torneira, por favor.', pos: 'noun' },
    { id: 'es_home_12', deckId: 'es_home', en: 'el foco', pt: 'a lâmpada', exampleHtml: 'Se fundió el <b>foco</b> anoche.', examplePt: 'A lâmpada queimou ontem à noite.', pos: 'noun' },
    { id: 'es_home_13', deckId: 'es_home', en: 'madrugar', pt: 'acordar muito cedo', exampleHtml: 'Mañana tengo que <b>madrugar</b>.', examplePt: 'Amanhã tenho que acordar cedo.', pos: 'verb' },
    { id: 'es_home_14', deckId: 'es_home', en: 'trasnochar', pt: 'virar a noite', exampleHtml: 'Anoche me tocó <b>trasnochar</b>.', examplePt: 'Ontem tive que virar a noite.', pos: 'verb' },
    { id: 'es_home_15', deckId: 'es_home', en: 'el fin de semana', pt: 'o fim de semana', exampleHtml: 'Nos vemos el <b>fin de semana</b>.', examplePt: 'A gente se vê no fim de semana.', pos: 'phrase' },
    { id: 'es_home_16', deckId: 'es_home', en: 'entre semana', pt: 'durante a semana', exampleHtml: '<b>Entre semana</b> casi no salgo.', examplePt: 'Durante a semana quase não saio.', pos: 'phrase' },
    { id: 'es_home_17', deckId: 'es_home', en: 'anteayer', pt: 'anteontem', exampleHtml: 'Llegaron <b>anteayer</b> por la noche.', examplePt: 'Chegaram anteontem à noite.', pos: 'word' },
    { id: 'es_home_18', deckId: 'es_home', en: 'pasado mañana', pt: 'depois de amanhã', exampleHtml: 'Te aviso <b>pasado mañana</b>.', examplePt: 'Te aviso depois de amanhã.', pos: 'phrase' },
    { id: 'es_home_19', deckId: 'es_home', en: 'a diario', pt: 'diariamente', exampleHtml: 'Camino <b>a diario</b> por la tarde.', examplePt: 'Caminho diariamente à tarde.', pos: 'phrase' },
    { id: 'es_home_20', deckId: 'es_home', en: 'de vez en cuando', pt: 'de vez em quando', exampleHtml: 'Nos vemos <b>de vez en cuando</b>.', examplePt: 'A gente se vê de vez em quando.', pos: 'phrase' },
    { id: 'es_home_21', deckId: 'es_home', en: 'a veces', pt: 'às vezes', exampleHtml: '<b>A veces</b> trabajo desde casa.', examplePt: 'Às vezes trabalho de casa.', pos: 'phrase' },
    { id: 'es_home_22', deckId: 'es_home', en: 'temprano', pt: 'cedo', exampleHtml: 'Llegué <b>temprano</b> a la oficina.', examplePt: 'Cheguei cedo no escritório.', pos: 'adj' },
    { id: 'es_home_23', deckId: 'es_home', en: 'tarde', pt: 'tarde', exampleHtml: 'Salimos <b>tarde</b> de la fiesta.', examplePt: 'Saímos tarde da festa.', pos: 'adj' },
    { id: 'es_home_24', deckId: 'es_home', en: 'el rato', pt: 'o tempinho', exampleHtml: 'Espérame un <b>rato</b>, ya voy.', examplePt: 'Me espera um tempinho, já vou.', pos: 'noun' },
  ],
}

export const ES_PEOPLE_DECK: Deck = {
  id: 'es_people',
  name: 'Gente e sentimentos',
  emoji: '🫂',
  desc: 'Descrever alguém e dizer como você está de verdade',
  level: 2,
  cards: [
    { id: 'es_people_0', deckId: 'es_people', en: 'amable', pt: 'gentil', exampleHtml: 'Fue muy <b>amable</b> conmigo.', examplePt: 'Foi muito gentil comigo.', pos: 'adj' },
    { id: 'es_people_1', deckId: 'es_people', en: 'grosero', pt: 'grosseiro', exampleHtml: 'Ese señor fue <b>grosero</b>.', examplePt: 'Aquele senhor foi grosseiro.', pos: 'adj' },
    { id: 'es_people_2', deckId: 'es_people', en: 'terco', pt: 'teimoso', exampleHtml: 'Mi hermano es muy <b>terco</b>.', examplePt: 'Meu irmão é muito teimoso.', pos: 'adj' },
    { id: 'es_people_3', deckId: 'es_people', en: 'perezoso', pt: 'preguiçoso', exampleHtml: 'Hoy estoy medio <b>perezoso</b>.', examplePt: 'Hoje estou meio preguiçoso.', pos: 'adj' },
    { id: 'es_people_4', deckId: 'es_people', en: 'trabajador', pt: 'trabalhador', exampleHtml: 'Es el más <b>trabajador</b> del equipo.', examplePt: 'É o mais trabalhador da equipe.', pos: 'adj' },
    { id: 'es_people_5', deckId: 'es_people', en: 'chistoso', pt: 'engraçado', exampleHtml: 'Tu amigo es muy <b>chistoso</b>.', examplePt: 'Seu amigo é muito engraçado.', pos: 'adj' },
    { id: 'es_people_6', deckId: 'es_people', en: 'agotado', pt: 'exausto', exampleHtml: 'Llegué <b>agotado</b> del viaje.', examplePt: 'Cheguei exausto da viagem.', pos: 'adj' },
    { id: 'es_people_7', deckId: 'es_people', en: 'harto', pt: 'de saco cheio', exampleHtml: 'Ya estoy <b>harto</b> de esperar.', examplePt: 'Já estou de saco cheio de esperar.', pos: 'adj' },
    { id: 'es_people_8', deckId: 'es_people', en: 'orgulloso', pt: 'orgulhoso', exampleHtml: 'Estoy <b>orgulloso</b> de ti.', examplePt: 'Estou orgulhoso de você.', pos: 'adj' },
    { id: 'es_people_9', deckId: 'es_people', en: 'preocupado', pt: 'preocupado', exampleHtml: 'Está <b>preocupado</b> por su mamá.', examplePt: 'Está preocupado com a mãe dele.', pos: 'adj' },
    { id: 'es_people_10', deckId: 'es_people', en: 'enojado', pt: 'bravo', exampleHtml: 'Se puso <b>enojado</b> sin razón.', examplePt: 'Ficou bravo sem motivo.', pos: 'adj' },
    { id: 'es_people_11', deckId: 'es_people', en: 'apenado', pt: 'envergonhado', exampleHtml: 'Quedé <b>apenado</b> con ellos.', examplePt: 'Fiquei envergonhado com eles.', pos: 'adj' },
    { id: 'es_people_12', deckId: 'es_people', en: 'la pareja', pt: 'o casal / parceiro', exampleHtml: 'Vino con su <b>pareja</b> ayer.', examplePt: 'Veio com o parceiro dele ontem.', pos: 'noun' },
    { id: 'es_people_13', deckId: 'es_people', en: 'el cuñado', pt: 'o cunhado', exampleHtml: 'Mi <b>cuñado</b> vive en Lima.', examplePt: 'Meu cunhado mora em Lima.', pos: 'noun' },
    { id: 'es_people_14', deckId: 'es_people', en: 'el compañero', pt: 'o colega', exampleHtml: 'Es <b>compañero</b> de trabajo.', examplePt: 'É colega de trabalho.', pos: 'noun' },
    { id: 'es_people_15', deckId: 'es_people', en: 'caer bien', pt: 'ir com a cara', exampleHtml: 'Ella me <b>cae bien</b>, en serio.', examplePt: 'Eu vou com a cara dela, sério.', pos: 'verb' },
    { id: 'es_people_16', deckId: 'es_people', en: 'caer mal', pt: 'não ir com a cara', exampleHtml: 'Ese tipo me <b>cae mal</b>.', examplePt: 'Não vou com a cara desse cara.', pos: 'verb' },
    { id: 'es_people_17', deckId: 'es_people', en: 'hacer caso', pt: 'dar atenção / obedecer', exampleHtml: 'No me <b>hace caso</b> nunca.', examplePt: 'Ele nunca me dá atenção.', pos: 'verb' },
    { id: 'es_people_18', deckId: 'es_people', en: 'dar la razón', pt: 'dar razão', exampleHtml: 'Al final le <b>di la razón</b>.', examplePt: 'No fim dei razão a ele.', pos: 'phrase' },
    { id: 'es_people_19', deckId: 'es_people', en: 'estar de buenas', pt: 'estar de bom humor', exampleHtml: 'Hoy <b>está de buenas</b>.', examplePt: 'Hoje ele está de bom humor.', pos: 'phrase' },
  ],
}

export const ES_EVERYDAY_DECKS: Deck[] = [ES_STRUCTURE_DECK, ES_HOME_DECK, ES_PEOPLE_DECK]
