import type { Deck } from '../../types'

/** Working Spanish: the meeting, the inbox, and the money. */

export const ES_WORK_DECK: Deck = {
  id: 'es_work',
  name: 'Trabalho',
  emoji: '💼',
  desc: 'Reunião, prazo, entrega — o vocabulário que paga a conta',
  level: 2,
  cards: [
    { id: 'es_work_0', deckId: 'es_work', en: 'la reunión', pt: 'a reunião', exampleHtml: '<b>La reunión</b> es a las diez.', examplePt: 'A reunião é às dez.', pos: 'noun' },
    { id: 'es_work_1', deckId: 'es_work', en: 'el plazo', pt: 'o prazo', exampleHtml: 'El <b>plazo</b> vence el viernes.', examplePt: 'O prazo vence na sexta.', pos: 'noun' },
    { id: 'es_work_2', deckId: 'es_work', en: 'la entrega', pt: 'a entrega', exampleHtml: 'La <b>entrega</b> se atrasó dos días.', examplePt: 'A entrega atrasou dois dias.', pos: 'noun' },
    { id: 'es_work_3', deckId: 'es_work', en: 'el informe', pt: 'o relatório', exampleHtml: 'Terminé el <b>informe</b> anoche.', examplePt: 'Terminei o relatório ontem à noite.', pos: 'noun' },
    { id: 'es_work_4', deckId: 'es_work', en: 'el presupuesto', pt: 'o orçamento', exampleHtml: 'El <b>presupuesto</b> ya está aprobado.', examplePt: 'O orçamento já está aprovado.', pos: 'noun' },
    { id: 'es_work_5', deckId: 'es_work', en: 'la propuesta', pt: 'a proposta', exampleHtml: 'Enviamos la <b>propuesta</b> el lunes.', examplePt: 'Enviamos a proposta na segunda.', pos: 'noun' },
    { id: 'es_work_6', deckId: 'es_work', en: 'el socio', pt: 'o sócio', exampleHtml: 'Mi <b>socio</b> maneja las finanzas.', examplePt: 'Meu sócio cuida das finanças.', pos: 'noun' },
    { id: 'es_work_7', deckId: 'es_work', en: 'el proveedor', pt: 'o fornecedor', exampleHtml: 'Cambiamos de <b>proveedor</b> este año.', examplePt: 'Trocamos de fornecedor este ano.', pos: 'noun' },
    { id: 'es_work_8', deckId: 'es_work', en: 'el sueldo', pt: 'o salário', exampleHtml: 'El <b>sueldo</b> cae cada quincena.', examplePt: 'O salário cai a cada quinzena.', pos: 'noun' },
    { id: 'es_work_9', deckId: 'es_work', en: 'el jefe', pt: 'o chefe', exampleHtml: 'Mi <b>jefe</b> aprobó las vacaciones.', examplePt: 'Meu chefe aprovou as férias.', pos: 'noun' },
    { id: 'es_work_10', deckId: 'es_work', en: 'contratar', pt: 'contratar', exampleHtml: 'Vamos a <b>contratar</b> dos personas.', examplePt: 'Vamos contratar duas pessoas.', pos: 'verb' },
    { id: 'es_work_11', deckId: 'es_work', en: 'despedir', pt: 'demitir', exampleHtml: 'Tuvieron que <b>despedir</b> a varios.', examplePt: 'Tiveram que demitir vários.', pos: 'verb' },
    { id: 'es_work_12', deckId: 'es_work', en: 'renunciar', pt: 'pedir demissão', exampleHtml: 'Decidió <b>renunciar</b> el mes pasado.', examplePt: 'Decidiu pedir demissão mês passado.', pos: 'verb' },
    { id: 'es_work_13', deckId: 'es_work', en: 'agendar', pt: 'agendar', exampleHtml: 'Voy a <b>agendar</b> una llamada.', examplePt: 'Vou agendar uma ligação.', pos: 'verb' },
    { id: 'es_work_14', deckId: 'es_work', en: 'posponer', pt: 'adiar', exampleHtml: 'Tuvimos que <b>posponer</b> la junta.', examplePt: 'Tivemos que adiar a reunião.', pos: 'verb' },
    { id: 'es_work_15', deckId: 'es_work', en: 'adjuntar', pt: 'anexar', exampleHtml: 'Te <b>adjunto</b> el archivo aquí.', examplePt: 'Te anexo o arquivo aqui.', pos: 'verb' },
    { id: 'es_work_16', deckId: 'es_work', en: 'dar seguimiento', pt: 'dar andamento', exampleHtml: 'Voy a <b>dar seguimiento</b> mañana.', examplePt: 'Vou dar andamento amanhã.', pos: 'phrase' },
    { id: 'es_work_17', deckId: 'es_work', en: 'quedar en', pt: 'combinar de', exampleHtml: '<b>Quedamos en</b> vernos el jueves.', examplePt: 'Combinamos de nos ver na quinta.', pos: 'verb' },
    { id: 'es_work_18', deckId: 'es_work', en: 'ponerse al día', pt: 'colocar em dia', exampleHtml: 'Necesito <b>ponerme al día</b> hoy.', examplePt: 'Preciso me colocar em dia hoje.', pos: 'phrase' },
    { id: 'es_work_19', deckId: 'es_work', en: 'estar a cargo', pt: 'estar responsável', exampleHtml: 'Ella <b>está a cargo</b> del proyecto.', examplePt: 'Ela está responsável pelo projeto.', pos: 'phrase' },
    { id: 'es_work_20', deckId: 'es_work', en: 'a corto plazo', pt: 'a curto prazo', exampleHtml: 'Es una solución <b>a corto plazo</b>.', examplePt: 'É uma solução a curto prazo.', pos: 'phrase' },
    { id: 'es_work_21', deckId: 'es_work', en: 'a largo plazo', pt: 'a longo prazo', exampleHtml: 'Pensemos <b>a largo plazo</b> ahora.', examplePt: 'Vamos pensar a longo prazo agora.', pos: 'phrase' },
    { id: 'es_work_22', deckId: 'es_work', en: 'la junta', pt: 'a reunião (México)', exampleHtml: 'La <b>junta</b> duró tres horas.', examplePt: 'A reunião durou três horas.', pos: 'noun' },
    { id: 'es_work_23', deckId: 'es_work', en: 'el archivo', pt: 'o arquivo', exampleHtml: 'No encuentro ese <b>archivo</b>.', examplePt: 'Não encontro esse arquivo.', pos: 'noun' },
    { id: 'es_work_24', deckId: 'es_work', en: 'la factura', pt: 'a nota fiscal', exampleHtml: 'Todavía falta la <b>factura</b>.', examplePt: 'Ainda falta a nota fiscal.', pos: 'noun' },
    { id: 'es_work_25', deckId: 'es_work', en: 'el pedido', pt: 'o pedido', exampleHtml: 'El <b>pedido</b> llega el martes.', examplePt: 'O pedido chega na terça.', pos: 'noun' },
    { id: 'es_work_26', deckId: 'es_work', en: 'la meta', pt: 'a meta', exampleHtml: 'Cumplimos la <b>meta</b> del mes.', examplePt: 'Cumprimos a meta do mês.', pos: 'noun' },
    { id: 'es_work_27', deckId: 'es_work', en: 'el logro', pt: 'a conquista', exampleHtml: 'Ese fue un gran <b>logro</b>.', examplePt: 'Essa foi uma grande conquista.', pos: 'noun' },
    { id: 'es_work_28', deckId: 'es_work', en: 'la marca', pt: 'a marca', exampleHtml: 'La <b>marca</b> creció mucho.', examplePt: 'A marca cresceu muito.', pos: 'noun' },
    { id: 'es_work_29', deckId: 'es_work', en: 'la campaña', pt: 'a campanha', exampleHtml: 'La <b>campaña</b> empieza en mayo.', examplePt: 'A campanha começa em maio.', pos: 'noun' },
    { id: 'es_work_30', deckId: 'es_work', en: 'el alcance', pt: 'o alcance', exampleHtml: 'El <b>alcance</b> superó lo esperado.', examplePt: 'O alcance superou o esperado.', pos: 'noun' },
    { id: 'es_work_31', deckId: 'es_work', en: 'la encuesta', pt: 'a pesquisa', exampleHtml: 'La <b>encuesta</b> cerró ayer.', examplePt: 'A pesquisa fechou ontem.', pos: 'noun' },
    { id: 'es_work_32', deckId: 'es_work', en: 'el aumento', pt: 'o aumento', exampleHtml: 'Pedí un <b>aumento</b> de sueldo.', examplePt: 'Pedi um aumento de salário.', pos: 'noun' },
    { id: 'es_work_33', deckId: 'es_work', en: 'la capacitación', pt: 'o treinamento', exampleHtml: 'La <b>capacitación</b> es obligatoria.', examplePt: 'O treinamento é obrigatório.', pos: 'noun' },
    { id: 'es_work_34', deckId: 'es_work', en: 'al pendiente', pt: 'atento / de olho', exampleHtml: 'Estoy <b>al pendiente</b> del correo.', examplePt: 'Estou de olho no e-mail.', pos: 'phrase' },
    { id: 'es_work_35', deckId: 'es_work', en: 'de antemano', pt: 'desde já', exampleHtml: 'Gracias <b>de antemano</b> por todo.', examplePt: 'Obrigado desde já por tudo.', pos: 'phrase' },
    { id: 'es_work_36', deckId: 'es_work', en: 'a la brevedad', pt: 'o quanto antes', exampleHtml: 'Respondo <b>a la brevedad</b> posible.', examplePt: 'Respondo o quanto antes possível.', pos: 'phrase' },
    { id: 'es_work_37', deckId: 'es_work', en: 'quedo atento', pt: 'fico no aguardo', exampleHtml: '<b>Quedo atento</b> a tus comentarios.', examplePt: 'Fico no aguardo dos seus comentários.', pos: 'phrase' },
    { id: 'es_work_38', deckId: 'es_work', en: 'saludos', pt: 'abraços (e-mail)', exampleHtml: '<b>Saludos</b> y buen fin de semana.', examplePt: 'Abraços e bom fim de semana.', pos: 'noun' },
    { id: 'es_work_39', deckId: 'es_work', en: 'la cotización', pt: 'o orçamento (cotação)', exampleHtml: '¿Ya enviaste la <b>cotización</b>?', examplePt: 'Você já enviou a cotação?', pos: 'noun' },
  ],
}

export const ES_TRAVEL_DECK: Deck = {
  id: 'es_travel',
  name: 'Viagem e serviços',
  emoji: '✈️',
  desc: 'Restaurante, hotel, transporte, farmácia — resolver as coisas',
  level: 1,
  cards: [
    { id: 'es_travel_0', deckId: 'es_travel', en: 'la cuenta', pt: 'a conta', exampleHtml: '¿Me trae <b>la cuenta</b>, por favor?', examplePt: 'Pode trazer a conta, por favor?', pos: 'noun' },
    { id: 'es_travel_1', deckId: 'es_travel', en: 'la propina', pt: 'a gorjeta', exampleHtml: '¿La <b>propina</b> ya está incluida?', examplePt: 'A gorjeta já está incluída?', pos: 'noun' },
    { id: 'es_travel_2', deckId: 'es_travel', en: 'reservar', pt: 'reservar', exampleHtml: 'Quiero <b>reservar</b> una mesa.', examplePt: 'Quero reservar uma mesa.', pos: 'verb' },
    { id: 'es_travel_3', deckId: 'es_travel', en: 'la habitación', pt: 'o quarto', exampleHtml: 'La <b>habitación</b> tiene dos camas.', examplePt: 'O quarto tem duas camas.', pos: 'noun' },
    { id: 'es_travel_4', deckId: 'es_travel', en: 'el mostrador', pt: 'o balcão', exampleHtml: 'Pregunta en el <b>mostrador</b>.', examplePt: 'Pergunta no balcão.', pos: 'noun' },
    { id: 'es_travel_5', deckId: 'es_travel', en: 'el boleto', pt: 'a passagem', exampleHtml: 'Compré el <b>boleto</b> por internet.', examplePt: 'Comprei a passagem pela internet.', pos: 'noun' },
    { id: 'es_travel_6', deckId: 'es_travel', en: 'el vuelo', pt: 'o voo', exampleHtml: 'El <b>vuelo</b> sale a las seis.', examplePt: 'O voo sai às seis.', pos: 'noun' },
    { id: 'es_travel_7', deckId: 'es_travel', en: 'el retraso', pt: 'o atraso', exampleHtml: 'Hubo un <b>retraso</b> de una hora.', examplePt: 'Houve um atraso de uma hora.', pos: 'noun' },
    { id: 'es_travel_8', deckId: 'es_travel', en: 'aterrizar', pt: 'aterrissar', exampleHtml: 'El avión acaba de <b>aterrizar</b>.', examplePt: 'O avião acabou de aterrissar.', pos: 'verb' },
    { id: 'es_travel_9', deckId: 'es_travel', en: 'la parada', pt: 'o ponto (ônibus)', exampleHtml: 'Bájate en la próxima <b>parada</b>.', examplePt: 'Desce no próximo ponto.', pos: 'noun' },
    { id: 'es_travel_10', deckId: 'es_travel', en: 'el andén', pt: 'a plataforma', exampleHtml: 'El tren sale del <b>andén</b> tres.', examplePt: 'O trem sai da plataforma três.', pos: 'noun' },
    { id: 'es_travel_11', deckId: 'es_travel', en: 'la sucursal', pt: 'a agência / filial', exampleHtml: 'Hay una <b>sucursal</b> cerca de aquí.', examplePt: 'Tem uma agência perto daqui.', pos: 'noun' },
    { id: 'es_travel_12', deckId: 'es_travel', en: 'la receta', pt: 'a receita médica', exampleHtml: 'Necesito una <b>receta</b> para esto.', examplePt: 'Preciso de uma receita para isso.', pos: 'noun' },
    { id: 'es_travel_13', deckId: 'es_travel', en: 'la farmacia', pt: 'a farmácia', exampleHtml: '¿Dónde hay una <b>farmacia</b>?', examplePt: 'Onde tem uma farmácia?', pos: 'noun' },
    { id: 'es_travel_14', deckId: 'es_travel', en: 'el seguro', pt: 'o seguro', exampleHtml: 'Mi <b>seguro</b> cubre la consulta.', examplePt: 'Meu seguro cobre a consulta.', pos: 'noun' },
    { id: 'es_travel_15', deckId: 'es_travel', en: 'la cita', pt: 'a consulta / o encontro', exampleHtml: 'Tengo <b>cita</b> con el doctor.', examplePt: 'Tenho consulta com o médico.', pos: 'noun' },
    { id: 'es_travel_16', deckId: 'es_travel', en: 'me duele', pt: 'está doendo (em mim)', exampleHtml: '<b>Me duele</b> mucho la cabeza.', examplePt: 'Minha cabeça está doendo muito.', pos: 'phrase' },
    { id: 'es_travel_17', deckId: 'es_travel', en: 'el probador', pt: 'o provador', exampleHtml: '¿Dónde está el <b>probador</b>?', examplePt: 'Onde fica o provador?', pos: 'noun' },
    { id: 'es_travel_18', deckId: 'es_travel', en: 'la talla', pt: 'o tamanho (roupa)', exampleHtml: '¿Tienen una <b>talla</b> más grande?', examplePt: 'Vocês têm um tamanho maior?', pos: 'noun' },
    { id: 'es_travel_19', deckId: 'es_travel', en: 'el descuento', pt: 'o desconto', exampleHtml: '¿Hay algún <b>descuento</b> hoy?', examplePt: 'Tem algum desconto hoje?', pos: 'noun' },
    { id: 'es_travel_20', deckId: 'es_travel', en: 'devolver', pt: 'devolver', exampleHtml: 'Quiero <b>devolver</b> esta camisa.', examplePt: 'Quero devolver esta camisa.', pos: 'verb' },
    { id: 'es_travel_21', deckId: 'es_travel', en: 'el recibo', pt: 'o recibo', exampleHtml: '¿Me da el <b>recibo</b>, por favor?', examplePt: 'Pode me dar o recibo, por favor?', pos: 'noun' },
    { id: 'es_travel_22', deckId: 'es_travel', en: 'en efectivo', pt: 'em dinheiro', exampleHtml: '¿Puedo pagar <b>en efectivo</b>?', examplePt: 'Posso pagar em dinheiro?', pos: 'phrase' },
    { id: 'es_travel_23', deckId: 'es_travel', en: 'con tarjeta', pt: 'no cartão', exampleHtml: 'Prefiero pagar <b>con tarjeta</b>.', examplePt: 'Prefiro pagar no cartão.', pos: 'phrase' },
    { id: 'es_travel_24', deckId: 'es_travel', en: 'la llave', pt: 'a chave', exampleHtml: 'Perdí la <b>llave</b> del cuarto.', examplePt: 'Perdi a chave do quarto.', pos: 'noun' },
    { id: 'es_travel_25', deckId: 'es_travel', en: 'el equipaje', pt: 'a bagagem', exampleHtml: 'Mi <b>equipaje</b> no llegó.', examplePt: 'Minha bagagem não chegou.', pos: 'noun' },
    { id: 'es_travel_26', deckId: 'es_travel', en: 'la aduana', pt: 'a alfândega', exampleHtml: 'Pasamos por la <b>aduana</b> rápido.', examplePt: 'Passamos pela alfândega rápido.', pos: 'noun' },
    { id: 'es_travel_27', deckId: 'es_travel', en: 'a la vuelta', pt: 'na esquina / virando', exampleHtml: 'El café está <b>a la vuelta</b>.', examplePt: 'O café está logo virando.', pos: 'phrase' },
    { id: 'es_travel_28', deckId: 'es_travel', en: 'derecho', pt: 'reto (direção)', exampleHtml: 'Sigue <b>derecho</b> dos cuadras.', examplePt: 'Siga reto duas quadras.', pos: 'adj' },
    { id: 'es_travel_29', deckId: 'es_travel', en: 'la cuadra', pt: 'o quarteirão', exampleHtml: 'Está a tres <b>cuadras</b> de aquí.', examplePt: 'Fica a três quarteirões daqui.', pos: 'noun' },
    { id: 'es_travel_30', deckId: 'es_travel', en: 'a domicilio', pt: 'em domicílio / delivery', exampleHtml: '¿Hacen entrega <b>a domicilio</b>?', examplePt: 'Vocês fazem entrega em domicílio?', pos: 'phrase' },
    { id: 'es_travel_31', deckId: 'es_travel', en: 'para llevar', pt: 'para viagem', exampleHtml: 'Un café <b>para llevar</b>, por favor.', examplePt: 'Um café para viagem, por favor.', pos: 'phrase' },
    { id: 'es_travel_32', deckId: 'es_travel', en: 'está ocupado', pt: 'está ocupado', exampleHtml: 'El baño <b>está ocupado</b> ahora.', examplePt: 'O banheiro está ocupado agora.', pos: 'phrase' },
    { id: 'es_travel_33', deckId: 'es_travel', en: 'me perdí', pt: 'me perdi', exampleHtml: 'Creo que <b>me perdí</b> aquí.', examplePt: 'Acho que me perdi aqui.', pos: 'phrase' },
    { id: 'es_travel_34', deckId: 'es_travel', en: 'la playa', pt: 'a praia', exampleHtml: 'Vamos a la <b>playa</b> el domingo.', examplePt: 'Vamos à praia no domingo.', pos: 'noun' },
  ],
}

export const ES_WORK_DECKS: Deck[] = [ES_WORK_DECK, ES_TRAVEL_DECK]
