// GENERATED by scripts/extract-content.mjs — DO NOT EDIT BY HAND.
import type { Deck } from '../types'

export const GENERATED_DECKS: Deck[] = [
 {
  "id": "survival",
  "name": "First words & courtesy",
  "emoji": "👋",
  "desc": "Greetings, please, thank you, yes/no",
  "level": 1,
  "cards": [
   {
    "id": "survival_0",
    "deckId": "survival",
    "en": "Hello",
    "pt": "Olá",
    "exampleHtml": "<b>Hello</b>, how are you?",
    "examplePt": "Olá, como você está?",
    "pos": "greeting"
   },
   {
    "id": "survival_1",
    "deckId": "survival",
    "en": "Hi",
    "pt": "Oi",
    "exampleHtml": "<b>Hi</b>! Nice to meet you.",
    "examplePt": "Oi! Prazer em conhecer.",
    "pos": "greeting"
   },
   {
    "id": "survival_2",
    "deckId": "survival",
    "en": "Good morning",
    "pt": "Bom dia",
    "exampleHtml": "<b>Good morning</b>, everyone.",
    "examplePt": "Bom dia a todos.",
    "pos": "phrase"
   },
   {
    "id": "survival_3",
    "deckId": "survival",
    "en": "Good afternoon",
    "pt": "Boa tarde",
    "exampleHtml": "<b>Good afternoon</b>, sir.",
    "examplePt": "Boa tarde, senhor.",
    "pos": "phrase"
   },
   {
    "id": "survival_4",
    "deckId": "survival",
    "en": "Good evening",
    "pt": "Boa noite (chegada)",
    "exampleHtml": "<b>Good evening</b>, table for two?",
    "examplePt": "Boa noite, mesa para dois?",
    "pos": "phrase"
   },
   {
    "id": "survival_5",
    "deckId": "survival",
    "en": "Goodbye",
    "pt": "Tchau / adeus",
    "exampleHtml": "<b>Goodbye</b>, see you tomorrow.",
    "examplePt": "Tchau, até amanhã.",
    "pos": "phrase"
   },
   {
    "id": "survival_6",
    "deckId": "survival",
    "en": "Please",
    "pt": "Por favor",
    "exampleHtml": "A coffee, <b>please</b>.",
    "examplePt": "Um café, por favor.",
    "pos": "word"
   },
   {
    "id": "survival_7",
    "deckId": "survival",
    "en": "Thank you",
    "pt": "Obrigada",
    "exampleHtml": "<b>Thank you</b> so much!",
    "examplePt": "Muito obrigada!",
    "pos": "phrase"
   },
   {
    "id": "survival_8",
    "deckId": "survival",
    "en": "You're welcome",
    "pt": "De nada",
    "exampleHtml": "“Thanks!” — “<b>You're welcome</b>.”",
    "examplePt": "“Valeu!” — “De nada.”",
    "pos": "phrase"
   },
   {
    "id": "survival_9",
    "deckId": "survival",
    "en": "Sorry",
    "pt": "Desculpa",
    "exampleHtml": "<b>Sorry</b>, I didn't hear you.",
    "examplePt": "Desculpa, não te ouvi.",
    "pos": "word"
   },
   {
    "id": "survival_10",
    "deckId": "survival",
    "en": "Excuse me",
    "pt": "Com licença / desculpe",
    "exampleHtml": "<b>Excuse me</b>, where is the toilet?",
    "examplePt": "Com licença, onde fica o banheiro?",
    "pos": "phrase"
   },
   {
    "id": "survival_11",
    "deckId": "survival",
    "en": "Yes",
    "pt": "Sim",
    "exampleHtml": "<b>Yes</b>, please.",
    "examplePt": "Sim, por favor.",
    "pos": "word"
   },
   {
    "id": "survival_12",
    "deckId": "survival",
    "en": "No",
    "pt": "Não",
    "exampleHtml": "<b>No</b>, thank you.",
    "examplePt": "Não, obrigada.",
    "pos": "word"
   },
   {
    "id": "survival_13",
    "deckId": "survival",
    "en": "Maybe",
    "pt": "Talvez",
    "exampleHtml": "<b>Maybe</b> later.",
    "examplePt": "Talvez mais tarde.",
    "pos": "word"
   },
   {
    "id": "survival_14",
    "deckId": "survival",
    "en": "My name is…",
    "pt": "Meu nome é…",
    "exampleHtml": "<b>My name is</b> Ana.",
    "examplePt": "Meu nome é Ana.",
    "pos": "phrase"
   },
   {
    "id": "survival_15",
    "deckId": "survival",
    "en": "Nice to meet you",
    "pt": "Prazer em conhecer",
    "exampleHtml": "<b>Nice to meet you</b>, John.",
    "examplePt": "Prazer em conhecer, John.",
    "pos": "phrase"
   },
   {
    "id": "survival_16",
    "deckId": "survival",
    "en": "How are you?",
    "pt": "Como você está?",
    "exampleHtml": "Hi! <b>How are you?</b>",
    "examplePt": "Oi! Como você está?",
    "pos": "phrase"
   },
   {
    "id": "survival_17",
    "deckId": "survival",
    "en": "I'm good, thanks",
    "pt": "Estou bem, obrigada",
    "exampleHtml": "<b>I'm good, thanks</b>. And you?",
    "examplePt": "Estou bem, obrigada. E você?",
    "pos": "phrase"
   },
   {
    "id": "survival_18",
    "deckId": "survival",
    "en": "I don't understand",
    "pt": "Eu não entendo",
    "exampleHtml": "Sorry, <b>I don't understand</b>.",
    "examplePt": "Desculpa, eu não entendo.",
    "pos": "phrase"
   },
   {
    "id": "survival_19",
    "deckId": "survival",
    "en": "Can you repeat, please?",
    "pt": "Pode repetir, por favor?",
    "exampleHtml": "<b>Can you repeat, please?</b>",
    "examplePt": "Pode repetir, por favor?",
    "pos": "phrase"
   },
   {
    "id": "survival_20",
    "deckId": "survival",
    "en": "Can you speak slowly?",
    "pt": "Pode falar devagar?",
    "exampleHtml": "<b>Can you speak slowly, please?</b>",
    "examplePt": "Pode falar devagar, por favor?",
    "pos": "phrase"
   },
   {
    "id": "survival_21",
    "deckId": "survival",
    "en": "I'm from Brazil",
    "pt": "Eu sou do Brasil",
    "exampleHtml": "Hi, <b>I'm from Brazil</b>.",
    "examplePt": "Oi, eu sou do Brasil.",
    "pos": "phrase"
   }
  ]
 },
 {
  "id": "numbers",
  "name": "Numbers, time & days",
  "emoji": "🔢",
  "desc": "Count, tell time, days of the week",
  "level": 1,
  "cards": [
   {
    "id": "numbers_0",
    "deckId": "numbers",
    "en": "One",
    "pt": "Um",
    "exampleHtml": "I have <b>one</b> brother.",
    "examplePt": "Eu tenho um irmão.",
    "pos": "number"
   },
   {
    "id": "numbers_1",
    "deckId": "numbers",
    "en": "Two",
    "pt": "Dois",
    "exampleHtml": "<b>Two</b> coffees, please.",
    "examplePt": "Dois cafés, por favor.",
    "pos": "number"
   },
   {
    "id": "numbers_2",
    "deckId": "numbers",
    "en": "Three",
    "pt": "Três",
    "exampleHtml": "<b>Three</b> tickets.",
    "examplePt": "Três ingressos.",
    "pos": "number"
   },
   {
    "id": "numbers_3",
    "deckId": "numbers",
    "en": "Four",
    "pt": "Quatro",
    "exampleHtml": "<b>Four</b> people.",
    "examplePt": "Quatro pessoas.",
    "pos": "number"
   },
   {
    "id": "numbers_4",
    "deckId": "numbers",
    "en": "Five",
    "pt": "Cinco",
    "exampleHtml": "It's <b>five</b> dollars.",
    "examplePt": "São cinco dólares.",
    "pos": "number"
   },
   {
    "id": "numbers_5",
    "deckId": "numbers",
    "en": "Ten",
    "pt": "Dez",
    "exampleHtml": "<b>Ten</b> minutes.",
    "examplePt": "Dez minutos.",
    "pos": "number"
   },
   {
    "id": "numbers_6",
    "deckId": "numbers",
    "en": "Twenty",
    "pt": "Vinte",
    "exampleHtml": "<b>Twenty</b> dollars.",
    "examplePt": "Vinte dólares.",
    "pos": "number"
   },
   {
    "id": "numbers_7",
    "deckId": "numbers",
    "en": "Hundred",
    "pt": "Cem",
    "exampleHtml": "One <b>hundred</b> people.",
    "examplePt": "Cem pessoas.",
    "pos": "number"
   },
   {
    "id": "numbers_8",
    "deckId": "numbers",
    "en": "First",
    "pt": "Primeiro",
    "exampleHtml": "The <b>first</b> door.",
    "examplePt": "A primeira porta.",
    "pos": "word"
   },
   {
    "id": "numbers_9",
    "deckId": "numbers",
    "en": "Today",
    "pt": "Hoje",
    "exampleHtml": "<b>Today</b> is Monday.",
    "examplePt": "Hoje é segunda.",
    "pos": "word"
   },
   {
    "id": "numbers_10",
    "deckId": "numbers",
    "en": "Tomorrow",
    "pt": "Amanhã",
    "exampleHtml": "See you <b>tomorrow</b>.",
    "examplePt": "Até amanhã.",
    "pos": "word"
   },
   {
    "id": "numbers_11",
    "deckId": "numbers",
    "en": "Yesterday",
    "pt": "Ontem",
    "exampleHtml": "I arrived <b>yesterday</b>.",
    "examplePt": "Cheguei ontem.",
    "pos": "word"
   },
   {
    "id": "numbers_12",
    "deckId": "numbers",
    "en": "Now",
    "pt": "Agora",
    "exampleHtml": "I need it <b>now</b>.",
    "examplePt": "Preciso disso agora.",
    "pos": "word"
   },
   {
    "id": "numbers_13",
    "deckId": "numbers",
    "en": "What time is it?",
    "pt": "Que horas são?",
    "exampleHtml": "Excuse me, <b>what time is it?</b>",
    "examplePt": "Com licença, que horas são?",
    "pos": "phrase"
   },
   {
    "id": "numbers_14",
    "deckId": "numbers",
    "en": "It's half past two",
    "pt": "São duas e meia",
    "exampleHtml": "<b>It's half past two.</b>",
    "examplePt": "São duas e meia.",
    "pos": "phrase"
   },
   {
    "id": "numbers_15",
    "deckId": "numbers",
    "en": "Morning",
    "pt": "Manhã",
    "exampleHtml": "In the <b>morning</b>.",
    "examplePt": "De manhã.",
    "pos": "word"
   },
   {
    "id": "numbers_16",
    "deckId": "numbers",
    "en": "Afternoon",
    "pt": "Tarde",
    "exampleHtml": "This <b>afternoon</b>.",
    "examplePt": "Esta tarde.",
    "pos": "word"
   },
   {
    "id": "numbers_17",
    "deckId": "numbers",
    "en": "Night",
    "pt": "Noite",
    "exampleHtml": "At <b>night</b>.",
    "examplePt": "À noite.",
    "pos": "word"
   },
   {
    "id": "numbers_18",
    "deckId": "numbers",
    "en": "Monday",
    "pt": "Segunda-feira",
    "exampleHtml": "See you on <b>Monday</b>.",
    "examplePt": "Até segunda.",
    "pos": "word"
   },
   {
    "id": "numbers_19",
    "deckId": "numbers",
    "en": "Friday",
    "pt": "Sexta-feira",
    "exampleHtml": "<b>Friday</b> is my day off.",
    "examplePt": "Sexta é minha folga.",
    "pos": "word"
   },
   {
    "id": "numbers_20",
    "deckId": "numbers",
    "en": "Weekend",
    "pt": "Fim de semana",
    "exampleHtml": "Have a good <b>weekend</b>!",
    "examplePt": "Bom fim de semana!",
    "pos": "word"
   },
   {
    "id": "numbers_21",
    "deckId": "numbers",
    "en": "Week",
    "pt": "Semana",
    "exampleHtml": "Next <b>week</b>.",
    "examplePt": "Semana que vem.",
    "pos": "word"
   }
  ]
 },
 {
  "id": "verbs",
  "name": "Everyday verbs",
  "emoji": "🏃",
  "desc": "The action words you'll use daily",
  "level": 1,
  "cards": [
   {
    "id": "verbs_0",
    "deckId": "verbs",
    "en": "to be",
    "pt": "ser / estar",
    "exampleHtml": "I <b>am</b> tired.",
    "examplePt": "Estou cansada.",
    "pos": "verb"
   },
   {
    "id": "verbs_1",
    "deckId": "verbs",
    "en": "to have",
    "pt": "ter",
    "exampleHtml": "I <b>have</b> a question.",
    "examplePt": "Eu tenho uma pergunta.",
    "pos": "verb"
   },
   {
    "id": "verbs_2",
    "deckId": "verbs",
    "en": "to want",
    "pt": "querer",
    "exampleHtml": "I <b>want</b> a coffee.",
    "examplePt": "Eu quero um café.",
    "pos": "verb"
   },
   {
    "id": "verbs_3",
    "deckId": "verbs",
    "en": "to need",
    "pt": "precisar",
    "exampleHtml": "I <b>need</b> help.",
    "examplePt": "Eu preciso de ajuda.",
    "pos": "verb"
   },
   {
    "id": "verbs_4",
    "deckId": "verbs",
    "en": "to go",
    "pt": "ir",
    "exampleHtml": "I <b>go</b> to work.",
    "examplePt": "Eu vou ao trabalho.",
    "pos": "verb"
   },
   {
    "id": "verbs_5",
    "deckId": "verbs",
    "en": "to come",
    "pt": "vir",
    "exampleHtml": "<b>Come</b> here, please.",
    "examplePt": "Venha aqui, por favor.",
    "pos": "verb"
   },
   {
    "id": "verbs_6",
    "deckId": "verbs",
    "en": "to eat",
    "pt": "comer",
    "exampleHtml": "Let's <b>eat</b>.",
    "examplePt": "Vamos comer.",
    "pos": "verb"
   },
   {
    "id": "verbs_7",
    "deckId": "verbs",
    "en": "to drink",
    "pt": "beber",
    "exampleHtml": "I want to <b>drink</b> water.",
    "examplePt": "Quero beber água.",
    "pos": "verb"
   },
   {
    "id": "verbs_8",
    "deckId": "verbs",
    "en": "to buy",
    "pt": "comprar",
    "exampleHtml": "I want to <b>buy</b> this.",
    "examplePt": "Quero comprar isto.",
    "pos": "verb"
   },
   {
    "id": "verbs_9",
    "deckId": "verbs",
    "en": "to pay",
    "pt": "pagar",
    "exampleHtml": "Can I <b>pay</b> by card?",
    "examplePt": "Posso pagar no cartão?",
    "pos": "verb"
   },
   {
    "id": "verbs_10",
    "deckId": "verbs",
    "en": "to work",
    "pt": "trabalhar",
    "exampleHtml": "I <b>work</b> in a shop.",
    "examplePt": "Eu trabalho numa loja.",
    "pos": "verb"
   },
   {
    "id": "verbs_11",
    "deckId": "verbs",
    "en": "to live",
    "pt": "morar / viver",
    "exampleHtml": "I <b>live</b> in Auckland.",
    "examplePt": "Eu moro em Auckland.",
    "pos": "verb"
   },
   {
    "id": "verbs_12",
    "deckId": "verbs",
    "en": "to speak",
    "pt": "falar",
    "exampleHtml": "I <b>speak</b> a little English.",
    "examplePt": "Eu falo um pouco de inglês.",
    "pos": "verb"
   },
   {
    "id": "verbs_13",
    "deckId": "verbs",
    "en": "to know",
    "pt": "saber / conhecer",
    "exampleHtml": "I don't <b>know</b>.",
    "examplePt": "Eu não sei.",
    "pos": "verb"
   },
   {
    "id": "verbs_14",
    "deckId": "verbs",
    "en": "to like",
    "pt": "gostar",
    "exampleHtml": "I <b>like</b> it.",
    "examplePt": "Eu gosto disso.",
    "pos": "verb"
   },
   {
    "id": "verbs_15",
    "deckId": "verbs",
    "en": "to help",
    "pt": "ajudar",
    "exampleHtml": "Can you <b>help</b> me?",
    "examplePt": "Você pode me ajudar?",
    "pos": "verb"
   },
   {
    "id": "verbs_16",
    "deckId": "verbs",
    "en": "to open",
    "pt": "abrir",
    "exampleHtml": "Can you <b>open</b> the door?",
    "examplePt": "Pode abrir a porta?",
    "pos": "verb"
   },
   {
    "id": "verbs_17",
    "deckId": "verbs",
    "en": "to close",
    "pt": "fechar",
    "exampleHtml": "Please <b>close</b> the window.",
    "examplePt": "Por favor feche a janela.",
    "pos": "verb"
   },
   {
    "id": "verbs_18",
    "deckId": "verbs",
    "en": "to wait",
    "pt": "esperar",
    "exampleHtml": "Please <b>wait</b> here.",
    "examplePt": "Por favor espere aqui.",
    "pos": "verb"
   },
   {
    "id": "verbs_19",
    "deckId": "verbs",
    "en": "to find",
    "pt": "encontrar",
    "exampleHtml": "I can't <b>find</b> it.",
    "examplePt": "Não consigo encontrar.",
    "pos": "verb"
   },
   {
    "id": "verbs_20",
    "deckId": "verbs",
    "en": "to look for",
    "pt": "procurar",
    "exampleHtml": "I'm <b>looking for</b> the bus stop.",
    "examplePt": "Estou procurando o ponto de ônibus.",
    "pos": "verb"
   },
   {
    "id": "verbs_21",
    "deckId": "verbs",
    "en": "to understand",
    "pt": "entender",
    "exampleHtml": "Do you <b>understand</b>?",
    "examplePt": "Você entende?",
    "pos": "verb"
   }
  ]
 },
 {
  "id": "people",
  "name": "People & family",
  "emoji": "👨‍👩‍👧",
  "desc": "Talk about who's who",
  "level": 1,
  "cards": [
   {
    "id": "people_0",
    "deckId": "people",
    "en": "Husband",
    "pt": "Marido",
    "exampleHtml": "This is my <b>husband</b>.",
    "examplePt": "Este é meu marido.",
    "pos": "noun"
   },
   {
    "id": "people_1",
    "deckId": "people",
    "en": "Wife",
    "pt": "Esposa",
    "exampleHtml": "She is my <b>wife</b>.",
    "examplePt": "Ela é minha esposa.",
    "pos": "noun"
   },
   {
    "id": "people_2",
    "deckId": "people",
    "en": "Child",
    "pt": "Criança / filho(a)",
    "exampleHtml": "We have one <b>child</b>.",
    "examplePt": "Temos um filho.",
    "pos": "noun"
   },
   {
    "id": "people_3",
    "deckId": "people",
    "en": "Children",
    "pt": "Crianças / filhos",
    "exampleHtml": "We have two <b>children</b>.",
    "examplePt": "Temos dois filhos.",
    "pos": "noun"
   },
   {
    "id": "people_4",
    "deckId": "people",
    "en": "Mother",
    "pt": "Mãe",
    "exampleHtml": "My <b>mother</b> lives in Brazil.",
    "examplePt": "Minha mãe mora no Brasil.",
    "pos": "noun"
   },
   {
    "id": "people_5",
    "deckId": "people",
    "en": "Father",
    "pt": "Pai",
    "exampleHtml": "My <b>father</b> is a teacher.",
    "examplePt": "Meu pai é professor.",
    "pos": "noun"
   },
   {
    "id": "people_6",
    "deckId": "people",
    "en": "Friend",
    "pt": "Amigo(a)",
    "exampleHtml": "She is my <b>friend</b>.",
    "examplePt": "Ela é minha amiga.",
    "pos": "noun"
   },
   {
    "id": "people_7",
    "deckId": "people",
    "en": "Neighbour",
    "pt": "Vizinho(a)",
    "exampleHtml": "Our <b>neighbour</b> is kind.",
    "examplePt": "Nosso vizinho é gentil.",
    "pos": "noun"
   },
   {
    "id": "people_8",
    "deckId": "people",
    "en": "Man",
    "pt": "Homem",
    "exampleHtml": "That <b>man</b> works here.",
    "examplePt": "Aquele homem trabalha aqui.",
    "pos": "noun"
   },
   {
    "id": "people_9",
    "deckId": "people",
    "en": "Woman",
    "pt": "Mulher",
    "exampleHtml": "The <b>woman</b> at the desk.",
    "examplePt": "A mulher no balcão.",
    "pos": "noun"
   },
   {
    "id": "people_10",
    "deckId": "people",
    "en": "Boy",
    "pt": "Menino",
    "exampleHtml": "The little <b>boy</b>.",
    "examplePt": "O menininho.",
    "pos": "noun"
   },
   {
    "id": "people_11",
    "deckId": "people",
    "en": "Girl",
    "pt": "Menina",
    "exampleHtml": "The little <b>girl</b>.",
    "examplePt": "A menininha.",
    "pos": "noun"
   },
   {
    "id": "people_12",
    "deckId": "people",
    "en": "Everyone",
    "pt": "Todo mundo",
    "exampleHtml": "<b>Everyone</b> is here.",
    "examplePt": "Todo mundo está aqui.",
    "pos": "word"
   },
   {
    "id": "people_13",
    "deckId": "people",
    "en": "Together",
    "pt": "Juntos",
    "exampleHtml": "We are moving <b>together</b>.",
    "examplePt": "Nós vamos juntos.",
    "pos": "word"
   },
   {
    "id": "people_14",
    "deckId": "people",
    "en": "He / She",
    "pt": "Ele / Ela",
    "exampleHtml": "<b>He</b> is my brother; <b>she</b> is my sister.",
    "examplePt": "Ele é meu irmão; ela é minha irmã.",
    "pos": "word"
   },
   {
    "id": "people_15",
    "deckId": "people",
    "en": "We",
    "pt": "Nós",
    "exampleHtml": "<b>We</b> live in New Zealand.",
    "examplePt": "Nós moramos na Nova Zelândia.",
    "pos": "word"
   }
  ]
 },
 {
  "id": "food",
  "name": "Café & restaurant",
  "emoji": "☕",
  "desc": "Order food and drinks like a local",
  "level": 2,
  "cards": [
   {
    "id": "food_0",
    "deckId": "food",
    "en": "Water",
    "pt": "Água",
    "exampleHtml": "Can I have some <b>water</b>?",
    "examplePt": "Pode me dar água?",
    "pos": "noun"
   },
   {
    "id": "food_1",
    "deckId": "food",
    "en": "Coffee",
    "pt": "Café",
    "exampleHtml": "A flat white is a NZ <b>coffee</b>.",
    "examplePt": "Flat white é um café típico da NZ.",
    "pos": "noun"
   },
   {
    "id": "food_2",
    "deckId": "food",
    "en": "Flat white",
    "pt": "Café com leite cremoso (típico NZ)",
    "exampleHtml": "I'll have a <b>flat white</b>, thanks.",
    "examplePt": "Vou querer um flat white, obrigada.",
    "pos": "noun"
   },
   {
    "id": "food_3",
    "deckId": "food",
    "en": "Tea",
    "pt": "Chá",
    "exampleHtml": "A cup of <b>tea</b>, please.",
    "examplePt": "Uma xícara de chá, por favor.",
    "pos": "noun"
   },
   {
    "id": "food_4",
    "deckId": "food",
    "en": "Bread",
    "pt": "Pão",
    "exampleHtml": "Fresh <b>bread</b>.",
    "examplePt": "Pão fresco.",
    "pos": "noun"
   },
   {
    "id": "food_5",
    "deckId": "food",
    "en": "Breakfast",
    "pt": "Café da manhã",
    "exampleHtml": "<b>Breakfast</b> is at 8.",
    "examplePt": "O café da manhã é às 8.",
    "pos": "noun"
   },
   {
    "id": "food_6",
    "deckId": "food",
    "en": "Lunch",
    "pt": "Almoço",
    "exampleHtml": "Let's have <b>lunch</b>.",
    "examplePt": "Vamos almoçar.",
    "pos": "noun"
   },
   {
    "id": "food_7",
    "deckId": "food",
    "en": "Dinner",
    "pt": "Jantar",
    "exampleHtml": "<b>Dinner</b> is ready.",
    "examplePt": "O jantar está pronto.",
    "pos": "noun"
   },
   {
    "id": "food_8",
    "deckId": "food",
    "en": "Menu",
    "pt": "Cardápio",
    "exampleHtml": "Can I see the <b>menu</b>?",
    "examplePt": "Posso ver o cardápio?",
    "pos": "noun"
   },
   {
    "id": "food_9",
    "deckId": "food",
    "en": "I'd like…",
    "pt": "Eu gostaria de…",
    "exampleHtml": "<b>I'd like</b> a sandwich, please.",
    "examplePt": "Eu gostaria de um sanduíche, por favor.",
    "pos": "phrase"
   },
   {
    "id": "food_10",
    "deckId": "food",
    "en": "Can I have…?",
    "pt": "Posso pedir…?",
    "exampleHtml": "<b>Can I have</b> the bill, please?",
    "examplePt": "Posso pedir a conta, por favor?",
    "pos": "phrase"
   },
   {
    "id": "food_11",
    "deckId": "food",
    "en": "The bill, please",
    "pt": "A conta, por favor",
    "exampleHtml": "<b>The bill, please.</b>",
    "examplePt": "A conta, por favor.",
    "pos": "phrase"
   },
   {
    "id": "food_12",
    "deckId": "food",
    "en": "Takeaway",
    "pt": "Para viagem",
    "exampleHtml": "Is it <b>takeaway</b> or dine in?",
    "examplePt": "É para viagem ou para comer aqui?",
    "pos": "noun"
   },
   {
    "id": "food_13",
    "deckId": "food",
    "en": "Delicious",
    "pt": "Delicioso",
    "exampleHtml": "This is <b>delicious</b>!",
    "examplePt": "Isto está delicioso!",
    "pos": "adj"
   },
   {
    "id": "food_14",
    "deckId": "food",
    "en": "I'm allergic to…",
    "pt": "Sou alérgica a…",
    "exampleHtml": "<b>I'm allergic to</b> nuts.",
    "examplePt": "Sou alérgica a nozes.",
    "pos": "phrase"
   },
   {
    "id": "food_15",
    "deckId": "food",
    "en": "No sugar, thanks",
    "pt": "Sem açúcar, obrigada",
    "exampleHtml": "<b>No sugar, thanks.</b>",
    "examplePt": "Sem açúcar, obrigada.",
    "pos": "phrase"
   },
   {
    "id": "food_16",
    "deckId": "food",
    "en": "Cheers",
    "pt": "Valeu / saúde",
    "exampleHtml": "<b>Cheers</b>, mate!",
    "examplePt": "Valeu, cara!",
    "pos": "word"
   }
  ]
 },
 {
  "id": "shopping",
  "name": "Shopping & supermarket",
  "emoji": "🛒",
  "desc": "Prices, sizes, paying",
  "level": 2,
  "cards": [
   {
    "id": "shopping_0",
    "deckId": "shopping",
    "en": "How much is it?",
    "pt": "Quanto custa?",
    "exampleHtml": "Excuse me, <b>how much is it?</b>",
    "examplePt": "Com licença, quanto custa?",
    "pos": "phrase"
   },
   {
    "id": "shopping_1",
    "deckId": "shopping",
    "en": "Too expensive",
    "pt": "Caro demais",
    "exampleHtml": "That's <b>too expensive</b>.",
    "examplePt": "Isso é caro demais.",
    "pos": "phrase"
   },
   {
    "id": "shopping_2",
    "deckId": "shopping",
    "en": "Cheap",
    "pt": "Barato",
    "exampleHtml": "This one is <b>cheap</b>.",
    "examplePt": "Este é barato.",
    "pos": "adj"
   },
   {
    "id": "shopping_3",
    "deckId": "shopping",
    "en": "On special",
    "pt": "Em promoção (NZ)",
    "exampleHtml": "The apples are <b>on special</b>.",
    "examplePt": "As maçãs estão em promoção.",
    "pos": "phrase"
   },
   {
    "id": "shopping_4",
    "deckId": "shopping",
    "en": "Do you have…?",
    "pt": "Você tem…?",
    "exampleHtml": "<b>Do you have</b> this in blue?",
    "examplePt": "Você tem isto em azul?",
    "pos": "phrase"
   },
   {
    "id": "shopping_5",
    "deckId": "shopping",
    "en": "Size",
    "pt": "Tamanho",
    "exampleHtml": "What <b>size</b> are you?",
    "examplePt": "Qual é o seu tamanho?",
    "pos": "noun"
   },
   {
    "id": "shopping_6",
    "deckId": "shopping",
    "en": "Receipt",
    "pt": "Recibo / nota",
    "exampleHtml": "Can I have a <b>receipt</b>?",
    "examplePt": "Pode me dar o recibo?",
    "pos": "noun"
   },
   {
    "id": "shopping_7",
    "deckId": "shopping",
    "en": "Trolley",
    "pt": "Carrinho (de mercado)",
    "exampleHtml": "Grab a <b>trolley</b>.",
    "examplePt": "Pega um carrinho.",
    "pos": "noun"
   },
   {
    "id": "shopping_8",
    "deckId": "shopping",
    "en": "Checkout",
    "pt": "Caixa (do mercado)",
    "exampleHtml": "Meet me at the <b>checkout</b>.",
    "examplePt": "Me encontra no caixa.",
    "pos": "noun"
   },
   {
    "id": "shopping_9",
    "deckId": "shopping",
    "en": "EFTPOS",
    "pt": "Máquina de cartão (NZ)",
    "exampleHtml": "Can I pay by <b>EFTPOS</b>?",
    "examplePt": "Posso pagar no cartão (EFTPOS)?",
    "pos": "noun"
   },
   {
    "id": "shopping_10",
    "deckId": "shopping",
    "en": "Cash",
    "pt": "Dinheiro",
    "exampleHtml": "Do you take <b>cash</b>?",
    "examplePt": "Vocês aceitam dinheiro?",
    "pos": "noun"
   },
   {
    "id": "shopping_11",
    "deckId": "shopping",
    "en": "Card",
    "pt": "Cartão",
    "exampleHtml": "I'll pay by <b>card</b>.",
    "examplePt": "Vou pagar no cartão.",
    "pos": "noun"
   },
   {
    "id": "shopping_12",
    "deckId": "shopping",
    "en": "Bag",
    "pt": "Sacola",
    "exampleHtml": "Do you need a <b>bag</b>?",
    "examplePt": "Você precisa de uma sacola?",
    "pos": "noun"
   },
   {
    "id": "shopping_13",
    "deckId": "shopping",
    "en": "The Warehouse",
    "pt": "Loja de tudo barato (NZ)",
    "exampleHtml": "Let's go to <b>The Warehouse</b>.",
    "examplePt": "Vamos à The Warehouse.",
    "pos": "noun"
   },
   {
    "id": "shopping_14",
    "deckId": "shopping",
    "en": "Countdown / New World",
    "pt": "Supermercados (NZ)",
    "exampleHtml": "I shop at <b>Countdown</b>.",
    "examplePt": "Faço compras no Countdown.",
    "pos": "noun"
   },
   {
    "id": "shopping_15",
    "deckId": "shopping",
    "en": "Dairy",
    "pt": "Mercadinho de esquina (NZ)",
    "exampleHtml": "Get milk from the <b>dairy</b>.",
    "examplePt": "Pega leite no mercadinho.",
    "pos": "noun"
   }
  ]
 },
 {
  "id": "money",
  "name": "Money & banking",
  "emoji": "🏦",
  "desc": "IRD, accounts, paying bills",
  "level": 3,
  "cards": [
   {
    "id": "money_0",
    "deckId": "money",
    "en": "Bank account",
    "pt": "Conta bancária",
    "exampleHtml": "I need to open a <b>bank account</b>.",
    "examplePt": "Preciso abrir uma conta bancária.",
    "pos": "noun"
   },
   {
    "id": "money_1",
    "deckId": "money",
    "en": "IRD number",
    "pt": "Nº de contribuinte (NZ)",
    "exampleHtml": "You need an <b>IRD number</b> to work.",
    "examplePt": "Você precisa de um IRD number para trabalhar.",
    "pos": "noun"
   },
   {
    "id": "money_2",
    "deckId": "money",
    "en": "Bill",
    "pt": "Conta (a pagar)",
    "exampleHtml": "I have to pay the <b>bill</b>.",
    "examplePt": "Tenho que pagar a conta.",
    "pos": "noun"
   },
   {
    "id": "money_3",
    "deckId": "money",
    "en": "Rent",
    "pt": "Aluguel",
    "exampleHtml": "The <b>rent</b> is due on Friday.",
    "examplePt": "O aluguel vence na sexta.",
    "pos": "noun"
   },
   {
    "id": "money_4",
    "deckId": "money",
    "en": "Wages / pay",
    "pt": "Salário",
    "exampleHtml": "I get my <b>pay</b> every week.",
    "examplePt": "Recebo meu salário toda semana.",
    "pos": "noun"
   },
   {
    "id": "money_5",
    "deckId": "money",
    "en": "Fortnight",
    "pt": "Quinzena (comum na NZ)",
    "exampleHtml": "I'm paid every <b>fortnight</b>.",
    "examplePt": "Recebo a cada quinzena.",
    "pos": "noun"
   },
   {
    "id": "money_6",
    "deckId": "money",
    "en": "Savings",
    "pt": "Poupança / economias",
    "exampleHtml": "We have some <b>savings</b>.",
    "examplePt": "Temos uma poupança.",
    "pos": "noun"
   },
   {
    "id": "money_7",
    "deckId": "money",
    "en": "Expensive",
    "pt": "Caro",
    "exampleHtml": "Housing is <b>expensive</b> here.",
    "examplePt": "Moradia é cara aqui.",
    "pos": "adj"
   },
   {
    "id": "money_8",
    "deckId": "money",
    "en": "Dollar",
    "pt": "Dólar",
    "exampleHtml": "It costs ten <b>dollars</b>.",
    "examplePt": "Custa dez dólares.",
    "pos": "noun"
   },
   {
    "id": "money_9",
    "deckId": "money",
    "en": "Cents",
    "pt": "Centavos",
    "exampleHtml": "Ninety-nine <b>cents</b>.",
    "examplePt": "Noventa e nove centavos.",
    "pos": "noun"
   },
   {
    "id": "money_10",
    "deckId": "money",
    "en": "Transfer",
    "pt": "Transferência",
    "exampleHtml": "I'll do a bank <b>transfer</b>.",
    "examplePt": "Vou fazer uma transferência.",
    "pos": "noun"
   },
   {
    "id": "money_11",
    "deckId": "money",
    "en": "ATM",
    "pt": "Caixa eletrônico",
    "exampleHtml": "Where's the nearest <b>ATM</b>?",
    "examplePt": "Onde fica o caixa eletrônico mais perto?",
    "pos": "noun"
   },
   {
    "id": "money_12",
    "deckId": "money",
    "en": "Deposit",
    "pt": "Depósito",
    "exampleHtml": "I'd like to make a <b>deposit</b>.",
    "examplePt": "Gostaria de fazer um depósito.",
    "pos": "noun"
   },
   {
    "id": "money_13",
    "deckId": "money",
    "en": "Budget",
    "pt": "Orçamento",
    "exampleHtml": "We need a <b>budget</b>.",
    "examplePt": "Precisamos de um orçamento.",
    "pos": "noun"
   }
  ]
 },
 {
  "id": "housing",
  "name": "Housing & renting (NZ)",
  "emoji": "🏠",
  "desc": "Flats, bond, letting agents",
  "level": 3,
  "cards": [
   {
    "id": "housing_0",
    "deckId": "housing",
    "en": "Flat",
    "pt": "Apartamento / casa alugada (NZ)",
    "exampleHtml": "We're renting a <b>flat</b>.",
    "examplePt": "Estamos alugando um flat.",
    "pos": "noun"
   },
   {
    "id": "housing_1",
    "deckId": "housing",
    "en": "Flatmate",
    "pt": "Colega de moradia",
    "exampleHtml": "We have two <b>flatmates</b>.",
    "examplePt": "Temos dois flatmates.",
    "pos": "noun"
   },
   {
    "id": "housing_2",
    "deckId": "housing",
    "en": "Landlord",
    "pt": "Proprietário / locador",
    "exampleHtml": "The <b>landlord</b> is nice.",
    "examplePt": "O locador é gente boa.",
    "pos": "noun"
   },
   {
    "id": "housing_3",
    "deckId": "housing",
    "en": "Letting agent",
    "pt": "Corretor de aluguel",
    "exampleHtml": "Call the <b>letting agent</b>.",
    "examplePt": "Ligue para o corretor de aluguel.",
    "pos": "noun"
   },
   {
    "id": "housing_4",
    "deckId": "housing",
    "en": "Bond",
    "pt": "Caução / depósito de garantia",
    "exampleHtml": "The <b>bond</b> is four weeks' rent.",
    "examplePt": "A caução é quatro semanas de aluguel.",
    "pos": "noun"
   },
   {
    "id": "housing_5",
    "deckId": "housing",
    "en": "Lease / tenancy",
    "pt": "Contrato de aluguel",
    "exampleHtml": "We signed a one-year <b>tenancy</b>.",
    "examplePt": "Assinamos um contrato de um ano.",
    "pos": "noun"
   },
   {
    "id": "housing_6",
    "deckId": "housing",
    "en": "Viewing",
    "pt": "Visita ao imóvel",
    "exampleHtml": "We have a <b>viewing</b> at 3pm.",
    "examplePt": "Temos uma visita às 15h.",
    "pos": "noun"
   },
   {
    "id": "housing_7",
    "deckId": "housing",
    "en": "Furnished",
    "pt": "Mobiliado",
    "exampleHtml": "Is the flat <b>furnished</b>?",
    "examplePt": "O apê é mobiliado?",
    "pos": "adj"
   },
   {
    "id": "housing_8",
    "deckId": "housing",
    "en": "Power / electricity",
    "pt": "Energia elétrica",
    "exampleHtml": "We need to connect the <b>power</b>.",
    "examplePt": "Precisamos ligar a energia.",
    "pos": "noun"
   },
   {
    "id": "housing_9",
    "deckId": "housing",
    "en": "Heat pump",
    "pt": "Ar-condicionado/aquecedor (NZ)",
    "exampleHtml": "The <b>heat pump</b> keeps us warm.",
    "examplePt": "O heat pump nos aquece.",
    "pos": "noun"
   },
   {
    "id": "housing_10",
    "deckId": "housing",
    "en": "Rubbish / bin",
    "pt": "Lixo / lixeira",
    "exampleHtml": "Put it in the <b>rubbish bin</b>.",
    "examplePt": "Coloca no lixo.",
    "pos": "noun"
   },
   {
    "id": "housing_11",
    "deckId": "housing",
    "en": "Recycling",
    "pt": "Reciclagem",
    "exampleHtml": "The <b>recycling</b> goes out on Tuesday.",
    "examplePt": "A reciclagem sai na terça.",
    "pos": "noun"
   },
   {
    "id": "housing_12",
    "deckId": "housing",
    "en": "Suburb",
    "pt": "Bairro",
    "exampleHtml": "Which <b>suburb</b> do you live in?",
    "examplePt": "Em que bairro você mora?",
    "pos": "noun"
   },
   {
    "id": "housing_13",
    "deckId": "housing",
    "en": "Damp",
    "pt": "Úmido (comum em casas NZ)",
    "exampleHtml": "The room is a bit <b>damp</b>.",
    "examplePt": "O quarto é meio úmido.",
    "pos": "adj"
   },
   {
    "id": "housing_14",
    "deckId": "housing",
    "en": "Key",
    "pt": "Chave",
    "exampleHtml": "I lost my <b>key</b>.",
    "examplePt": "Perdi minha chave.",
    "pos": "noun"
   },
   {
    "id": "housing_15",
    "deckId": "housing",
    "en": "Address",
    "pt": "Endereço",
    "exampleHtml": "What's your <b>address</b>?",
    "examplePt": "Qual é o seu endereço?",
    "pos": "noun"
   }
  ]
 },
 {
  "id": "health",
  "name": "Health, GP & pharmacy (NZ)",
  "emoji": "🩺",
  "desc": "Doctors, chemist, feeling unwell",
  "level": 3,
  "cards": [
   {
    "id": "health_0",
    "deckId": "health",
    "en": "GP",
    "pt": "Clínico geral / médico de família",
    "exampleHtml": "I need to see a <b>GP</b>.",
    "examplePt": "Preciso consultar um clínico geral.",
    "pos": "noun"
   },
   {
    "id": "health_1",
    "deckId": "health",
    "en": "Appointment",
    "pt": "Consulta / agendamento",
    "exampleHtml": "I'd like to book an <b>appointment</b>.",
    "examplePt": "Gostaria de marcar uma consulta.",
    "pos": "noun"
   },
   {
    "id": "health_2",
    "deckId": "health",
    "en": "Chemist / pharmacy",
    "pt": "Farmácia (NZ)",
    "exampleHtml": "Get it from the <b>chemist</b>.",
    "examplePt": "Pega na farmácia.",
    "pos": "noun"
   },
   {
    "id": "health_3",
    "deckId": "health",
    "en": "Prescription",
    "pt": "Receita médica",
    "exampleHtml": "I need a <b>prescription</b>.",
    "examplePt": "Preciso de uma receita.",
    "pos": "noun"
   },
   {
    "id": "health_4",
    "deckId": "health",
    "en": "Medicine",
    "pt": "Remédio",
    "exampleHtml": "Take this <b>medicine</b> twice a day.",
    "examplePt": "Tome este remédio duas vezes ao dia.",
    "pos": "noun"
   },
   {
    "id": "health_5",
    "deckId": "health",
    "en": "I feel sick",
    "pt": "Estou me sentindo mal",
    "exampleHtml": "<b>I feel sick</b> today.",
    "examplePt": "Estou me sentindo mal hoje.",
    "pos": "phrase"
   },
   {
    "id": "health_6",
    "deckId": "health",
    "en": "It hurts here",
    "pt": "Dói aqui",
    "exampleHtml": "<b>It hurts here.</b>",
    "examplePt": "Dói aqui.",
    "pos": "phrase"
   },
   {
    "id": "health_7",
    "deckId": "health",
    "en": "Headache",
    "pt": "Dor de cabeça",
    "exampleHtml": "I have a <b>headache</b>.",
    "examplePt": "Estou com dor de cabeça.",
    "pos": "noun"
   },
   {
    "id": "health_8",
    "deckId": "health",
    "en": "Fever",
    "pt": "Febre",
    "exampleHtml": "She has a <b>fever</b>.",
    "examplePt": "Ela está com febre.",
    "pos": "noun"
   },
   {
    "id": "health_9",
    "deckId": "health",
    "en": "Cough",
    "pt": "Tosse",
    "exampleHtml": "I have a <b>cough</b>.",
    "examplePt": "Estou com tosse.",
    "pos": "noun"
   },
   {
    "id": "health_10",
    "deckId": "health",
    "en": "Cold / flu",
    "pt": "Resfriado / gripe",
    "exampleHtml": "I've got a <b>cold</b>.",
    "examplePt": "Estou resfriada.",
    "pos": "noun"
   },
   {
    "id": "health_11",
    "deckId": "health",
    "en": "Nurse",
    "pt": "Enfermeiro(a)",
    "exampleHtml": "The <b>nurse</b> will see you now.",
    "examplePt": "O enfermeiro vai te atender agora.",
    "pos": "noun"
   },
   {
    "id": "health_12",
    "deckId": "health",
    "en": "Hospital",
    "pt": "Hospital",
    "exampleHtml": "Where is the <b>hospital</b>?",
    "examplePt": "Onde fica o hospital?",
    "pos": "noun"
   },
   {
    "id": "health_13",
    "deckId": "health",
    "en": "Dentist",
    "pt": "Dentista",
    "exampleHtml": "I need a <b>dentist</b>.",
    "examplePt": "Preciso de um dentista.",
    "pos": "noun"
   },
   {
    "id": "health_14",
    "deckId": "health",
    "en": "Healthline",
    "pt": "Telessaúde grátis (NZ)",
    "exampleHtml": "You can call <b>Healthline</b> for advice.",
    "examplePt": "Você pode ligar para a Healthline.",
    "pos": "noun"
   },
   {
    "id": "health_15",
    "deckId": "health",
    "en": "I'm pregnant",
    "pt": "Estou grávida",
    "exampleHtml": "<b>I'm pregnant.</b>",
    "examplePt": "Estou grávida.",
    "pos": "phrase"
   }
  ]
 },
 {
  "id": "transport",
  "name": "Getting around (NZ)",
  "emoji": "🚌",
  "desc": "Buses, driving, directions",
  "level": 3,
  "cards": [
   {
    "id": "transport_0",
    "deckId": "transport",
    "en": "Bus",
    "pt": "Ônibus",
    "exampleHtml": "The <b>bus</b> is late.",
    "examplePt": "O ônibus está atrasado.",
    "pos": "noun"
   },
   {
    "id": "transport_1",
    "deckId": "transport",
    "en": "Bus stop",
    "pt": "Ponto de ônibus",
    "exampleHtml": "Wait at the <b>bus stop</b>.",
    "examplePt": "Espere no ponto de ônibus.",
    "pos": "noun"
   },
   {
    "id": "transport_2",
    "deckId": "transport",
    "en": "AT HOP / Bee Card",
    "pt": "Cartão de transporte (NZ)",
    "exampleHtml": "Tag on with your <b>AT HOP card</b>.",
    "examplePt": "Passe o cartão de transporte.",
    "pos": "noun"
   },
   {
    "id": "transport_3",
    "deckId": "transport",
    "en": "Train",
    "pt": "Trem",
    "exampleHtml": "Take the <b>train</b> to the city.",
    "examplePt": "Pegue o trem para a cidade.",
    "pos": "noun"
   },
   {
    "id": "transport_4",
    "deckId": "transport",
    "en": "Ferry",
    "pt": "Balsa / ferry",
    "exampleHtml": "The <b>ferry</b> leaves at noon.",
    "examplePt": "A balsa sai ao meio-dia.",
    "pos": "noun"
   },
   {
    "id": "transport_5",
    "deckId": "transport",
    "en": "Car",
    "pt": "Carro",
    "exampleHtml": "We need a <b>car</b>.",
    "examplePt": "Precisamos de um carro.",
    "pos": "noun"
   },
   {
    "id": "transport_6",
    "deckId": "transport",
    "en": "Petrol",
    "pt": "Gasolina (NZ)",
    "exampleHtml": "I need to get <b>petrol</b>.",
    "examplePt": "Preciso abastecer.",
    "pos": "noun"
   },
   {
    "id": "transport_7",
    "deckId": "transport",
    "en": "Driver's licence",
    "pt": "Carteira de motorista",
    "exampleHtml": "I have a Brazilian <b>driver's licence</b>.",
    "examplePt": "Tenho carteira de motorista brasileira.",
    "pos": "noun"
   },
   {
    "id": "transport_8",
    "deckId": "transport",
    "en": "Left side",
    "pt": "Lado esquerdo (dirige-se à esquerda!)",
    "exampleHtml": "In NZ you drive on the <b>left side</b>.",
    "examplePt": "Na NZ se dirige do lado esquerdo.",
    "pos": "phrase"
   },
   {
    "id": "transport_9",
    "deckId": "transport",
    "en": "How do I get to…?",
    "pt": "Como chego em…?",
    "exampleHtml": "<b>How do I get to</b> the city centre?",
    "examplePt": "Como chego ao centro da cidade?",
    "pos": "phrase"
   },
   {
    "id": "transport_10",
    "deckId": "transport",
    "en": "Turn left",
    "pt": "Vire à esquerda",
    "exampleHtml": "<b>Turn left</b> here.",
    "examplePt": "Vire à esquerda aqui.",
    "pos": "phrase"
   },
   {
    "id": "transport_11",
    "deckId": "transport",
    "en": "Turn right",
    "pt": "Vire à direita",
    "exampleHtml": "<b>Turn right</b> at the lights.",
    "examplePt": "Vire à direita no sinal.",
    "pos": "phrase"
   },
   {
    "id": "transport_12",
    "deckId": "transport",
    "en": "Straight ahead",
    "pt": "Em frente",
    "exampleHtml": "Go <b>straight ahead</b>.",
    "examplePt": "Siga em frente.",
    "pos": "phrase"
   },
   {
    "id": "transport_13",
    "deckId": "transport",
    "en": "Near / far",
    "pt": "Perto / longe",
    "exampleHtml": "Is it <b>near</b> or <b>far</b>?",
    "examplePt": "É perto ou longe?",
    "pos": "adj"
   },
   {
    "id": "transport_14",
    "deckId": "transport",
    "en": "Traffic lights",
    "pt": "Semáforo",
    "exampleHtml": "Stop at the <b>traffic lights</b>.",
    "examplePt": "Pare no semáforo.",
    "pos": "noun"
   },
   {
    "id": "transport_15",
    "deckId": "transport",
    "en": "Footpath",
    "pt": "Calçada (NZ)",
    "exampleHtml": "Walk on the <b>footpath</b>.",
    "examplePt": "Ande na calçada.",
    "pos": "noun"
   }
  ]
 },
 {
  "id": "work",
  "name": "Work & job",
  "emoji": "💼",
  "desc": "Interviews, workplace basics",
  "level": 3,
  "cards": [
   {
    "id": "work_0",
    "deckId": "work",
    "en": "Job",
    "pt": "Emprego / trabalho",
    "exampleHtml": "I'm looking for a <b>job</b>.",
    "examplePt": "Estou procurando emprego.",
    "pos": "noun"
   },
   {
    "id": "work_1",
    "deckId": "work",
    "en": "CV / résumé",
    "pt": "Currículo",
    "exampleHtml": "Here is my <b>CV</b>.",
    "examplePt": "Aqui está meu currículo.",
    "pos": "noun"
   },
   {
    "id": "work_2",
    "deckId": "work",
    "en": "Interview",
    "pt": "Entrevista",
    "exampleHtml": "I have a job <b>interview</b>.",
    "examplePt": "Tenho uma entrevista de emprego.",
    "pos": "noun"
   },
   {
    "id": "work_3",
    "deckId": "work",
    "en": "Boss / manager",
    "pt": "Chefe / gerente",
    "exampleHtml": "My <b>manager</b> is helpful.",
    "examplePt": "Meu gerente é prestativo.",
    "pos": "noun"
   },
   {
    "id": "work_4",
    "deckId": "work",
    "en": "Colleague / workmate",
    "pt": "Colega de trabalho",
    "exampleHtml": "My <b>workmates</b> are friendly.",
    "examplePt": "Meus colegas são simpáticos.",
    "pos": "noun"
   },
   {
    "id": "work_5",
    "deckId": "work",
    "en": "Shift",
    "pt": "Turno",
    "exampleHtml": "I work the morning <b>shift</b>.",
    "examplePt": "Trabalho no turno da manhã.",
    "pos": "noun"
   },
   {
    "id": "work_6",
    "deckId": "work",
    "en": "Full-time",
    "pt": "Tempo integral",
    "exampleHtml": "It's a <b>full-time</b> job.",
    "examplePt": "É um emprego de tempo integral.",
    "pos": "adj"
   },
   {
    "id": "work_7",
    "deckId": "work",
    "en": "Part-time",
    "pt": "Meio período",
    "exampleHtml": "I want <b>part-time</b> work.",
    "examplePt": "Quero um trabalho de meio período.",
    "pos": "adj"
   },
   {
    "id": "work_8",
    "deckId": "work",
    "en": "Experience",
    "pt": "Experiência",
    "exampleHtml": "I have three years of <b>experience</b>.",
    "examplePt": "Tenho três anos de experiência.",
    "pos": "noun"
   },
   {
    "id": "work_9",
    "deckId": "work",
    "en": "Available",
    "pt": "Disponível",
    "exampleHtml": "I'm <b>available</b> to start now.",
    "examplePt": "Estou disponível para começar agora.",
    "pos": "adj"
   },
   {
    "id": "work_10",
    "deckId": "work",
    "en": "Break",
    "pt": "Pausa / intervalo",
    "exampleHtml": "Let's take a <b>break</b>.",
    "examplePt": "Vamos fazer uma pausa.",
    "pos": "noun"
   },
   {
    "id": "work_11",
    "deckId": "work",
    "en": "Meeting",
    "pt": "Reunião",
    "exampleHtml": "We have a <b>meeting</b> at 10.",
    "examplePt": "Temos uma reunião às 10.",
    "pos": "noun"
   },
   {
    "id": "work_12",
    "deckId": "work",
    "en": "Email",
    "pt": "E-mail",
    "exampleHtml": "I'll send you an <b>email</b>.",
    "examplePt": "Vou te mandar um e-mail.",
    "pos": "noun"
   },
   {
    "id": "work_13",
    "deckId": "work",
    "en": "Thank you for your time",
    "pt": "Obrigada pelo seu tempo",
    "exampleHtml": "<b>Thank you for your time.</b>",
    "examplePt": "Obrigada pelo seu tempo.",
    "pos": "phrase"
   }
  ]
 },
 {
  "id": "smalltalk",
  "name": "Small talk & social",
  "emoji": "💬",
  "desc": "Chat, make friends, be polite",
  "level": 3,
  "cards": [
   {
    "id": "smalltalk_0",
    "deckId": "smalltalk",
    "en": "How's it going?",
    "pt": "Como vão as coisas?",
    "exampleHtml": "Hey, <b>how's it going?</b>",
    "examplePt": "E aí, como vão as coisas?",
    "pos": "phrase"
   },
   {
    "id": "smalltalk_1",
    "deckId": "smalltalk",
    "en": "Not bad, you?",
    "pt": "Nada mal, e você?",
    "exampleHtml": "“How are you?” — “<b>Not bad, you?</b>”",
    "examplePt": "“Como vai?” — “Nada mal, e você?”",
    "pos": "phrase"
   },
   {
    "id": "smalltalk_2",
    "deckId": "smalltalk",
    "en": "What do you do?",
    "pt": "O que você faz? (trabalho)",
    "exampleHtml": "So, <b>what do you do?</b>",
    "examplePt": "Então, o que você faz?",
    "pos": "phrase"
   },
   {
    "id": "smalltalk_3",
    "deckId": "smalltalk",
    "en": "Where are you from?",
    "pt": "De onde você é?",
    "exampleHtml": "<b>Where are you from?</b>",
    "examplePt": "De onde você é?",
    "pos": "phrase"
   },
   {
    "id": "smalltalk_4",
    "deckId": "smalltalk",
    "en": "Lovely weather",
    "pt": "Tempo ótimo (papo comum)",
    "exampleHtml": "<b>Lovely weather</b> today, eh?",
    "examplePt": "Que tempo bom hoje, né?",
    "pos": "phrase"
   },
   {
    "id": "smalltalk_5",
    "deckId": "smalltalk",
    "en": "That's great!",
    "pt": "Que ótimo!",
    "exampleHtml": "<b>That's great!</b> Congratulations.",
    "examplePt": "Que ótimo! Parabéns.",
    "pos": "phrase"
   },
   {
    "id": "smalltalk_6",
    "deckId": "smalltalk",
    "en": "No worries",
    "pt": "Sem problema / tranquilo",
    "exampleHtml": "“Thanks!” — “<b>No worries.</b>”",
    "examplePt": "“Valeu!” — “Tranquilo.”",
    "pos": "phrase"
   },
   {
    "id": "smalltalk_7",
    "deckId": "smalltalk",
    "en": "See you later",
    "pt": "Até mais",
    "exampleHtml": "<b>See you later!</b>",
    "examplePt": "Até mais!",
    "pos": "phrase"
   },
   {
    "id": "smalltalk_8",
    "deckId": "smalltalk",
    "en": "Take care",
    "pt": "Se cuida",
    "exampleHtml": "Bye, <b>take care!</b>",
    "examplePt": "Tchau, se cuida!",
    "pos": "phrase"
   },
   {
    "id": "smalltalk_9",
    "deckId": "smalltalk",
    "en": "Have a good one",
    "pt": "Tenha um bom dia (informal NZ)",
    "exampleHtml": "<b>Have a good one!</b>",
    "examplePt": "Tenha um bom dia!",
    "pos": "phrase"
   },
   {
    "id": "smalltalk_10",
    "deckId": "smalltalk",
    "en": "I'm still learning English",
    "pt": "Ainda estou aprendendo inglês",
    "exampleHtml": "Sorry, <b>I'm still learning English</b>.",
    "examplePt": "Desculpa, ainda estou aprendendo inglês.",
    "pos": "phrase"
   },
   {
    "id": "smalltalk_11",
    "deckId": "smalltalk",
    "en": "Could you help me?",
    "pt": "Você poderia me ajudar?",
    "exampleHtml": "<b>Could you help me</b>, please?",
    "examplePt": "Você poderia me ajudar, por favor?",
    "pos": "phrase"
   },
   {
    "id": "smalltalk_12",
    "deckId": "smalltalk",
    "en": "What does this mean?",
    "pt": "O que isso significa?",
    "exampleHtml": "<b>What does this mean?</b>",
    "examplePt": "O que isso significa?",
    "pos": "phrase"
   },
   {
    "id": "smalltalk_13",
    "deckId": "smalltalk",
    "en": "Congratulations",
    "pt": "Parabéns",
    "exampleHtml": "<b>Congratulations</b> on the new job!",
    "examplePt": "Parabéns pelo novo emprego!",
    "pos": "word"
   }
  ]
 },
 {
  "id": "kiwi",
  "name": "Kiwi slang & NZ words",
  "emoji": "🥝",
  "desc": "Sound like a local in Aotearoa",
  "level": 3,
  "cards": [
   {
    "id": "kiwi_0",
    "deckId": "kiwi",
    "en": "Kia ora",
    "pt": "Olá / saúde (Māori)",
    "exampleHtml": "<b>Kia ora!</b> Welcome.",
    "examplePt": "Kia ora! Bem-vinda.",
    "pos": "greeting"
   },
   {
    "id": "kiwi_1",
    "deckId": "kiwi",
    "en": "Sweet as",
    "pt": "Show / beleza / perfeito",
    "exampleHtml": "“Meet at six?” — “<b>Sweet as!</b>”",
    "examplePt": "“Às seis?” — “Beleza!”",
    "pos": "slang"
   },
   {
    "id": "kiwi_2",
    "deckId": "kiwi",
    "en": "Chur",
    "pt": "Valeu / obrigado (gíria)",
    "exampleHtml": "<b>Chur</b>, bro!",
    "examplePt": "Valeu, mano!",
    "pos": "slang"
   },
   {
    "id": "kiwi_3",
    "deckId": "kiwi",
    "en": "Heaps",
    "pt": "Muito / um monte",
    "exampleHtml": "Thanks <b>heaps</b>!",
    "examplePt": "Muito obrigada!",
    "pos": "slang"
   },
   {
    "id": "kiwi_4",
    "deckId": "kiwi",
    "en": "Keen",
    "pt": "Animado / a fim",
    "exampleHtml": "I'm <b>keen</b> to go.",
    "examplePt": "Tô a fim de ir.",
    "pos": "slang"
   },
   {
    "id": "kiwi_5",
    "deckId": "kiwi",
    "en": "Mate",
    "pt": "Amigo / cara",
    "exampleHtml": "Cheers, <b>mate</b>.",
    "examplePt": "Valeu, cara.",
    "pos": "slang"
   },
   {
    "id": "kiwi_6",
    "deckId": "kiwi",
    "en": "Ta",
    "pt": "Obrigada (curtinho)",
    "exampleHtml": "<b>Ta!</b> That's kind.",
    "examplePt": "Obrigada! Que gentil.",
    "pos": "slang"
   },
   {
    "id": "kiwi_7",
    "deckId": "kiwi",
    "en": "Jandals",
    "pt": "Chinelo de dedo",
    "exampleHtml": "Wear your <b>jandals</b> to the beach.",
    "examplePt": "Leve os chinelos pra praia.",
    "pos": "noun"
   },
   {
    "id": "kiwi_8",
    "deckId": "kiwi",
    "en": "Togs",
    "pt": "Roupa de banho",
    "exampleHtml": "Bring your <b>togs</b> for swimming.",
    "examplePt": "Traga sua roupa de banho.",
    "pos": "noun"
   },
   {
    "id": "kiwi_9",
    "deckId": "kiwi",
    "en": "Bach",
    "pt": "Casa de praia / campo",
    "exampleHtml": "We're staying at a <b>bach</b>.",
    "examplePt": "Vamos ficar numa casa de praia.",
    "pos": "noun"
   },
   {
    "id": "kiwi_10",
    "deckId": "kiwi",
    "en": "Chilly bin",
    "pt": "Cooler / isopor",
    "exampleHtml": "Put the drinks in the <b>chilly bin</b>.",
    "examplePt": "Põe as bebidas no cooler.",
    "pos": "noun"
   },
   {
    "id": "kiwi_11",
    "deckId": "kiwi",
    "en": "Tramping",
    "pt": "Trilha / caminhada",
    "exampleHtml": "We're going <b>tramping</b> this weekend.",
    "examplePt": "Vamos fazer trilha neste fim de semana.",
    "pos": "noun"
   },
   {
    "id": "kiwi_12",
    "deckId": "kiwi",
    "en": "Bring a plate",
    "pt": "Traga um prato de comida (festa)",
    "exampleHtml": "It's a party — <b>bring a plate</b>.",
    "examplePt": "É festa — traga um prato de comida.",
    "pos": "phrase"
   },
   {
    "id": "kiwi_13",
    "deckId": "kiwi",
    "en": "Wee",
    "pt": "Pequeno / um pouquinho",
    "exampleHtml": "Just a <b>wee</b> bit.",
    "examplePt": "Só um pouquinho.",
    "pos": "slang"
   },
   {
    "id": "kiwi_14",
    "deckId": "kiwi",
    "en": "Good on ya",
    "pt": "Muito bem / parabéns",
    "exampleHtml": "<b>Good on ya!</b>",
    "examplePt": "Muito bem!",
    "pos": "phrase"
   },
   {
    "id": "kiwi_15",
    "deckId": "kiwi",
    "en": "Aotearoa",
    "pt": "Nome Māori da Nova Zelândia",
    "exampleHtml": "Welcome to <b>Aotearoa</b>.",
    "examplePt": "Bem-vinda à Aotearoa.",
    "pos": "noun"
   }
  ]
 },
 {
  "id": "emergency",
  "name": "Emergencies & help",
  "emoji": "🚨",
  "desc": "Words that matter when it's urgent",
  "level": 1,
  "cards": [
   {
    "id": "emergency_0",
    "deckId": "emergency",
    "en": "Help!",
    "pt": "Socorro! / Ajuda!",
    "exampleHtml": "<b>Help!</b> Please call someone.",
    "examplePt": "Socorro! Por favor chame alguém.",
    "pos": "word"
   },
   {
    "id": "emergency_1",
    "deckId": "emergency",
    "en": "Call 111",
    "pt": "Ligue 111 (emergência NZ)",
    "exampleHtml": "<b>Call 111</b> — it's an emergency.",
    "examplePt": "Ligue 111 — é uma emergência.",
    "pos": "phrase"
   },
   {
    "id": "emergency_2",
    "deckId": "emergency",
    "en": "Emergency",
    "pt": "Emergência",
    "exampleHtml": "This is an <b>emergency</b>.",
    "examplePt": "Isto é uma emergência.",
    "pos": "noun"
   },
   {
    "id": "emergency_3",
    "deckId": "emergency",
    "en": "Ambulance",
    "pt": "Ambulância",
    "exampleHtml": "We need an <b>ambulance</b>.",
    "examplePt": "Precisamos de uma ambulância.",
    "pos": "noun"
   },
   {
    "id": "emergency_4",
    "deckId": "emergency",
    "en": "Police",
    "pt": "Polícia",
    "exampleHtml": "Call the <b>police</b>.",
    "examplePt": "Chame a polícia.",
    "pos": "noun"
   },
   {
    "id": "emergency_5",
    "deckId": "emergency",
    "en": "Fire",
    "pt": "Fogo / incêndio",
    "exampleHtml": "There's a <b>fire</b>!",
    "examplePt": "Tem um incêndio!",
    "pos": "noun"
   },
   {
    "id": "emergency_6",
    "deckId": "emergency",
    "en": "I need help",
    "pt": "Preciso de ajuda",
    "exampleHtml": "<b>I need help</b>, please.",
    "examplePt": "Preciso de ajuda, por favor.",
    "pos": "phrase"
   },
   {
    "id": "emergency_7",
    "deckId": "emergency",
    "en": "I'm lost",
    "pt": "Estou perdida",
    "exampleHtml": "Excuse me, <b>I'm lost</b>.",
    "examplePt": "Com licença, estou perdida.",
    "pos": "phrase"
   },
   {
    "id": "emergency_8",
    "deckId": "emergency",
    "en": "Are you okay?",
    "pt": "Você está bem?",
    "exampleHtml": "<b>Are you okay?</b>",
    "examplePt": "Você está bem?",
    "pos": "phrase"
   },
   {
    "id": "emergency_9",
    "deckId": "emergency",
    "en": "Careful!",
    "pt": "Cuidado!",
    "exampleHtml": "<b>Careful!</b>",
    "examplePt": "Cuidado!",
    "pos": "word"
   },
   {
    "id": "emergency_10",
    "deckId": "emergency",
    "en": "Stop",
    "pt": "Pare",
    "exampleHtml": "<b>Stop</b>, please!",
    "examplePt": "Pare, por favor!",
    "pos": "word"
   },
   {
    "id": "emergency_11",
    "deckId": "emergency",
    "en": "Danger",
    "pt": "Perigo",
    "exampleHtml": "<b>Danger</b> — do not enter.",
    "examplePt": "Perigo — não entre.",
    "pos": "noun"
   },
   {
    "id": "emergency_12",
    "deckId": "emergency",
    "en": "I don't feel safe",
    "pt": "Não me sinto segura",
    "exampleHtml": "<b>I don't feel safe</b> here.",
    "examplePt": "Não me sinto segura aqui.",
    "pos": "phrase"
   },
   {
    "id": "emergency_13",
    "deckId": "emergency",
    "en": "Where is the exit?",
    "pt": "Onde fica a saída?",
    "exampleHtml": "<b>Where is the exit?</b>",
    "examplePt": "Onde fica a saída?",
    "pos": "phrase"
   }
  ]
 },
 {
  "id": "feelings",
  "name": "Feelings & states",
  "emoji": "😊",
  "desc": "Say how you feel — happy, tired, cold…",
  "level": 1,
  "cards": [
   {
    "id": "feelings_0",
    "deckId": "feelings",
    "en": "Happy",
    "pt": "Feliz",
    "exampleHtml": "I'm so <b>happy</b> here.",
    "examplePt": "Estou tão feliz aqui.",
    "pos": "adj"
   },
   {
    "id": "feelings_1",
    "deckId": "feelings",
    "en": "Sad",
    "pt": "Triste",
    "exampleHtml": "She feels <b>sad</b> today.",
    "examplePt": "Ela está triste hoje.",
    "pos": "adj"
   },
   {
    "id": "feelings_2",
    "deckId": "feelings",
    "en": "Tired",
    "pt": "Cansada",
    "exampleHtml": "I'm really <b>tired</b>.",
    "examplePt": "Estou muito cansada.",
    "pos": "adj"
   },
   {
    "id": "feelings_3",
    "deckId": "feelings",
    "en": "Hungry",
    "pt": "Com fome",
    "exampleHtml": "Are you <b>hungry</b>?",
    "examplePt": "Você está com fome?",
    "pos": "adj"
   },
   {
    "id": "feelings_4",
    "deckId": "feelings",
    "en": "Thirsty",
    "pt": "Com sede",
    "exampleHtml": "I'm <b>thirsty</b>.",
    "examplePt": "Estou com sede.",
    "pos": "adj"
   },
   {
    "id": "feelings_5",
    "deckId": "feelings",
    "en": "Cold",
    "pt": "Com frio",
    "exampleHtml": "I'm <b>cold</b>.",
    "examplePt": "Estou com frio.",
    "pos": "adj"
   },
   {
    "id": "feelings_6",
    "deckId": "feelings",
    "en": "Hot",
    "pt": "Com calor",
    "exampleHtml": "It's too <b>hot</b> in here.",
    "examplePt": "Está quente demais aqui.",
    "pos": "adj"
   },
   {
    "id": "feelings_7",
    "deckId": "feelings",
    "en": "Scared",
    "pt": "Com medo",
    "exampleHtml": "Don't be <b>scared</b>.",
    "examplePt": "Não fique com medo.",
    "pos": "adj"
   },
   {
    "id": "feelings_8",
    "deckId": "feelings",
    "en": "Angry",
    "pt": "Com raiva / bravo",
    "exampleHtml": "He looks <b>angry</b>.",
    "examplePt": "Ele parece bravo.",
    "pos": "adj"
   },
   {
    "id": "feelings_9",
    "deckId": "feelings",
    "en": "Worried",
    "pt": "Preocupada",
    "exampleHtml": "I'm a bit <b>worried</b>.",
    "examplePt": "Estou meio preocupada.",
    "pos": "adj"
   },
   {
    "id": "feelings_10",
    "deckId": "feelings",
    "en": "Excited",
    "pt": "Animada / empolgada",
    "exampleHtml": "I'm <b>excited</b> about the move.",
    "examplePt": "Estou animada com a mudança.",
    "pos": "adj"
   },
   {
    "id": "feelings_11",
    "deckId": "feelings",
    "en": "Nervous",
    "pt": "Nervosa",
    "exampleHtml": "I'm <b>nervous</b> about the interview.",
    "examplePt": "Estou nervosa com a entrevista.",
    "pos": "adj"
   },
   {
    "id": "feelings_12",
    "deckId": "feelings",
    "en": "Bored",
    "pt": "Entediada",
    "exampleHtml": "I'm <b>bored</b>.",
    "examplePt": "Estou entediada.",
    "pos": "adj"
   },
   {
    "id": "feelings_13",
    "deckId": "feelings",
    "en": "Fine",
    "pt": "Bem / tudo certo",
    "exampleHtml": "I'm <b>fine</b>, thanks.",
    "examplePt": "Estou bem, obrigada.",
    "pos": "adj"
   },
   {
    "id": "feelings_14",
    "deckId": "feelings",
    "en": "Homesick",
    "pt": "Com saudade de casa",
    "exampleHtml": "I feel a little <b>homesick</b>.",
    "examplePt": "Estou com saudade de casa.",
    "pos": "adj"
   },
   {
    "id": "feelings_15",
    "deckId": "feelings",
    "en": "Proud",
    "pt": "Orgulhosa",
    "exampleHtml": "I'm <b>proud</b> of you.",
    "examplePt": "Estou orgulhosa de você.",
    "pos": "adj"
   },
   {
    "id": "feelings_16",
    "deckId": "feelings",
    "en": "Comfortable",
    "pt": "Confortável",
    "exampleHtml": "Make yourself <b>comfortable</b>.",
    "examplePt": "Fique à vontade.",
    "pos": "adj"
   },
   {
    "id": "feelings_17",
    "deckId": "feelings",
    "en": "Confused",
    "pt": "Confusa",
    "exampleHtml": "I'm a bit <b>confused</b>.",
    "examplePt": "Estou meio confusa.",
    "pos": "adj"
   }
  ]
 },
 {
  "id": "house",
  "name": "Around the house",
  "emoji": "🛋️",
  "desc": "Rooms and things at home",
  "level": 2,
  "cards": [
   {
    "id": "house_0",
    "deckId": "house",
    "en": "Door",
    "pt": "Porta",
    "exampleHtml": "Close the <b>door</b>, please.",
    "examplePt": "Feche a porta, por favor.",
    "pos": "noun"
   },
   {
    "id": "house_1",
    "deckId": "house",
    "en": "Window",
    "pt": "Janela",
    "exampleHtml": "Open the <b>window</b>.",
    "examplePt": "Abra a janela.",
    "pos": "noun"
   },
   {
    "id": "house_2",
    "deckId": "house",
    "en": "Table",
    "pt": "Mesa",
    "exampleHtml": "Put it on the <b>table</b>.",
    "examplePt": "Coloque na mesa.",
    "pos": "noun"
   },
   {
    "id": "house_3",
    "deckId": "house",
    "en": "Chair",
    "pt": "Cadeira",
    "exampleHtml": "Take a <b>chair</b>.",
    "examplePt": "Pegue uma cadeira.",
    "pos": "noun"
   },
   {
    "id": "house_4",
    "deckId": "house",
    "en": "Bed",
    "pt": "Cama",
    "exampleHtml": "The <b>bed</b> is comfortable.",
    "examplePt": "A cama é confortável.",
    "pos": "noun"
   },
   {
    "id": "house_5",
    "deckId": "house",
    "en": "Kitchen",
    "pt": "Cozinha",
    "exampleHtml": "She's in the <b>kitchen</b>.",
    "examplePt": "Ela está na cozinha.",
    "pos": "noun"
   },
   {
    "id": "house_6",
    "deckId": "house",
    "en": "Bathroom",
    "pt": "Banheiro",
    "exampleHtml": "Where's the <b>bathroom</b>?",
    "examplePt": "Onde fica o banheiro?",
    "pos": "noun"
   },
   {
    "id": "house_7",
    "deckId": "house",
    "en": "Bedroom",
    "pt": "Quarto",
    "exampleHtml": "This is the <b>bedroom</b>.",
    "examplePt": "Este é o quarto.",
    "pos": "noun"
   },
   {
    "id": "house_8",
    "deckId": "house",
    "en": "Living room",
    "pt": "Sala de estar",
    "exampleHtml": "We watch TV in the <b>living room</b>.",
    "examplePt": "Assistimos TV na sala.",
    "pos": "noun"
   },
   {
    "id": "house_9",
    "deckId": "house",
    "en": "Fridge",
    "pt": "Geladeira",
    "exampleHtml": "The milk is in the <b>fridge</b>.",
    "examplePt": "O leite está na geladeira.",
    "pos": "noun"
   },
   {
    "id": "house_10",
    "deckId": "house",
    "en": "Oven",
    "pt": "Forno",
    "exampleHtml": "The <b>oven</b> is hot.",
    "examplePt": "O forno está quente.",
    "pos": "noun"
   },
   {
    "id": "house_11",
    "deckId": "house",
    "en": "Sink",
    "pt": "Pia",
    "exampleHtml": "Wash it in the <b>sink</b>.",
    "examplePt": "Lave na pia.",
    "pos": "noun"
   },
   {
    "id": "house_12",
    "deckId": "house",
    "en": "Shower",
    "pt": "Chuveiro / ducha",
    "exampleHtml": "I'll take a <b>shower</b>.",
    "examplePt": "Vou tomar banho.",
    "pos": "noun"
   },
   {
    "id": "house_13",
    "deckId": "house",
    "en": "Towel",
    "pt": "Toalha",
    "exampleHtml": "Pass me a <b>towel</b>.",
    "examplePt": "Me passa uma toalha.",
    "pos": "noun"
   },
   {
    "id": "house_14",
    "deckId": "house",
    "en": "Blanket",
    "pt": "Cobertor",
    "exampleHtml": "I need another <b>blanket</b>.",
    "examplePt": "Preciso de outro cobertor.",
    "pos": "noun"
   },
   {
    "id": "house_15",
    "deckId": "house",
    "en": "Light",
    "pt": "Luz",
    "exampleHtml": "Turn on the <b>light</b>.",
    "examplePt": "Acenda a luz.",
    "pos": "noun"
   },
   {
    "id": "house_16",
    "deckId": "house",
    "en": "Heater",
    "pt": "Aquecedor",
    "exampleHtml": "Turn on the <b>heater</b>, it's cold.",
    "examplePt": "Liga o aquecedor, está frio.",
    "pos": "noun"
   },
   {
    "id": "house_17",
    "deckId": "house",
    "en": "Clean",
    "pt": "Limpo / limpar",
    "exampleHtml": "The house is <b>clean</b>.",
    "examplePt": "A casa está limpa.",
    "pos": "adj"
   }
  ]
 },
 {
  "id": "clothes",
  "name": "Clothes & weather",
  "emoji": "🧥",
  "desc": "Dress for the Kiwi weather",
  "level": 2,
  "cards": [
   {
    "id": "clothes_0",
    "deckId": "clothes",
    "en": "Clothes",
    "pt": "Roupas",
    "exampleHtml": "I need warm <b>clothes</b>.",
    "examplePt": "Preciso de roupas quentes.",
    "pos": "noun"
   },
   {
    "id": "clothes_1",
    "deckId": "clothes",
    "en": "Shirt",
    "pt": "Camisa",
    "exampleHtml": "A blue <b>shirt</b>.",
    "examplePt": "Uma camisa azul.",
    "pos": "noun"
   },
   {
    "id": "clothes_2",
    "deckId": "clothes",
    "en": "Jacket",
    "pt": "Jaqueta",
    "exampleHtml": "Bring a <b>jacket</b>.",
    "examplePt": "Leve uma jaqueta.",
    "pos": "noun"
   },
   {
    "id": "clothes_3",
    "deckId": "clothes",
    "en": "Coat",
    "pt": "Casaco",
    "exampleHtml": "It's cold — wear a <b>coat</b>.",
    "examplePt": "Está frio — use um casaco.",
    "pos": "noun"
   },
   {
    "id": "clothes_4",
    "deckId": "clothes",
    "en": "Shoes",
    "pt": "Sapatos",
    "exampleHtml": "Nice <b>shoes</b>!",
    "examplePt": "Sapatos legais!",
    "pos": "noun"
   },
   {
    "id": "clothes_5",
    "deckId": "clothes",
    "en": "Socks",
    "pt": "Meias",
    "exampleHtml": "Warm <b>socks</b> for winter.",
    "examplePt": "Meias quentes pro inverno.",
    "pos": "noun"
   },
   {
    "id": "clothes_6",
    "deckId": "clothes",
    "en": "Pants",
    "pt": "Calça",
    "exampleHtml": "New <b>pants</b>.",
    "examplePt": "Calça nova.",
    "pos": "noun"
   },
   {
    "id": "clothes_7",
    "deckId": "clothes",
    "en": "Dress",
    "pt": "Vestido",
    "exampleHtml": "A pretty <b>dress</b>.",
    "examplePt": "Um vestido bonito.",
    "pos": "noun"
   },
   {
    "id": "clothes_8",
    "deckId": "clothes",
    "en": "Hat",
    "pt": "Chapéu / gorro",
    "exampleHtml": "Wear a <b>hat</b>.",
    "examplePt": "Use um gorro.",
    "pos": "noun"
   },
   {
    "id": "clothes_9",
    "deckId": "clothes",
    "en": "Umbrella",
    "pt": "Guarda-chuva",
    "exampleHtml": "Take an <b>umbrella</b>, it might rain.",
    "examplePt": "Leve um guarda-chuva, pode chover.",
    "pos": "noun"
   },
   {
    "id": "clothes_10",
    "deckId": "clothes",
    "en": "Raincoat",
    "pt": "Capa de chuva",
    "exampleHtml": "A <b>raincoat</b> is useful in NZ.",
    "examplePt": "Capa de chuva é útil na NZ.",
    "pos": "noun"
   },
   {
    "id": "clothes_11",
    "deckId": "clothes",
    "en": "Weather",
    "pt": "Tempo / clima",
    "exampleHtml": "How's the <b>weather</b>?",
    "examplePt": "Como está o tempo?",
    "pos": "noun"
   },
   {
    "id": "clothes_12",
    "deckId": "clothes",
    "en": "Rain",
    "pt": "Chuva",
    "exampleHtml": "There's a lot of <b>rain</b> today.",
    "examplePt": "Tem muita chuva hoje.",
    "pos": "noun"
   },
   {
    "id": "clothes_13",
    "deckId": "clothes",
    "en": "Wind",
    "pt": "Vento",
    "exampleHtml": "Wellington has a lot of <b>wind</b>.",
    "examplePt": "Wellington tem muito vento.",
    "pos": "noun"
   },
   {
    "id": "clothes_14",
    "deckId": "clothes",
    "en": "Sunny",
    "pt": "Ensolarado",
    "exampleHtml": "It's <b>sunny</b> today.",
    "examplePt": "Está ensolarado hoje.",
    "pos": "adj"
   },
   {
    "id": "clothes_15",
    "deckId": "clothes",
    "en": "Cloudy",
    "pt": "Nublado",
    "exampleHtml": "It's <b>cloudy</b>.",
    "examplePt": "Está nublado.",
    "pos": "adj"
   },
   {
    "id": "clothes_16",
    "deckId": "clothes",
    "en": "Wet",
    "pt": "Molhado",
    "exampleHtml": "The ground is <b>wet</b>.",
    "examplePt": "O chão está molhado.",
    "pos": "adj"
   },
   {
    "id": "clothes_17",
    "deckId": "clothes",
    "en": "Warm",
    "pt": "Quentinho / agradável",
    "exampleHtml": "It's nice and <b>warm</b> inside.",
    "examplePt": "Está bem quentinho aqui dentro.",
    "pos": "adj"
   }
  ]
 },
 {
  "id": "body",
  "name": "The body",
  "emoji": "🧍",
  "desc": "Useful at the doctor and daily life",
  "level": 2,
  "cards": [
   {
    "id": "body_0",
    "deckId": "body",
    "en": "Head",
    "pt": "Cabeça",
    "exampleHtml": "My <b>head</b> hurts.",
    "examplePt": "Minha cabeça dói.",
    "pos": "noun"
   },
   {
    "id": "body_1",
    "deckId": "body",
    "en": "Hand",
    "pt": "Mão",
    "exampleHtml": "Give me your <b>hand</b>.",
    "examplePt": "Me dá a mão.",
    "pos": "noun"
   },
   {
    "id": "body_2",
    "deckId": "body",
    "en": "Arm",
    "pt": "Braço",
    "exampleHtml": "My <b>arm</b> is sore.",
    "examplePt": "Meu braço está dolorido.",
    "pos": "noun"
   },
   {
    "id": "body_3",
    "deckId": "body",
    "en": "Leg",
    "pt": "Perna",
    "exampleHtml": "My <b>leg</b> hurts.",
    "examplePt": "Minha perna dói.",
    "pos": "noun"
   },
   {
    "id": "body_4",
    "deckId": "body",
    "en": "Foot",
    "pt": "Pé",
    "exampleHtml": "My <b>foot</b> is cold.",
    "examplePt": "Meu pé está frio.",
    "pos": "noun"
   },
   {
    "id": "body_5",
    "deckId": "body",
    "en": "Eye",
    "pt": "Olho",
    "exampleHtml": "Something's in my <b>eye</b>.",
    "examplePt": "Tem algo no meu olho.",
    "pos": "noun"
   },
   {
    "id": "body_6",
    "deckId": "body",
    "en": "Ear",
    "pt": "Orelha / ouvido",
    "exampleHtml": "My <b>ear</b> hurts.",
    "examplePt": "Meu ouvido dói.",
    "pos": "noun"
   },
   {
    "id": "body_7",
    "deckId": "body",
    "en": "Mouth",
    "pt": "Boca",
    "exampleHtml": "Open your <b>mouth</b>.",
    "examplePt": "Abra a boca.",
    "pos": "noun"
   },
   {
    "id": "body_8",
    "deckId": "body",
    "en": "Nose",
    "pt": "Nariz",
    "exampleHtml": "My <b>nose</b> is blocked.",
    "examplePt": "Meu nariz está entupido.",
    "pos": "noun"
   },
   {
    "id": "body_9",
    "deckId": "body",
    "en": "Tooth",
    "pt": "Dente",
    "exampleHtml": "My <b>tooth</b> hurts.",
    "examplePt": "Meu dente dói.",
    "pos": "noun"
   },
   {
    "id": "body_10",
    "deckId": "body",
    "en": "Stomach",
    "pt": "Estômago / barriga",
    "exampleHtml": "I have a <b>stomach</b> ache.",
    "examplePt": "Estou com dor de barriga.",
    "pos": "noun"
   },
   {
    "id": "body_11",
    "deckId": "body",
    "en": "Back",
    "pt": "Costas",
    "exampleHtml": "My <b>back</b> is sore.",
    "examplePt": "Minhas costas doem.",
    "pos": "noun"
   },
   {
    "id": "body_12",
    "deckId": "body",
    "en": "Throat",
    "pt": "Garganta",
    "exampleHtml": "I have a sore <b>throat</b>.",
    "examplePt": "Estou com dor de garganta.",
    "pos": "noun"
   },
   {
    "id": "body_13",
    "deckId": "body",
    "en": "Hair",
    "pt": "Cabelo",
    "exampleHtml": "She has long <b>hair</b>.",
    "examplePt": "Ela tem cabelo comprido.",
    "pos": "noun"
   }
  ]
 },
 {
  "id": "questions",
  "name": "Question & linking words",
  "emoji": "❓",
  "desc": "Ask anything and join your ideas",
  "level": 1,
  "cards": [
   {
    "id": "questions_0",
    "deckId": "questions",
    "en": "What",
    "pt": "O que / qual",
    "exampleHtml": "<b>What</b> is this?",
    "examplePt": "O que é isto?",
    "pos": "word"
   },
   {
    "id": "questions_1",
    "deckId": "questions",
    "en": "Where",
    "pt": "Onde",
    "exampleHtml": "<b>Where</b> is the bus?",
    "examplePt": "Onde está o ônibus?",
    "pos": "word"
   },
   {
    "id": "questions_2",
    "deckId": "questions",
    "en": "When",
    "pt": "Quando",
    "exampleHtml": "<b>When</b> does it open?",
    "examplePt": "Quando abre?",
    "pos": "word"
   },
   {
    "id": "questions_3",
    "deckId": "questions",
    "en": "Who",
    "pt": "Quem",
    "exampleHtml": "<b>Who</b> is that?",
    "examplePt": "Quem é aquele?",
    "pos": "word"
   },
   {
    "id": "questions_4",
    "deckId": "questions",
    "en": "Why",
    "pt": "Por quê",
    "exampleHtml": "<b>Why</b> is it closed?",
    "examplePt": "Por que está fechado?",
    "pos": "word"
   },
   {
    "id": "questions_5",
    "deckId": "questions",
    "en": "How",
    "pt": "Como",
    "exampleHtml": "<b>How</b> does this work?",
    "examplePt": "Como isto funciona?",
    "pos": "word"
   },
   {
    "id": "questions_6",
    "deckId": "questions",
    "en": "Which",
    "pt": "Qual (de opções)",
    "exampleHtml": "<b>Which</b> one do you want?",
    "examplePt": "Qual você quer?",
    "pos": "word"
   },
   {
    "id": "questions_7",
    "deckId": "questions",
    "en": "How much",
    "pt": "Quanto (preço)",
    "exampleHtml": "<b>How much</b> is this?",
    "examplePt": "Quanto custa isto?",
    "pos": "phrase"
   },
   {
    "id": "questions_8",
    "deckId": "questions",
    "en": "How many",
    "pt": "Quantos",
    "exampleHtml": "<b>How many</b> do you need?",
    "examplePt": "Quantos você precisa?",
    "pos": "phrase"
   },
   {
    "id": "questions_9",
    "deckId": "questions",
    "en": "And",
    "pt": "E",
    "exampleHtml": "Tea <b>and</b> bread.",
    "examplePt": "Chá e pão.",
    "pos": "word"
   },
   {
    "id": "questions_10",
    "deckId": "questions",
    "en": "But",
    "pt": "Mas",
    "exampleHtml": "I want to, <b>but</b> I can't.",
    "examplePt": "Eu quero, mas não posso.",
    "pos": "word"
   },
   {
    "id": "questions_11",
    "deckId": "questions",
    "en": "Because",
    "pt": "Porque",
    "exampleHtml": "I'm late <b>because</b> of the bus.",
    "examplePt": "Estou atrasada por causa do ônibus.",
    "pos": "word"
   },
   {
    "id": "questions_12",
    "deckId": "questions",
    "en": "Also",
    "pt": "Também",
    "exampleHtml": "I'd like tea, <b>also</b> water.",
    "examplePt": "Quero chá, também água.",
    "pos": "word"
   },
   {
    "id": "questions_13",
    "deckId": "questions",
    "en": "Or",
    "pt": "Ou",
    "exampleHtml": "Tea <b>or</b> coffee?",
    "examplePt": "Chá ou café?",
    "pos": "word"
   },
   {
    "id": "questions_14",
    "deckId": "questions",
    "en": "If",
    "pt": "Se",
    "exampleHtml": "<b>If</b> it rains, we'll stay home.",
    "examplePt": "Se chover, ficamos em casa.",
    "pos": "word"
   },
   {
    "id": "questions_15",
    "deckId": "questions",
    "en": "So",
    "pt": "Então / por isso",
    "exampleHtml": "It's late, <b>so</b> let's go.",
    "examplePt": "Está tarde, então vamos.",
    "pos": "word"
   }
  ]
 },
 {
  "id": "arrival",
  "name": "Airport & immigration",
  "emoji": "🛂",
  "desc": "Arriving in NZ — the exact words you'll hear",
  "level": 3,
  "cards": [
   {
    "id": "arrival_0",
    "deckId": "arrival",
    "en": "Passport",
    "pt": "Passaporte",
    "exampleHtml": "Here's my <b>passport</b>.",
    "examplePt": "Aqui está meu passaporte.",
    "pos": "noun"
   },
   {
    "id": "arrival_1",
    "deckId": "arrival",
    "en": "Visa",
    "pt": "Visto",
    "exampleHtml": "I have a work <b>visa</b>.",
    "examplePt": "Eu tenho um visto de trabalho.",
    "pos": "noun"
   },
   {
    "id": "arrival_2",
    "deckId": "arrival",
    "en": "Flight",
    "pt": "Voo",
    "exampleHtml": "My <b>flight</b> was long.",
    "examplePt": "Meu voo foi longo.",
    "pos": "noun"
   },
   {
    "id": "arrival_3",
    "deckId": "arrival",
    "en": "Boarding pass",
    "pt": "Cartão de embarque",
    "exampleHtml": "Show your <b>boarding pass</b>.",
    "examplePt": "Mostre seu cartão de embarque.",
    "pos": "noun"
   },
   {
    "id": "arrival_4",
    "deckId": "arrival",
    "en": "Luggage",
    "pt": "Bagagem",
    "exampleHtml": "Where is my <b>luggage</b>?",
    "examplePt": "Onde está minha bagagem?",
    "pos": "noun"
   },
   {
    "id": "arrival_5",
    "deckId": "arrival",
    "en": "Baggage claim",
    "pt": "Esteira de bagagem",
    "exampleHtml": "Go to <b>baggage claim</b>.",
    "examplePt": "Vá à esteira de bagagem.",
    "pos": "phrase"
   },
   {
    "id": "arrival_6",
    "deckId": "arrival",
    "en": "Arrival",
    "pt": "Chegada",
    "exampleHtml": "<b>Arrival</b> hall is this way.",
    "examplePt": "O saguão de chegada é por aqui.",
    "pos": "noun"
   },
   {
    "id": "arrival_7",
    "deckId": "arrival",
    "en": "Customs",
    "pt": "Alfândega",
    "exampleHtml": "Please go through <b>customs</b>.",
    "examplePt": "Passe pela alfândega.",
    "pos": "noun"
   },
   {
    "id": "arrival_8",
    "deckId": "arrival",
    "en": "Immigration",
    "pt": "Imigração",
    "exampleHtml": "The <b>immigration</b> officer was kind.",
    "examplePt": "O oficial de imigração foi gentil.",
    "pos": "noun"
   },
   {
    "id": "arrival_9",
    "deckId": "arrival",
    "en": "Biosecurity",
    "pt": "Biossegurança (importante na NZ!)",
    "exampleHtml": "NZ has strict <b>biosecurity</b> rules.",
    "examplePt": "A NZ tem regras rígidas de biossegurança.",
    "pos": "noun"
   },
   {
    "id": "arrival_10",
    "deckId": "arrival",
    "en": "Declare",
    "pt": "Declarar",
    "exampleHtml": "Do you have anything to <b>declare</b>?",
    "examplePt": "Você tem algo a declarar?",
    "pos": "verb"
   },
   {
    "id": "arrival_11",
    "deckId": "arrival",
    "en": "Nothing to declare",
    "pt": "Nada a declarar",
    "exampleHtml": "I have <b>nothing to declare</b>.",
    "examplePt": "Não tenho nada a declarar.",
    "pos": "phrase"
   },
   {
    "id": "arrival_12",
    "deckId": "arrival",
    "en": "No food or plants",
    "pt": "Sem comida nem plantas",
    "exampleHtml": "<b>No food or plants</b> in your bag?",
    "examplePt": "Sem comida nem plantas na mala?",
    "pos": "phrase"
   },
   {
    "id": "arrival_13",
    "deckId": "arrival",
    "en": "Purpose of visit",
    "pt": "Motivo da viagem",
    "exampleHtml": "What's the <b>purpose of your visit</b>?",
    "examplePt": "Qual o motivo da sua viagem?",
    "pos": "phrase"
   },
   {
    "id": "arrival_14",
    "deckId": "arrival",
    "en": "I'm moving here",
    "pt": "Estou me mudando pra cá",
    "exampleHtml": "<b>I'm moving here</b> to live and work.",
    "examplePt": "Estou me mudando pra cá pra morar e trabalhar.",
    "pos": "phrase"
   },
   {
    "id": "arrival_15",
    "deckId": "arrival",
    "en": "Residence",
    "pt": "Residência",
    "exampleHtml": "We got <b>residence</b> visas.",
    "examplePt": "Conseguimos vistos de residência.",
    "pos": "noun"
   }
  ]
 },
 {
  "id": "town",
  "name": "Around town",
  "emoji": "🧭",
  "desc": "Places you'll go every week",
  "level": 2,
  "cards": [
   {
    "id": "town_0",
    "deckId": "town",
    "en": "Street",
    "pt": "Rua",
    "exampleHtml": "What <b>street</b> is this?",
    "examplePt": "Que rua é esta?",
    "pos": "noun"
   },
   {
    "id": "town_1",
    "deckId": "town",
    "en": "Road",
    "pt": "Estrada / via",
    "exampleHtml": "It's on the main <b>road</b>.",
    "examplePt": "É na via principal.",
    "pos": "noun"
   },
   {
    "id": "town_2",
    "deckId": "town",
    "en": "Corner",
    "pt": "Esquina",
    "exampleHtml": "It's on the <b>corner</b>.",
    "examplePt": "É na esquina.",
    "pos": "noun"
   },
   {
    "id": "town_3",
    "deckId": "town",
    "en": "Shop",
    "pt": "Loja",
    "exampleHtml": "The <b>shop</b> is closed.",
    "examplePt": "A loja está fechada.",
    "pos": "noun"
   },
   {
    "id": "town_4",
    "deckId": "town",
    "en": "Bank",
    "pt": "Banco",
    "exampleHtml": "I'm going to the <b>bank</b>.",
    "examplePt": "Vou ao banco.",
    "pos": "noun"
   },
   {
    "id": "town_5",
    "deckId": "town",
    "en": "Post office",
    "pt": "Correios",
    "exampleHtml": "Where's the <b>post office</b>?",
    "examplePt": "Onde ficam os correios?",
    "pos": "noun"
   },
   {
    "id": "town_6",
    "deckId": "town",
    "en": "Library",
    "pt": "Biblioteca",
    "exampleHtml": "The <b>library</b> is free to join.",
    "examplePt": "A biblioteca é grátis pra se cadastrar.",
    "pos": "noun"
   },
   {
    "id": "town_7",
    "deckId": "town",
    "en": "Park",
    "pt": "Parque",
    "exampleHtml": "Let's go to the <b>park</b>.",
    "examplePt": "Vamos ao parque.",
    "pos": "noun"
   },
   {
    "id": "town_8",
    "deckId": "town",
    "en": "School",
    "pt": "Escola",
    "exampleHtml": "The <b>school</b> is nearby.",
    "examplePt": "A escola é perto.",
    "pos": "noun"
   },
   {
    "id": "town_9",
    "deckId": "town",
    "en": "Petrol station",
    "pt": "Posto de gasolina",
    "exampleHtml": "Stop at the <b>petrol station</b>.",
    "examplePt": "Pare no posto.",
    "pos": "noun"
   },
   {
    "id": "town_10",
    "deckId": "town",
    "en": "Toilet",
    "pt": "Banheiro (público)",
    "exampleHtml": "Where's the <b>toilet</b>?",
    "examplePt": "Onde fica o banheiro?",
    "pos": "noun"
   },
   {
    "id": "town_11",
    "deckId": "town",
    "en": "Café",
    "pt": "Cafeteria",
    "exampleHtml": "Meet me at the <b>café</b>.",
    "examplePt": "Me encontra na cafeteria.",
    "pos": "noun"
   },
   {
    "id": "town_12",
    "deckId": "town",
    "en": "Beach",
    "pt": "Praia",
    "exampleHtml": "The <b>beach</b> is beautiful.",
    "examplePt": "A praia é linda.",
    "pos": "noun"
   },
   {
    "id": "town_13",
    "deckId": "town",
    "en": "City centre",
    "pt": "Centro da cidade",
    "exampleHtml": "Take the bus to the <b>city centre</b>.",
    "examplePt": "Pegue o ônibus pro centro.",
    "pos": "noun"
   },
   {
    "id": "town_14",
    "deckId": "town",
    "en": "Here",
    "pt": "Aqui",
    "exampleHtml": "It's right <b>here</b>.",
    "examplePt": "É bem aqui.",
    "pos": "word"
   },
   {
    "id": "town_15",
    "deckId": "town",
    "en": "There",
    "pt": "Lá / ali",
    "exampleHtml": "It's over <b>there</b>.",
    "examplePt": "É ali.",
    "pos": "word"
   }
  ]
 },
 {
  "id": "basics",
  "name": "Colours & describing",
  "emoji": "🎨",
  "desc": "Colours and useful adjectives",
  "level": 1,
  "cards": [
   {
    "id": "basics_0",
    "deckId": "basics",
    "en": "Colour",
    "pt": "Cor",
    "exampleHtml": "What <b>colour</b> is it?",
    "examplePt": "De que cor é?",
    "pos": "noun"
   },
   {
    "id": "basics_1",
    "deckId": "basics",
    "en": "Red",
    "pt": "Vermelho",
    "exampleHtml": "A <b>red</b> car.",
    "examplePt": "Um carro vermelho.",
    "pos": "adj"
   },
   {
    "id": "basics_2",
    "deckId": "basics",
    "en": "Blue",
    "pt": "Azul",
    "exampleHtml": "A <b>blue</b> shirt.",
    "examplePt": "Uma camisa azul.",
    "pos": "adj"
   },
   {
    "id": "basics_3",
    "deckId": "basics",
    "en": "Green",
    "pt": "Verde",
    "exampleHtml": "A <b>green</b> apple.",
    "examplePt": "Uma maçã verde.",
    "pos": "adj"
   },
   {
    "id": "basics_4",
    "deckId": "basics",
    "en": "Yellow",
    "pt": "Amarelo",
    "exampleHtml": "A <b>yellow</b> bag.",
    "examplePt": "Uma bolsa amarela.",
    "pos": "adj"
   },
   {
    "id": "basics_5",
    "deckId": "basics",
    "en": "Black",
    "pt": "Preto",
    "exampleHtml": "<b>Black</b> shoes.",
    "examplePt": "Sapatos pretos.",
    "pos": "adj"
   },
   {
    "id": "basics_6",
    "deckId": "basics",
    "en": "White",
    "pt": "Branco",
    "exampleHtml": "A <b>white</b> wall.",
    "examplePt": "Uma parede branca.",
    "pos": "adj"
   },
   {
    "id": "basics_7",
    "deckId": "basics",
    "en": "Big",
    "pt": "Grande",
    "exampleHtml": "A <b>big</b> house.",
    "examplePt": "Uma casa grande.",
    "pos": "adj"
   },
   {
    "id": "basics_8",
    "deckId": "basics",
    "en": "Small",
    "pt": "Pequeno",
    "exampleHtml": "A <b>small</b> flat.",
    "examplePt": "Um apê pequeno.",
    "pos": "adj"
   },
   {
    "id": "basics_9",
    "deckId": "basics",
    "en": "New",
    "pt": "Novo",
    "exampleHtml": "A <b>new</b> job.",
    "examplePt": "Um emprego novo.",
    "pos": "adj"
   },
   {
    "id": "basics_10",
    "deckId": "basics",
    "en": "Old",
    "pt": "Velho / antigo",
    "exampleHtml": "An <b>old</b> car.",
    "examplePt": "Um carro velho.",
    "pos": "adj"
   },
   {
    "id": "basics_11",
    "deckId": "basics",
    "en": "Good",
    "pt": "Bom",
    "exampleHtml": "This is <b>good</b>.",
    "examplePt": "Isto é bom.",
    "pos": "adj"
   },
   {
    "id": "basics_12",
    "deckId": "basics",
    "en": "Bad",
    "pt": "Ruim",
    "exampleHtml": "The weather is <b>bad</b>.",
    "examplePt": "O tempo está ruim.",
    "pos": "adj"
   },
   {
    "id": "basics_13",
    "deckId": "basics",
    "en": "Beautiful",
    "pt": "Lindo / bonito",
    "exampleHtml": "What a <b>beautiful</b> view!",
    "examplePt": "Que vista linda!",
    "pos": "adj"
   },
   {
    "id": "basics_14",
    "deckId": "basics",
    "en": "Easy",
    "pt": "Fácil",
    "exampleHtml": "It's <b>easy</b>.",
    "examplePt": "É fácil.",
    "pos": "adj"
   },
   {
    "id": "basics_15",
    "deckId": "basics",
    "en": "Difficult",
    "pt": "Difícil",
    "exampleHtml": "English is <b>difficult</b> but I'm learning.",
    "examplePt": "Inglês é difícil mas estou aprendendo.",
    "pos": "adj"
   }
  ]
 },
 {
  "id": "verbs2",
  "name": "More everyday verbs",
  "emoji": "⚡",
  "desc": "Another set of high-use verbs",
  "level": 2,
  "cards": [
   {
    "id": "verbs2_0",
    "deckId": "verbs2",
    "en": "to give",
    "pt": "dar",
    "exampleHtml": "Can you <b>give</b> me that?",
    "examplePt": "Pode me dar aquilo?",
    "pos": "verb"
   },
   {
    "id": "verbs2_1",
    "deckId": "verbs2",
    "en": "to take",
    "pt": "pegar / levar",
    "exampleHtml": "I'll <b>take</b> this one.",
    "examplePt": "Vou levar este.",
    "pos": "verb"
   },
   {
    "id": "verbs2_2",
    "deckId": "verbs2",
    "en": "to make",
    "pt": "fazer (criar)",
    "exampleHtml": "I'll <b>make</b> dinner.",
    "examplePt": "Vou fazer o jantar.",
    "pos": "verb"
   },
   {
    "id": "verbs2_3",
    "deckId": "verbs2",
    "en": "to do",
    "pt": "fazer",
    "exampleHtml": "What do you <b>do</b> on weekends?",
    "examplePt": "O que você faz nos fins de semana?",
    "pos": "verb"
   },
   {
    "id": "verbs2_4",
    "deckId": "verbs2",
    "en": "to say",
    "pt": "dizer",
    "exampleHtml": "What did you <b>say</b>?",
    "examplePt": "O que você disse?",
    "pos": "verb"
   },
   {
    "id": "verbs2_5",
    "deckId": "verbs2",
    "en": "to tell",
    "pt": "contar / dizer",
    "exampleHtml": "<b>Tell</b> me more.",
    "examplePt": "Me conta mais.",
    "pos": "verb"
   },
   {
    "id": "verbs2_6",
    "deckId": "verbs2",
    "en": "to ask",
    "pt": "perguntar / pedir",
    "exampleHtml": "Can I <b>ask</b> a question?",
    "examplePt": "Posso fazer uma pergunta?",
    "pos": "verb"
   },
   {
    "id": "verbs2_7",
    "deckId": "verbs2",
    "en": "to call",
    "pt": "ligar / chamar",
    "exampleHtml": "I'll <b>call</b> you later.",
    "examplePt": "Te ligo mais tarde.",
    "pos": "verb"
   },
   {
    "id": "verbs2_8",
    "deckId": "verbs2",
    "en": "to bring",
    "pt": "trazer",
    "exampleHtml": "<b>Bring</b> your umbrella.",
    "examplePt": "Traga seu guarda-chuva.",
    "pos": "verb"
   },
   {
    "id": "verbs2_9",
    "deckId": "verbs2",
    "en": "to put",
    "pt": "colocar / pôr",
    "exampleHtml": "<b>Put</b> it here.",
    "examplePt": "Coloque aqui.",
    "pos": "verb"
   },
   {
    "id": "verbs2_10",
    "deckId": "verbs2",
    "en": "to get",
    "pt": "conseguir / pegar",
    "exampleHtml": "Where can I <b>get</b> a coffee?",
    "examplePt": "Onde consigo um café?",
    "pos": "verb"
   },
   {
    "id": "verbs2_11",
    "deckId": "verbs2",
    "en": "to learn",
    "pt": "aprender",
    "exampleHtml": "I want to <b>learn</b> English.",
    "examplePt": "Quero aprender inglês.",
    "pos": "verb"
   },
   {
    "id": "verbs2_12",
    "deckId": "verbs2",
    "en": "to remember",
    "pt": "lembrar",
    "exampleHtml": "I can't <b>remember</b> his name.",
    "examplePt": "Não lembro o nome dele.",
    "pos": "verb"
   },
   {
    "id": "verbs2_13",
    "deckId": "verbs2",
    "en": "to forget",
    "pt": "esquecer",
    "exampleHtml": "Don't <b>forget</b> your key.",
    "examplePt": "Não esqueça a chave.",
    "pos": "verb"
   },
   {
    "id": "verbs2_14",
    "deckId": "verbs2",
    "en": "to try",
    "pt": "tentar",
    "exampleHtml": "I'll <b>try</b> again.",
    "examplePt": "Vou tentar de novo.",
    "pos": "verb"
   },
   {
    "id": "verbs2_15",
    "deckId": "verbs2",
    "en": "to show",
    "pt": "mostrar",
    "exampleHtml": "Can you <b>show</b> me?",
    "examplePt": "Pode me mostrar?",
    "pos": "verb"
   },
   {
    "id": "verbs2_16",
    "deckId": "verbs2",
    "en": "to start",
    "pt": "começar",
    "exampleHtml": "When does it <b>start</b>?",
    "examplePt": "Quando começa?",
    "pos": "verb"
   },
   {
    "id": "verbs2_17",
    "deckId": "verbs2",
    "en": "to finish",
    "pt": "terminar",
    "exampleHtml": "I <b>finish</b> work at five.",
    "examplePt": "Termino o trabalho às cinco.",
    "pos": "verb"
   }
  ]
 },
 {
  "id": "power",
  "name": "Power phrases",
  "emoji": "💪",
  "desc": "Sentences that get you through the day",
  "level": 2,
  "cards": [
   {
    "id": "power_0",
    "deckId": "power",
    "en": "How do you say… in English?",
    "pt": "Como se diz… em inglês?",
    "exampleHtml": "<b>How do you say</b> 'obrigada' <b>in English?</b>",
    "examplePt": "Como se diz 'obrigada' em inglês?",
    "pos": "phrase"
   },
   {
    "id": "power_1",
    "deckId": "power",
    "en": "What's this called?",
    "pt": "Como se chama isto?",
    "exampleHtml": "<b>What's this called?</b>",
    "examplePt": "Como isto se chama?",
    "pos": "phrase"
   },
   {
    "id": "power_2",
    "deckId": "power",
    "en": "Can you write it down?",
    "pt": "Pode escrever pra mim?",
    "exampleHtml": "<b>Can you write it down</b>, please?",
    "examplePt": "Pode escrever, por favor?",
    "pos": "phrase"
   },
   {
    "id": "power_3",
    "deckId": "power",
    "en": "I'm not sure",
    "pt": "Não tenho certeza",
    "exampleHtml": "<b>I'm not sure</b>, sorry.",
    "examplePt": "Não tenho certeza, desculpa.",
    "pos": "phrase"
   },
   {
    "id": "power_4",
    "deckId": "power",
    "en": "I think so",
    "pt": "Acho que sim",
    "exampleHtml": "<b>I think so.</b>",
    "examplePt": "Acho que sim.",
    "pos": "phrase"
   },
   {
    "id": "power_5",
    "deckId": "power",
    "en": "Just a moment",
    "pt": "Só um momento",
    "exampleHtml": "<b>Just a moment</b>, please.",
    "examplePt": "Só um momento, por favor.",
    "pos": "phrase"
   },
   {
    "id": "power_6",
    "deckId": "power",
    "en": "I'll be right back",
    "pt": "Já volto",
    "exampleHtml": "<b>I'll be right back.</b>",
    "examplePt": "Já volto.",
    "pos": "phrase"
   },
   {
    "id": "power_7",
    "deckId": "power",
    "en": "Never mind",
    "pt": "Deixa pra lá",
    "exampleHtml": "It's okay, <b>never mind</b>.",
    "examplePt": "Tá tudo bem, deixa pra lá.",
    "pos": "phrase"
   },
   {
    "id": "power_8",
    "deckId": "power",
    "en": "Of course",
    "pt": "Claro",
    "exampleHtml": "<b>Of course!</b> No problem.",
    "examplePt": "Claro! Sem problema.",
    "pos": "phrase"
   },
   {
    "id": "power_9",
    "deckId": "power",
    "en": "That's fine",
    "pt": "Tá tudo bem",
    "exampleHtml": "<b>That's fine</b> with me.",
    "examplePt": "Por mim tá tudo bem.",
    "pos": "phrase"
   },
   {
    "id": "power_10",
    "deckId": "power",
    "en": "Let me check",
    "pt": "Deixa eu verificar",
    "exampleHtml": "<b>Let me check</b> for you.",
    "examplePt": "Deixa eu verificar pra você.",
    "pos": "phrase"
   },
   {
    "id": "power_11",
    "deckId": "power",
    "en": "Can I ask you something?",
    "pt": "Posso te perguntar uma coisa?",
    "exampleHtml": "<b>Can I ask you something?</b>",
    "examplePt": "Posso te perguntar uma coisa?",
    "pos": "phrase"
   },
   {
    "id": "power_12",
    "deckId": "power",
    "en": "I agree",
    "pt": "Concordo",
    "exampleHtml": "<b>I agree</b> with you.",
    "examplePt": "Concordo com você.",
    "pos": "phrase"
   },
   {
    "id": "power_13",
    "deckId": "power",
    "en": "Good idea",
    "pt": "Boa ideia",
    "exampleHtml": "<b>Good idea!</b> Let's do it.",
    "examplePt": "Boa ideia! Vamos fazer isso.",
    "pos": "phrase"
   },
   {
    "id": "power_14",
    "deckId": "power",
    "en": "Don't worry",
    "pt": "Não se preocupe",
    "exampleHtml": "<b>Don't worry</b>, it's fine.",
    "examplePt": "Não se preocupe, tá tudo bem.",
    "pos": "phrase"
   },
   {
    "id": "power_15",
    "deckId": "power",
    "en": "What should I do?",
    "pt": "O que devo fazer?",
    "exampleHtml": "<b>What should I do?</b>",
    "examplePt": "O que eu devo fazer?",
    "pos": "phrase"
   },
   {
    "id": "power_16",
    "deckId": "power",
    "en": "I'll have this one",
    "pt": "Vou querer este",
    "exampleHtml": "<b>I'll have this one</b>, thanks.",
    "examplePt": "Vou querer este, obrigada.",
    "pos": "phrase"
   },
   {
    "id": "power_17",
    "deckId": "power",
    "en": "Slow down, please",
    "pt": "Mais devagar, por favor",
    "exampleHtml": "<b>Slow down, please.</b>",
    "examplePt": "Mais devagar, por favor.",
    "pos": "phrase"
   }
  ]
 },
 {
  "id": "grammar",
  "name": "Essential grammar",
  "emoji": "📘",
  "desc": "The building blocks of sentences",
  "level": 2,
  "cards": [
   {
    "id": "grammar_0",
    "deckId": "grammar",
    "en": "I am / you are / he is",
    "pt": "verbo TO BE (ser/estar): I am, you are, he/she/it is, we/they are",
    "exampleHtml": "<b>I am</b> Ana. <b>You are</b> kind. <b>She is</b> here.",
    "examplePt": "Eu sou Ana. Você é gentil. Ela está aqui.",
    "pos": "grammar"
   },
   {
    "id": "grammar_1",
    "deckId": "grammar",
    "en": "I'm not / isn't / aren't",
    "pt": "Negativo do TO BE: add NOT. I'm not, he isn't, they aren't",
    "exampleHtml": "<b>I'm not</b> ready. He <b>isn't</b> here.",
    "examplePt": "Não estou pronta. Ele não está aqui.",
    "pos": "grammar"
   },
   {
    "id": "grammar_2",
    "deckId": "grammar",
    "en": "Are you…? / Is he…?",
    "pt": "Pergunta com TO BE: inverta o verbo. Are you…? Is she…?",
    "exampleHtml": "<b>Are you</b> okay? <b>Is she</b> your friend?",
    "examplePt": "Você está bem? Ela é sua amiga?",
    "pos": "grammar"
   },
   {
    "id": "grammar_3",
    "deckId": "grammar",
    "en": "a / an",
    "pt": "Artigo 'um/uma'. Use AN antes de som de vogal: a car, an apple",
    "exampleHtml": "I have <b>a</b> car and <b>an</b> apple.",
    "examplePt": "Tenho um carro e uma maçã.",
    "pos": "grammar"
   },
   {
    "id": "grammar_4",
    "deckId": "grammar",
    "en": "the",
    "pt": "'o/a' — coisa específica que os dois conhecem",
    "exampleHtml": "Close <b>the</b> door. <b>The</b> bus is late.",
    "examplePt": "Feche a porta. O ônibus está atrasado.",
    "pos": "grammar"
   },
   {
    "id": "grammar_5",
    "deckId": "grammar",
    "en": "Plurals: add -s",
    "pt": "Plural: geralmente +s. one car → two cars; box → boxes",
    "exampleHtml": "I have two <b>cars</b> and three <b>boxes</b>.",
    "examplePt": "Tenho dois carros e três caixas.",
    "pos": "grammar"
   },
   {
    "id": "grammar_6",
    "deckId": "grammar",
    "en": "this / that / these / those",
    "pt": "this=isto(perto), that=aquilo(longe), these/those=plural",
    "exampleHtml": "<b>This</b> is mine. <b>Those</b> are yours.",
    "examplePt": "Isto é meu. Aqueles são seus.",
    "pos": "grammar"
   },
   {
    "id": "grammar_7",
    "deckId": "grammar",
    "en": "my / your / his / her",
    "pt": "Possessivos: my, your, his, her, our, their",
    "exampleHtml": "<b>My</b> name, <b>your</b> bag, <b>her</b> car.",
    "examplePt": "Meu nome, sua bolsa, o carro dela.",
    "pos": "grammar"
   },
   {
    "id": "grammar_8",
    "deckId": "grammar",
    "en": "Present: I work / she works",
    "pt": "Presente simples. Na 3ª pessoa (he/she/it) add -s: she works",
    "exampleHtml": "I <b>work</b> here. She <b>works</b> there.",
    "examplePt": "Eu trabalho aqui. Ela trabalha ali.",
    "pos": "grammar"
   },
   {
    "id": "grammar_9",
    "deckId": "grammar",
    "en": "I don't / she doesn't",
    "pt": "Negativo no presente: don't (I/you/we/they), doesn't (he/she/it)",
    "exampleHtml": "I <b>don't</b> know. She <b>doesn't</b> live here.",
    "examplePt": "Eu não sei. Ela não mora aqui.",
    "pos": "grammar"
   },
   {
    "id": "grammar_10",
    "deckId": "grammar",
    "en": "Do you…? / Does he…?",
    "pt": "Pergunta no presente: Do you…? Does she…?",
    "exampleHtml": "<b>Do you</b> speak English? <b>Does he</b> work?",
    "examplePt": "Você fala inglês? Ele trabalha?",
    "pos": "grammar"
   },
   {
    "id": "grammar_11",
    "deckId": "grammar",
    "en": "Present continuous: I'm working",
    "pt": "Ação agora: am/is/are + verbo-ING",
    "exampleHtml": "I <b>am working</b> now. It <b>is raining</b>.",
    "examplePt": "Estou trabalhando agora. Está chovendo.",
    "pos": "grammar"
   },
   {
    "id": "grammar_12",
    "deckId": "grammar",
    "en": "Past: worked / went",
    "pt": "Passado: verbos regulares +ed (worked); irregulares mudam (go→went)",
    "exampleHtml": "Yesterday I <b>worked</b> and <b>went</b> home.",
    "examplePt": "Ontem eu trabalhei e fui pra casa.",
    "pos": "grammar"
   },
   {
    "id": "grammar_13",
    "deckId": "grammar",
    "en": "Irregular past: was / had / went",
    "pt": "Comuns: be→was/were, have→had, go→went, do→did, say→said",
    "exampleHtml": "I <b>was</b> tired, so I <b>went</b> to bed.",
    "examplePt": "Eu estava cansada, então fui dormir.",
    "pos": "grammar"
   },
   {
    "id": "grammar_14",
    "deckId": "grammar",
    "en": "Future: will",
    "pt": "Futuro/decisão: WILL + verbo. I will call = I'll call",
    "exampleHtml": "I <b>will</b> help you. She'<b>ll</b> come later.",
    "examplePt": "Vou te ajudar. Ela virá depois.",
    "pos": "grammar"
   },
   {
    "id": "grammar_15",
    "deckId": "grammar",
    "en": "Future: going to",
    "pt": "Plano/intenção: am/is/are + going to + verbo",
    "exampleHtml": "We <b>are going to</b> move to NZ.",
    "examplePt": "Nós vamos nos mudar pra NZ.",
    "pos": "grammar"
   },
   {
    "id": "grammar_16",
    "deckId": "grammar",
    "en": "can / can't",
    "pt": "Habilidade/permissão: can + verbo (sem 'to'). can't = não pode",
    "exampleHtml": "I <b>can</b> swim. I <b>can't</b> drive yet.",
    "examplePt": "Sei nadar. Ainda não sei dirigir.",
    "pos": "grammar"
   },
   {
    "id": "grammar_17",
    "deckId": "grammar",
    "en": "there is / there are",
    "pt": "Existe: there is (singular), there are (plural)",
    "exampleHtml": "<b>There is</b> a shop. <b>There are</b> two rooms.",
    "examplePt": "Tem uma loja. Tem dois quartos.",
    "pos": "grammar"
   },
   {
    "id": "grammar_18",
    "deckId": "grammar",
    "en": "have to / need to",
    "pt": "Obrigação: have to / need to + verbo",
    "exampleHtml": "I <b>have to</b> work. We <b>need to</b> go.",
    "examplePt": "Tenho que trabalhar. Precisamos ir.",
    "pos": "grammar"
   },
   {
    "id": "grammar_19",
    "deckId": "grammar",
    "en": "Comparatives: bigger / more…",
    "pt": "Comparar: curtas +er (bigger); longas more+adj (more expensive)",
    "exampleHtml": "This is <b>bigger</b> and <b>more expensive</b>.",
    "examplePt": "Este é maior e mais caro.",
    "pos": "grammar"
   },
   {
    "id": "grammar_20",
    "deckId": "grammar",
    "en": "would like",
    "pt": "Pedido educado: I would like = I'd like (mais fino que 'I want')",
    "exampleHtml": "<b>I'd like</b> a coffee, please.",
    "examplePt": "Eu gostaria de um café, por favor.",
    "pos": "grammar"
   },
   {
    "id": "grammar_21",
    "deckId": "grammar",
    "en": "Object words: me/you/him/her",
    "pt": "Depois do verbo: me, you, him, her, us, them",
    "exampleHtml": "Call <b>me</b>. I saw <b>her</b>. Help <b>us</b>.",
    "examplePt": "Me liga. Eu a vi. Nos ajude.",
    "pos": "grammar"
   }
  ]
 }
]
