// GENERATED by scripts/extract-content.mjs — DO NOT EDIT BY HAND.
import type { Dialogue } from '../types'

export const DIALOGUES: Dialogue[] = [
 {
  "id": "dlg_0",
  "title": "At the café",
  "emoji": "☕",
  "lines": [
   {
    "who": "Barista",
    "en": "Hi there! What can I get you?",
    "pt": "Oi! O que você vai querer?"
   },
   {
    "who": "You",
    "en": "Hi, can I have a coffee, please?",
    "pt": "Oi, pode me ver um café, por favor?"
   },
   {
    "who": "Barista",
    "en": "Sure. Have here or takeaway?",
    "pt": "Claro. Pra comer aqui ou pra viagem?"
   },
   {
    "who": "You",
    "en": "Takeaway, thanks.",
    "pt": "Pra viagem, obrigada."
   },
   {
    "who": "Barista",
    "en": "That's five fifty.",
    "pt": "São cinco e cinquenta."
   },
   {
    "who": "You",
    "en": "Can I pay by card?",
    "pt": "Posso pagar no cartão?"
   },
   {
    "who": "Barista",
    "en": "Of course, pop it on there.",
    "pt": "Claro, passe aqui."
   },
   {
    "who": "You",
    "en": "Thanks, cheers!",
    "pt": "Obrigada, valeu!"
   }
  ]
 },
 {
  "id": "dlg_1",
  "title": "Viewing an apartment",
  "emoji": "🏠",
  "lines": [
   {
    "who": "Agent",
    "en": "Hi, are you here for the showing?",
    "pt": "Oi, você veio pra visita?"
   },
   {
    "who": "You",
    "en": "Yes, we're interested in renting.",
    "pt": "Sim, estamos interessados em alugar."
   },
   {
    "who": "Agent",
    "en": "Great. It has two bedrooms and a heat pump.",
    "pt": "Ótimo. Tem dois quartos e um heat pump."
   },
   {
    "who": "You",
    "en": "How much is the rent per month?",
    "pt": "Quanto é o aluguel por mês?"
   },
   {
    "who": "Agent",
    "en": "It's two thousand a month.",
    "pt": "São dois mil por mês."
   },
   {
    "who": "You",
    "en": "And how much is the security deposit?",
    "pt": "E quanto é o depósito de segurança?"
   },
   {
    "who": "Agent",
    "en": "One month's rent, paid upfront.",
    "pt": "Um mês de aluguel, adiantado."
   },
   {
    "who": "You",
    "en": "Thank you. When can we move in?",
    "pt": "Obrigada. Quando podemos entrar?"
   }
  ]
 },
 {
  "id": "dlg_2",
  "title": "At the doctor",
  "emoji": "🩺",
  "lines": [
   {
    "who": "Reception",
    "en": "Hi there, do you have an appointment?",
    "pt": "Oi, você tem hora marcada?"
   },
   {
    "who": "You",
    "en": "Yes, at ten with the nurse.",
    "pt": "Sim, às dez com o enfermeiro."
   },
   {
    "who": "Nurse",
    "en": "Come through. What's the problem today?",
    "pt": "Pode vir. Qual é o problema hoje?"
   },
   {
    "who": "You",
    "en": "I have a sore throat and a fever.",
    "pt": "Estou com dor de garganta e febre."
   },
   {
    "who": "Nurse",
    "en": "How long have you felt like this?",
    "pt": "Há quanto tempo você está assim?"
   },
   {
    "who": "You",
    "en": "For three days.",
    "pt": "Faz três dias."
   },
   {
    "who": "Nurse",
    "en": "I'll give you a prescription for the pharmacy.",
    "pt": "Vou te dar uma receita pra farmácia."
   },
   {
    "who": "You",
    "en": "Thank you so much.",
    "pt": "Muito obrigada."
   }
  ]
 },
 {
  "id": "dlg_3",
  "title": "At the supermarket",
  "emoji": "🛒",
  "lines": [
   {
    "who": "You",
    "en": "Excuse me, where is the milk?",
    "pt": "Com licença, onde fica o leite?"
   },
   {
    "who": "Staff",
    "en": "It's down the back, on the left.",
    "pt": "É lá no fundo, à esquerda."
   },
   {
    "who": "You",
    "en": "Thanks. Are these apples on sale?",
    "pt": "Obrigada. Essas maçãs estão em promoção?"
   },
   {
    "who": "Staff",
    "en": "Yeah, two dollars a pound.",
    "pt": "Sim, dois dólares a libra."
   },
   {
    "who": "Checkout",
    "en": "Hi, do you need a bag?",
    "pt": "Oi, você precisa de sacola?"
   },
   {
    "who": "You",
    "en": "Yes, please. Can I tap to pay?",
    "pt": "Sim, por favor. Posso pagar por aproximação?"
   },
   {
    "who": "Checkout",
    "en": "Sure, tap when you're ready.",
    "pt": "Claro, aproxime quando quiser."
   },
   {
    "who": "You",
    "en": "Thanks!",
    "pt": "Obrigada!"
   }
  ]
 },
 {
  "id": "dlg_4",
  "title": "Meeting a neighbor",
  "emoji": "👋",
  "lines": [
   {
    "who": "Neighbor",
    "en": "Hey, are you new here?",
    "pt": "Oi, você é nova por aqui?"
   },
   {
    "who": "You",
    "en": "Yes, we just moved from Brazil.",
    "pt": "Sim, acabamos de mudar do Brasil."
   },
   {
    "who": "Neighbor",
    "en": "Oh, lovely! Welcome. How's it going?",
    "pt": "Ah, que ótimo! Bem-vinda. Como vão as coisas?"
   },
   {
    "who": "You",
    "en": "Good, thanks. I'm still learning English.",
    "pt": "Bem, obrigada. Ainda estou aprendendo inglês."
   },
   {
    "who": "Neighbor",
    "en": "You're doing great. I'm Sam, by the way.",
    "pt": "Você está indo muito bem. Aliás, sou o Sam."
   },
   {
    "who": "You",
    "en": "Nice to meet you, Sam. I'm Ana.",
    "pt": "Prazer, Sam. Sou a Ana."
   },
   {
    "who": "Neighbor",
    "en": "If you need anything, just knock.",
    "pt": "Se precisar de algo, é só bater na porta."
   },
   {
    "who": "You",
    "en": "Thank you, that's very kind.",
    "pt": "Obrigada, muito gentil."
   }
  ]
 },
 {
  "id": "dlg_5",
  "title": "At immigration (arrival)",
  "emoji": "🛂",
  "lines": [
   {
    "who": "Officer",
    "en": "Good morning. Passport, please.",
    "pt": "Bom dia. Passaporte, por favor."
   },
   {
    "who": "You",
    "en": "Here you are.",
    "pt": "Aqui está."
   },
   {
    "who": "Officer",
    "en": "What's the purpose of your visit?",
    "pt": "Qual é o motivo da sua viagem?"
   },
   {
    "who": "You",
    "en": "I'm moving here to live and work.",
    "pt": "Estou me mudando pra cá pra morar e trabalhar."
   },
   {
    "who": "Officer",
    "en": "Do you have anything to declare? Any food?",
    "pt": "Tem algo a declarar? Alguma comida?"
   },
   {
    "who": "You",
    "en": "No, nothing to declare.",
    "pt": "Não, nada a declarar."
   },
   {
    "who": "Officer",
    "en": "Great. Welcome to the United States.",
    "pt": "Ótimo. Bem-vinda aos Estados Unidos."
   },
   {
    "who": "You",
    "en": "Thank you very much!",
    "pt": "Muito obrigada!"
   }
  ]
 },
 {
  "id": "dlg_6",
  "title": "A job interview (start)",
  "emoji": "💼",
  "lines": [
   {
    "who": "Manager",
    "en": "Hi, thanks for coming in. Take a seat.",
    "pt": "Oi, obrigado por vir. Sente-se."
   },
   {
    "who": "You",
    "en": "Thank you for the opportunity.",
    "pt": "Obrigada pela oportunidade."
   },
   {
    "who": "Manager",
    "en": "So, tell me a little about yourself.",
    "pt": "Então, me conte um pouco sobre você."
   },
   {
    "who": "You",
    "en": "I'm from Brazil and I have three years of experience.",
    "pt": "Sou do Brasil e tenho três anos de experiência."
   },
   {
    "who": "Manager",
    "en": "When are you available to start?",
    "pt": "Quando você pode começar?"
   },
   {
    "who": "You",
    "en": "I'm available to start right away.",
    "pt": "Estou disponível para começar já."
   },
   {
    "who": "Manager",
    "en": "Great. We'll be in touch this week.",
    "pt": "Ótimo. Entraremos em contato esta semana."
   },
   {
    "who": "You",
    "en": "Thank you for your time.",
    "pt": "Obrigada pelo seu tempo."
   }
  ]
 }
]
