import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const html = readFileSync(resolve(ROOT, 'english-nz.html'), 'utf8')

/** Slice a `const NAME = [ ... ]` array literal out of the HTML by bracket balance. */
function sliceArrayLiteral(source, declaration) {
  const start = source.indexOf(declaration)
  if (start === -1) throw new Error('Declaration not found: ' + declaration)
  const open = source.indexOf('[', start)
  let depth = 0
  let inString = null
  let i = open
  for (; i < source.length; i++) {
    const ch = source[i]
    const prev = source[i - 1]
    if (inString) {
      if (ch === inString && prev !== '\\') inString = null
      continue
    }
    if (ch === '"' || ch === "'" || ch === '`') { inString = ch; continue }
    if (ch === '[') depth++
    else if (ch === ']') { depth--; if (depth === 0) { i++; break } }
  }
  if (depth !== 0) throw new Error('Unbalanced brackets for ' + declaration)
  return source.slice(open, i)
}

const rawDecks = new Function('return ' + sliceArrayLiteral(html, 'const DECKS = ['))()
const rawDialogues = new Function('return ' + sliceArrayLiteral(html, 'const DIALOGUES=['))()

const LEVELS = {
  survival: 1, numbers: 1, verbs: 1, people: 1,
  feelings: 1, questions: 1, basics: 1, emergency: 1,
  house: 2, body: 2, food: 2, clothes: 2, shopping: 2,
  town: 2, verbs2: 2, power: 2, grammar: 2,
  money: 3, transport: 3, smalltalk: 3, arrival: 3,
  housing: 3, health: 3, work: 3, kiwi: 3,
}

const unmapped = rawDecks.map(d => d.id).filter(id => !(id in LEVELS))
if (unmapped.length) throw new Error('Decks with no level mapping: ' + unmapped.join(', '))

const decks = rawDecks.map(d => ({
  id: d.id,
  name: d.name,
  emoji: d.emo,
  desc: d.desc,
  level: LEVELS[d.id],
  cards: d.cards.map((c, i) => ({
    id: d.id + '_' + i,
    deckId: d.id,
    en: c[0],
    pt: c[1],
    exampleHtml: c[2],
    examplePt: c[3],
    pos: c[4],
    ...(c[5] ? { phonetic: c[5] } : {}),
  })),
}))

const dialogues = rawDialogues.map((d, i) => ({
  id: 'dlg_' + i,
  title: d.title,
  emoji: d.emo,
  lines: d.lines.map(l => ({ who: l.w, en: l.en, pt: l.pt })),
}))

const cardCount = decks.reduce((n, d) => n + d.cards.length, 0)
const banner = '// GENERATED by scripts/extract-content.mjs — DO NOT EDIT BY HAND.\n'

mkdirSync(resolve(ROOT, 'src/content'), { recursive: true })

writeFileSync(
  resolve(ROOT, 'src/content/decks.generated.ts'),
  banner + "import type { Deck } from '../types'\n\nexport const GENERATED_DECKS: Deck[] = " +
    JSON.stringify(decks, null, 1) + '\n',
)
writeFileSync(
  resolve(ROOT, 'src/content/dialogues.generated.ts'),
  banner + "import type { Dialogue } from '../types'\n\nexport const DIALOGUES: Dialogue[] = " +
    JSON.stringify(dialogues, null, 1) + '\n',
)

console.log('Extracted ' + decks.length + ' decks, ' + cardCount + ' cards, ' + dialogues.length + ' dialogues.')
